/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * WMS API
 * Warehouse Management System API
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateProductClientAssignmentDto,
  PaginatedResponseDto,
  ProductClientAssignmentResponseDto
} from '../../../types/wms-api';

import { customInstance } from '../../../http/httpClient.js';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type ProductClientAssignmentController_createResponse201 = {
  data: ProductClientAssignmentResponseDto
  status: 201
}

export type ProductClientAssignmentController_createResponseSuccess = (ProductClientAssignmentController_createResponse201) & {
  headers: Headers;
};
;

export type ProductClientAssignmentController_createResponse = (ProductClientAssignmentController_createResponseSuccess)

export const getProductClientAssignmentControllerCreateUrl = () => {




  return `/api/v1/wms/web/product-client-assignments`
}

/**
 * @summary Create product-client assignment
 */
export const ProductClientAssignmentController_create = async (createProductClientAssignmentDto: CreateProductClientAssignmentDto, options?: RequestInit): Promise<ProductClientAssignmentController_createResponse> => {

  return customInstance<ProductClientAssignmentController_createResponse>(getProductClientAssignmentControllerCreateUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createProductClientAssignmentDto)
  }
);}





export const getProductClientAssignmentControllerCreateQueryKey = (createProductClientAssignmentDto?: CreateProductClientAssignmentDto,) => {
    return [
    'POST', `/api/v1/wms/web/product-client-assignments`, createProductClientAssignmentDto
    ] as const;
    }


export const getProductClientAssignmentControllerCreateQueryOptions = <TData = Awaited<ReturnType<typeof ProductClientAssignmentController_create>>, TError = unknown>(createProductClientAssignmentDto: CreateProductClientAssignmentDto, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof ProductClientAssignmentController_create>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getProductClientAssignmentControllerCreateQueryKey(createProductClientAssignmentDto);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof ProductClientAssignmentController_create>>> = ({ signal }) => ProductClientAssignmentController_create(createProductClientAssignmentDto, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof ProductClientAssignmentController_create>>, TError, TData> & { queryKey: QueryKey }
}

export type ProductClientAssignmentControllerCreateQueryResult = NonNullable<Awaited<ReturnType<typeof ProductClientAssignmentController_create>>>
export type ProductClientAssignmentControllerCreateQueryError = unknown


/**
 * @summary Create product-client assignment
 */

export function useProductClientAssignmentControllerCreate<TData = Awaited<ReturnType<typeof ProductClientAssignmentController_create>>, TError = unknown>(
 createProductClientAssignmentDto: CreateProductClientAssignmentDto, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof ProductClientAssignmentController_create>>, TError, TData>, request?: SecondParameter<typeof customInstance>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getProductClientAssignmentControllerCreateQueryOptions(createProductClientAssignmentDto,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}






export type ProductClientAssignmentController_findAllResponse200 = {
  data: PaginatedResponseDto
  status: 200
}

export type ProductClientAssignmentController_findAllResponseSuccess = (ProductClientAssignmentController_findAllResponse200) & {
  headers: Headers;
};
;

export type ProductClientAssignmentController_findAllResponse = (ProductClientAssignmentController_findAllResponseSuccess)

export const getProductClientAssignmentControllerFindAllUrl = () => {




  return `/api/v1/wms/web/product-client-assignments`
}

/**
 * @summary List product-client assignments
 */
export const ProductClientAssignmentController_findAll = async ( options?: RequestInit): Promise<ProductClientAssignmentController_findAllResponse> => {

  return customInstance<ProductClientAssignmentController_findAllResponse>(getProductClientAssignmentControllerFindAllUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getProductClientAssignmentControllerFindAllMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof ProductClientAssignmentController_findAll>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof ProductClientAssignmentController_findAll>>, TError,void, TContext> => {

const mutationKey = ['productClientAssignmentControllerFindAll'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof ProductClientAssignmentController_findAll>>, void> = () => {


          return  ProductClientAssignmentController_findAll(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ProductClientAssignmentControllerFindAllMutationResult = NonNullable<Awaited<ReturnType<typeof ProductClientAssignmentController_findAll>>>

    export type ProductClientAssignmentControllerFindAllMutationError = unknown

    /**
 * @summary List product-client assignments
 */
export const useProductClientAssignmentControllerFindAll = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof ProductClientAssignmentController_findAll>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof ProductClientAssignmentController_findAll>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getProductClientAssignmentControllerFindAllMutationOptions(options));
    }
    export type ProductClientAssignmentController_findByIdResponse200 = {
  data: ProductClientAssignmentResponseDto
  status: 200
}

export type ProductClientAssignmentController_findByIdResponseSuccess = (ProductClientAssignmentController_findByIdResponse200) & {
  headers: Headers;
};
;

export type ProductClientAssignmentController_findByIdResponse = (ProductClientAssignmentController_findByIdResponseSuccess)

export const getProductClientAssignmentControllerFindByIdUrl = (id: string,) => {




  return `/api/v1/wms/web/product-client-assignments/${id}`
}

/**
 * @summary Get product-client assignment
 */
export const ProductClientAssignmentController_findById = async (id: string, options?: RequestInit): Promise<ProductClientAssignmentController_findByIdResponse> => {

  return customInstance<ProductClientAssignmentController_findByIdResponse>(getProductClientAssignmentControllerFindByIdUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getProductClientAssignmentControllerFindByIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof ProductClientAssignmentController_findById>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof ProductClientAssignmentController_findById>>, TError,{id: string}, TContext> => {

const mutationKey = ['productClientAssignmentControllerFindById'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof ProductClientAssignmentController_findById>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  ProductClientAssignmentController_findById(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ProductClientAssignmentControllerFindByIdMutationResult = NonNullable<Awaited<ReturnType<typeof ProductClientAssignmentController_findById>>>

    export type ProductClientAssignmentControllerFindByIdMutationError = unknown

    /**
 * @summary Get product-client assignment
 */
export const useProductClientAssignmentControllerFindById = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof ProductClientAssignmentController_findById>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof ProductClientAssignmentController_findById>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getProductClientAssignmentControllerFindByIdMutationOptions(options));
    }
    export type ProductClientAssignmentController_deleteResponse200 = {
  data: ProductClientAssignmentResponseDto
  status: 200
}

export type ProductClientAssignmentController_deleteResponseSuccess = (ProductClientAssignmentController_deleteResponse200) & {
  headers: Headers;
};
;

export type ProductClientAssignmentController_deleteResponse = (ProductClientAssignmentController_deleteResponseSuccess)

export const getProductClientAssignmentControllerDeleteUrl = (id: string,) => {




  return `/api/v1/wms/web/product-client-assignments/${id}`
}

/**
 * @summary Delete product-client assignment
 */
export const ProductClientAssignmentController_delete = async (id: string, options?: RequestInit): Promise<ProductClientAssignmentController_deleteResponse> => {

  return customInstance<ProductClientAssignmentController_deleteResponse>(getProductClientAssignmentControllerDeleteUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getProductClientAssignmentControllerDeleteQueryKey = (id: string,) => {
    return [
    'DELETE', `/api/v1/wms/web/product-client-assignments/${id}`
    ] as const;
    }


export const getProductClientAssignmentControllerDeleteQueryOptions = <TData = Awaited<ReturnType<typeof ProductClientAssignmentController_delete>>, TError = unknown>(id: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof ProductClientAssignmentController_delete>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getProductClientAssignmentControllerDeleteQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof ProductClientAssignmentController_delete>>> = ({ signal }) => ProductClientAssignmentController_delete(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof ProductClientAssignmentController_delete>>, TError, TData> & { queryKey: QueryKey }
}

export type ProductClientAssignmentControllerDeleteQueryResult = NonNullable<Awaited<ReturnType<typeof ProductClientAssignmentController_delete>>>
export type ProductClientAssignmentControllerDeleteQueryError = unknown


/**
 * @summary Delete product-client assignment
 */

export function useProductClientAssignmentControllerDelete<TData = Awaited<ReturnType<typeof ProductClientAssignmentController_delete>>, TError = unknown>(
 id: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof ProductClientAssignmentController_delete>>, TError, TData>, request?: SecondParameter<typeof customInstance>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getProductClientAssignmentControllerDeleteQueryOptions(id,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}






export type ProductClientAssignmentController_findByProductResponse200 = {
  data: ProductClientAssignmentResponseDto[]
  status: 200
}

export type ProductClientAssignmentController_findByProductResponseSuccess = (ProductClientAssignmentController_findByProductResponse200) & {
  headers: Headers;
};
;

export type ProductClientAssignmentController_findByProductResponse = (ProductClientAssignmentController_findByProductResponseSuccess)

export const getProductClientAssignmentControllerFindByProductUrl = (productId: string,) => {




  return `/api/v1/wms/web/product-client-assignments/by-product/${productId}`
}

/**
 * @summary Find assignments by product
 */
export const ProductClientAssignmentController_findByProduct = async (productId: string, options?: RequestInit): Promise<ProductClientAssignmentController_findByProductResponse> => {

  return customInstance<ProductClientAssignmentController_findByProductResponse>(getProductClientAssignmentControllerFindByProductUrl(productId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getProductClientAssignmentControllerFindByProductMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof ProductClientAssignmentController_findByProduct>>, TError,{productId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof ProductClientAssignmentController_findByProduct>>, TError,{productId: string}, TContext> => {

const mutationKey = ['productClientAssignmentControllerFindByProduct'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof ProductClientAssignmentController_findByProduct>>, {productId: string}> = (props) => {
          const {productId} = props ?? {};

          return  ProductClientAssignmentController_findByProduct(productId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ProductClientAssignmentControllerFindByProductMutationResult = NonNullable<Awaited<ReturnType<typeof ProductClientAssignmentController_findByProduct>>>

    export type ProductClientAssignmentControllerFindByProductMutationError = unknown

    /**
 * @summary Find assignments by product
 */
export const useProductClientAssignmentControllerFindByProduct = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof ProductClientAssignmentController_findByProduct>>, TError,{productId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof ProductClientAssignmentController_findByProduct>>,
        TError,
        {productId: string},
        TContext
      > => {
      return useMutation(getProductClientAssignmentControllerFindByProductMutationOptions(options));
    }
    export type ProductClientAssignmentController_findByClientResponse200 = {
  data: ProductClientAssignmentResponseDto[]
  status: 200
}

export type ProductClientAssignmentController_findByClientResponseSuccess = (ProductClientAssignmentController_findByClientResponse200) & {
  headers: Headers;
};
;

export type ProductClientAssignmentController_findByClientResponse = (ProductClientAssignmentController_findByClientResponseSuccess)

export const getProductClientAssignmentControllerFindByClientUrl = (clientId: string,) => {




  return `/api/v1/wms/web/product-client-assignments/by-client/${clientId}`
}

/**
 * @summary Find assignments by client
 */
export const ProductClientAssignmentController_findByClient = async (clientId: string, options?: RequestInit): Promise<ProductClientAssignmentController_findByClientResponse> => {

  return customInstance<ProductClientAssignmentController_findByClientResponse>(getProductClientAssignmentControllerFindByClientUrl(clientId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getProductClientAssignmentControllerFindByClientMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof ProductClientAssignmentController_findByClient>>, TError,{clientId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof ProductClientAssignmentController_findByClient>>, TError,{clientId: string}, TContext> => {

const mutationKey = ['productClientAssignmentControllerFindByClient'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof ProductClientAssignmentController_findByClient>>, {clientId: string}> = (props) => {
          const {clientId} = props ?? {};

          return  ProductClientAssignmentController_findByClient(clientId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ProductClientAssignmentControllerFindByClientMutationResult = NonNullable<Awaited<ReturnType<typeof ProductClientAssignmentController_findByClient>>>

    export type ProductClientAssignmentControllerFindByClientMutationError = unknown

    /**
 * @summary Find assignments by client
 */
export const useProductClientAssignmentControllerFindByClient = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof ProductClientAssignmentController_findByClient>>, TError,{clientId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof ProductClientAssignmentController_findByClient>>,
        TError,
        {clientId: string},
        TContext
      > => {
      return useMutation(getProductClientAssignmentControllerFindByClientMutationOptions(options));
    }
