/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * WMS API
 * Warehouse Management System API
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  BillingCycleDto,
  BillingCyclesResponseDto,
  ChargesResponseDto,
  ClientInvoiceDto,
  CreateBillingCycleDto,
  CreateClientRateDto,
  CreateStorageRateDto,
  DeleteResultDto,
  GenerateInvoiceDto,
  GenerateSnapshotDto,
  InvoicesResponseDto,
  SnapshotGenerateResultDto,
  SnapshotsResponseDto,
  StorageClientRateDto,
  StorageRateMasterDto,
  UpdateBillingCycleDto,
  UpdateClientRateDto,
  UpdateStorageRateDto
} from '../../../types/wms-api';

import { customInstance } from '../../../http/httpClient.js';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type BillingWebController_createRateResponse201 = {
  data: StorageRateMasterDto
  status: 201
}

export type BillingWebController_createRateResponseSuccess = (BillingWebController_createRateResponse201) & {
  headers: Headers;
};
;

export type BillingWebController_createRateResponse = (BillingWebController_createRateResponseSuccess)

export const getBillingWebControllerCreateRateUrl = () => {




  return `/api/v1/wms/web/billing/storage-rates`
}

/**
 * @summary Create storage rate
 */
export const BillingWebController_createRate = async (createStorageRateDto: CreateStorageRateDto, options?: RequestInit): Promise<BillingWebController_createRateResponse> => {

  return customInstance<BillingWebController_createRateResponse>(getBillingWebControllerCreateRateUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createStorageRateDto)
  }
);}





export const getBillingWebControllerCreateRateQueryKey = (createStorageRateDto?: CreateStorageRateDto,) => {
    return [
    'POST', `/api/v1/wms/web/billing/storage-rates`, createStorageRateDto
    ] as const;
    }


export const getBillingWebControllerCreateRateQueryOptions = <TData = Awaited<ReturnType<typeof BillingWebController_createRate>>, TError = unknown>(createStorageRateDto: CreateStorageRateDto, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof BillingWebController_createRate>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getBillingWebControllerCreateRateQueryKey(createStorageRateDto);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof BillingWebController_createRate>>> = ({ signal }) => BillingWebController_createRate(createStorageRateDto, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof BillingWebController_createRate>>, TError, TData> & { queryKey: QueryKey }
}

export type BillingWebControllerCreateRateQueryResult = NonNullable<Awaited<ReturnType<typeof BillingWebController_createRate>>>
export type BillingWebControllerCreateRateQueryError = unknown


/**
 * @summary Create storage rate
 */

export function useBillingWebControllerCreateRate<TData = Awaited<ReturnType<typeof BillingWebController_createRate>>, TError = unknown>(
 createStorageRateDto: CreateStorageRateDto, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof BillingWebController_createRate>>, TError, TData>, request?: SecondParameter<typeof customInstance>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getBillingWebControllerCreateRateQueryOptions(createStorageRateDto,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}






export type BillingWebController_findAllRatesResponse200 = {
  data: StorageRateMasterDto[]
  status: 200
}

export type BillingWebController_findAllRatesResponseSuccess = (BillingWebController_findAllRatesResponse200) & {
  headers: Headers;
};
;

export type BillingWebController_findAllRatesResponse = (BillingWebController_findAllRatesResponseSuccess)

export const getBillingWebControllerFindAllRatesUrl = () => {




  return `/api/v1/wms/web/billing/storage-rates`
}

/**
 * @summary List storage rates
 */
export const BillingWebController_findAllRates = async ( options?: RequestInit): Promise<BillingWebController_findAllRatesResponse> => {

  return customInstance<BillingWebController_findAllRatesResponse>(getBillingWebControllerFindAllRatesUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getBillingWebControllerFindAllRatesMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof BillingWebController_findAllRates>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof BillingWebController_findAllRates>>, TError,void, TContext> => {

const mutationKey = ['billingWebControllerFindAllRates'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof BillingWebController_findAllRates>>, void> = () => {


          return  BillingWebController_findAllRates(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type BillingWebControllerFindAllRatesMutationResult = NonNullable<Awaited<ReturnType<typeof BillingWebController_findAllRates>>>

    export type BillingWebControllerFindAllRatesMutationError = unknown

    /**
 * @summary List storage rates
 */
export const useBillingWebControllerFindAllRates = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof BillingWebController_findAllRates>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof BillingWebController_findAllRates>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getBillingWebControllerFindAllRatesMutationOptions(options));
    }
    export type BillingWebController_findRateByIdResponse200 = {
  data: StorageRateMasterDto
  status: 200
}

export type BillingWebController_findRateByIdResponseSuccess = (BillingWebController_findRateByIdResponse200) & {
  headers: Headers;
};
;

export type BillingWebController_findRateByIdResponse = (BillingWebController_findRateByIdResponseSuccess)

export const getBillingWebControllerFindRateByIdUrl = (id: string,) => {




  return `/api/v1/wms/web/billing/storage-rates/${id}`
}

/**
 * @summary Get storage rate by ID
 */
export const BillingWebController_findRateById = async (id: string, options?: RequestInit): Promise<BillingWebController_findRateByIdResponse> => {

  return customInstance<BillingWebController_findRateByIdResponse>(getBillingWebControllerFindRateByIdUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getBillingWebControllerFindRateByIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof BillingWebController_findRateById>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof BillingWebController_findRateById>>, TError,{id: string}, TContext> => {

const mutationKey = ['billingWebControllerFindRateById'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof BillingWebController_findRateById>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  BillingWebController_findRateById(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type BillingWebControllerFindRateByIdMutationResult = NonNullable<Awaited<ReturnType<typeof BillingWebController_findRateById>>>

    export type BillingWebControllerFindRateByIdMutationError = unknown

    /**
 * @summary Get storage rate by ID
 */
export const useBillingWebControllerFindRateById = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof BillingWebController_findRateById>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof BillingWebController_findRateById>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getBillingWebControllerFindRateByIdMutationOptions(options));
    }
    export type BillingWebController_updateRateResponse200 = {
  data: StorageRateMasterDto
  status: 200
}

export type BillingWebController_updateRateResponseSuccess = (BillingWebController_updateRateResponse200) & {
  headers: Headers;
};
;

export type BillingWebController_updateRateResponse = (BillingWebController_updateRateResponseSuccess)

export const getBillingWebControllerUpdateRateUrl = (id: string,) => {




  return `/api/v1/wms/web/billing/storage-rates/${id}`
}

/**
 * @summary Update storage rate
 */
export const BillingWebController_updateRate = async (id: string,
    updateStorageRateDto: UpdateStorageRateDto, options?: RequestInit): Promise<BillingWebController_updateRateResponse> => {

  return customInstance<BillingWebController_updateRateResponse>(getBillingWebControllerUpdateRateUrl(id),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateStorageRateDto)
  }
);}





export const getBillingWebControllerUpdateRateQueryKey = (id: string,
    updateStorageRateDto?: UpdateStorageRateDto,) => {
    return [
    'PATCH', `/api/v1/wms/web/billing/storage-rates/${id}`, updateStorageRateDto
    ] as const;
    }


export const getBillingWebControllerUpdateRateQueryOptions = <TData = Awaited<ReturnType<typeof BillingWebController_updateRate>>, TError = unknown>(id: string,
    updateStorageRateDto: UpdateStorageRateDto, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof BillingWebController_updateRate>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getBillingWebControllerUpdateRateQueryKey(id,updateStorageRateDto);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof BillingWebController_updateRate>>> = ({ signal }) => BillingWebController_updateRate(id,updateStorageRateDto, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof BillingWebController_updateRate>>, TError, TData> & { queryKey: QueryKey }
}

export type BillingWebControllerUpdateRateQueryResult = NonNullable<Awaited<ReturnType<typeof BillingWebController_updateRate>>>
export type BillingWebControllerUpdateRateQueryError = unknown


/**
 * @summary Update storage rate
 */

export function useBillingWebControllerUpdateRate<TData = Awaited<ReturnType<typeof BillingWebController_updateRate>>, TError = unknown>(
 id: string,
    updateStorageRateDto: UpdateStorageRateDto, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof BillingWebController_updateRate>>, TError, TData>, request?: SecondParameter<typeof customInstance>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getBillingWebControllerUpdateRateQueryOptions(id,updateStorageRateDto,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}






export type BillingWebController_deleteRateResponse200 = {
  data: DeleteResultDto
  status: 200
}

export type BillingWebController_deleteRateResponseSuccess = (BillingWebController_deleteRateResponse200) & {
  headers: Headers;
};
;

export type BillingWebController_deleteRateResponse = (BillingWebController_deleteRateResponseSuccess)

export const getBillingWebControllerDeleteRateUrl = (id: string,) => {




  return `/api/v1/wms/web/billing/storage-rates/${id}`
}

/**
 * @summary Delete storage rate
 */
export const BillingWebController_deleteRate = async (id: string, options?: RequestInit): Promise<BillingWebController_deleteRateResponse> => {

  return customInstance<BillingWebController_deleteRateResponse>(getBillingWebControllerDeleteRateUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getBillingWebControllerDeleteRateQueryKey = (id: string,) => {
    return [
    'DELETE', `/api/v1/wms/web/billing/storage-rates/${id}`
    ] as const;
    }


export const getBillingWebControllerDeleteRateQueryOptions = <TData = Awaited<ReturnType<typeof BillingWebController_deleteRate>>, TError = unknown>(id: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof BillingWebController_deleteRate>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getBillingWebControllerDeleteRateQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof BillingWebController_deleteRate>>> = ({ signal }) => BillingWebController_deleteRate(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof BillingWebController_deleteRate>>, TError, TData> & { queryKey: QueryKey }
}

export type BillingWebControllerDeleteRateQueryResult = NonNullable<Awaited<ReturnType<typeof BillingWebController_deleteRate>>>
export type BillingWebControllerDeleteRateQueryError = unknown


/**
 * @summary Delete storage rate
 */

export function useBillingWebControllerDeleteRate<TData = Awaited<ReturnType<typeof BillingWebController_deleteRate>>, TError = unknown>(
 id: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof BillingWebController_deleteRate>>, TError, TData>, request?: SecondParameter<typeof customInstance>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getBillingWebControllerDeleteRateQueryOptions(id,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}






export type BillingWebController_createClientRateResponse201 = {
  data: StorageClientRateDto
  status: 201
}

export type BillingWebController_createClientRateResponseSuccess = (BillingWebController_createClientRateResponse201) & {
  headers: Headers;
};
;

export type BillingWebController_createClientRateResponse = (BillingWebController_createClientRateResponseSuccess)

export const getBillingWebControllerCreateClientRateUrl = () => {




  return `/api/v1/wms/web/billing/client-rates`
}

/**
 * @summary Create client rate
 */
export const BillingWebController_createClientRate = async (createClientRateDto: CreateClientRateDto, options?: RequestInit): Promise<BillingWebController_createClientRateResponse> => {

  return customInstance<BillingWebController_createClientRateResponse>(getBillingWebControllerCreateClientRateUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createClientRateDto)
  }
);}





export const getBillingWebControllerCreateClientRateQueryKey = (createClientRateDto?: CreateClientRateDto,) => {
    return [
    'POST', `/api/v1/wms/web/billing/client-rates`, createClientRateDto
    ] as const;
    }


export const getBillingWebControllerCreateClientRateQueryOptions = <TData = Awaited<ReturnType<typeof BillingWebController_createClientRate>>, TError = unknown>(createClientRateDto: CreateClientRateDto, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof BillingWebController_createClientRate>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getBillingWebControllerCreateClientRateQueryKey(createClientRateDto);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof BillingWebController_createClientRate>>> = ({ signal }) => BillingWebController_createClientRate(createClientRateDto, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof BillingWebController_createClientRate>>, TError, TData> & { queryKey: QueryKey }
}

export type BillingWebControllerCreateClientRateQueryResult = NonNullable<Awaited<ReturnType<typeof BillingWebController_createClientRate>>>
export type BillingWebControllerCreateClientRateQueryError = unknown


/**
 * @summary Create client rate
 */

export function useBillingWebControllerCreateClientRate<TData = Awaited<ReturnType<typeof BillingWebController_createClientRate>>, TError = unknown>(
 createClientRateDto: CreateClientRateDto, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof BillingWebController_createClientRate>>, TError, TData>, request?: SecondParameter<typeof customInstance>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getBillingWebControllerCreateClientRateQueryOptions(createClientRateDto,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}






export type BillingWebController_findAllClientRatesResponse200 = {
  data: StorageClientRateDto[]
  status: 200
}

export type BillingWebController_findAllClientRatesResponseSuccess = (BillingWebController_findAllClientRatesResponse200) & {
  headers: Headers;
};
;

export type BillingWebController_findAllClientRatesResponse = (BillingWebController_findAllClientRatesResponseSuccess)

export const getBillingWebControllerFindAllClientRatesUrl = () => {




  return `/api/v1/wms/web/billing/client-rates`
}

/**
 * @summary List client rates
 */
export const BillingWebController_findAllClientRates = async ( options?: RequestInit): Promise<BillingWebController_findAllClientRatesResponse> => {

  return customInstance<BillingWebController_findAllClientRatesResponse>(getBillingWebControllerFindAllClientRatesUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getBillingWebControllerFindAllClientRatesMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof BillingWebController_findAllClientRates>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof BillingWebController_findAllClientRates>>, TError,void, TContext> => {

const mutationKey = ['billingWebControllerFindAllClientRates'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof BillingWebController_findAllClientRates>>, void> = () => {


          return  BillingWebController_findAllClientRates(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type BillingWebControllerFindAllClientRatesMutationResult = NonNullable<Awaited<ReturnType<typeof BillingWebController_findAllClientRates>>>

    export type BillingWebControllerFindAllClientRatesMutationError = unknown

    /**
 * @summary List client rates
 */
export const useBillingWebControllerFindAllClientRates = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof BillingWebController_findAllClientRates>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof BillingWebController_findAllClientRates>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getBillingWebControllerFindAllClientRatesMutationOptions(options));
    }
    export type BillingWebController_findClientRateByIdResponse200 = {
  data: StorageClientRateDto
  status: 200
}

export type BillingWebController_findClientRateByIdResponseSuccess = (BillingWebController_findClientRateByIdResponse200) & {
  headers: Headers;
};
;

export type BillingWebController_findClientRateByIdResponse = (BillingWebController_findClientRateByIdResponseSuccess)

export const getBillingWebControllerFindClientRateByIdUrl = (id: string,) => {




  return `/api/v1/wms/web/billing/client-rates/${id}`
}

/**
 * @summary Get client rate by ID
 */
export const BillingWebController_findClientRateById = async (id: string, options?: RequestInit): Promise<BillingWebController_findClientRateByIdResponse> => {

  return customInstance<BillingWebController_findClientRateByIdResponse>(getBillingWebControllerFindClientRateByIdUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getBillingWebControllerFindClientRateByIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof BillingWebController_findClientRateById>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof BillingWebController_findClientRateById>>, TError,{id: string}, TContext> => {

const mutationKey = ['billingWebControllerFindClientRateById'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof BillingWebController_findClientRateById>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  BillingWebController_findClientRateById(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type BillingWebControllerFindClientRateByIdMutationResult = NonNullable<Awaited<ReturnType<typeof BillingWebController_findClientRateById>>>

    export type BillingWebControllerFindClientRateByIdMutationError = unknown

    /**
 * @summary Get client rate by ID
 */
export const useBillingWebControllerFindClientRateById = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof BillingWebController_findClientRateById>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof BillingWebController_findClientRateById>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getBillingWebControllerFindClientRateByIdMutationOptions(options));
    }
    export type BillingWebController_updateClientRateResponse200 = {
  data: StorageClientRateDto
  status: 200
}

export type BillingWebController_updateClientRateResponseSuccess = (BillingWebController_updateClientRateResponse200) & {
  headers: Headers;
};
;

export type BillingWebController_updateClientRateResponse = (BillingWebController_updateClientRateResponseSuccess)

export const getBillingWebControllerUpdateClientRateUrl = (id: string,) => {




  return `/api/v1/wms/web/billing/client-rates/${id}`
}

/**
 * @summary Update client rate
 */
export const BillingWebController_updateClientRate = async (id: string,
    updateClientRateDto: UpdateClientRateDto, options?: RequestInit): Promise<BillingWebController_updateClientRateResponse> => {

  return customInstance<BillingWebController_updateClientRateResponse>(getBillingWebControllerUpdateClientRateUrl(id),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateClientRateDto)
  }
);}





export const getBillingWebControllerUpdateClientRateQueryKey = (id: string,
    updateClientRateDto?: UpdateClientRateDto,) => {
    return [
    'PATCH', `/api/v1/wms/web/billing/client-rates/${id}`, updateClientRateDto
    ] as const;
    }


export const getBillingWebControllerUpdateClientRateQueryOptions = <TData = Awaited<ReturnType<typeof BillingWebController_updateClientRate>>, TError = unknown>(id: string,
    updateClientRateDto: UpdateClientRateDto, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof BillingWebController_updateClientRate>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getBillingWebControllerUpdateClientRateQueryKey(id,updateClientRateDto);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof BillingWebController_updateClientRate>>> = ({ signal }) => BillingWebController_updateClientRate(id,updateClientRateDto, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof BillingWebController_updateClientRate>>, TError, TData> & { queryKey: QueryKey }
}

export type BillingWebControllerUpdateClientRateQueryResult = NonNullable<Awaited<ReturnType<typeof BillingWebController_updateClientRate>>>
export type BillingWebControllerUpdateClientRateQueryError = unknown


/**
 * @summary Update client rate
 */

export function useBillingWebControllerUpdateClientRate<TData = Awaited<ReturnType<typeof BillingWebController_updateClientRate>>, TError = unknown>(
 id: string,
    updateClientRateDto: UpdateClientRateDto, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof BillingWebController_updateClientRate>>, TError, TData>, request?: SecondParameter<typeof customInstance>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getBillingWebControllerUpdateClientRateQueryOptions(id,updateClientRateDto,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}






export type BillingWebController_deleteClientRateResponse200 = {
  data: DeleteResultDto
  status: 200
}

export type BillingWebController_deleteClientRateResponseSuccess = (BillingWebController_deleteClientRateResponse200) & {
  headers: Headers;
};
;

export type BillingWebController_deleteClientRateResponse = (BillingWebController_deleteClientRateResponseSuccess)

export const getBillingWebControllerDeleteClientRateUrl = (id: string,) => {




  return `/api/v1/wms/web/billing/client-rates/${id}`
}

/**
 * @summary Delete client rate
 */
export const BillingWebController_deleteClientRate = async (id: string, options?: RequestInit): Promise<BillingWebController_deleteClientRateResponse> => {

  return customInstance<BillingWebController_deleteClientRateResponse>(getBillingWebControllerDeleteClientRateUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getBillingWebControllerDeleteClientRateQueryKey = (id: string,) => {
    return [
    'DELETE', `/api/v1/wms/web/billing/client-rates/${id}`
    ] as const;
    }


export const getBillingWebControllerDeleteClientRateQueryOptions = <TData = Awaited<ReturnType<typeof BillingWebController_deleteClientRate>>, TError = unknown>(id: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof BillingWebController_deleteClientRate>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getBillingWebControllerDeleteClientRateQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof BillingWebController_deleteClientRate>>> = ({ signal }) => BillingWebController_deleteClientRate(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof BillingWebController_deleteClientRate>>, TError, TData> & { queryKey: QueryKey }
}

export type BillingWebControllerDeleteClientRateQueryResult = NonNullable<Awaited<ReturnType<typeof BillingWebController_deleteClientRate>>>
export type BillingWebControllerDeleteClientRateQueryError = unknown


/**
 * @summary Delete client rate
 */

export function useBillingWebControllerDeleteClientRate<TData = Awaited<ReturnType<typeof BillingWebController_deleteClientRate>>, TError = unknown>(
 id: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof BillingWebController_deleteClientRate>>, TError, TData>, request?: SecondParameter<typeof customInstance>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getBillingWebControllerDeleteClientRateQueryOptions(id,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}






export type BillingWebController_createCycleResponse201 = {
  data: BillingCycleDto
  status: 201
}

export type BillingWebController_createCycleResponseSuccess = (BillingWebController_createCycleResponse201) & {
  headers: Headers;
};
;

export type BillingWebController_createCycleResponse = (BillingWebController_createCycleResponseSuccess)

export const getBillingWebControllerCreateCycleUrl = () => {




  return `/api/v1/wms/web/billing/cycles`
}

/**
 * @summary Create billing cycle
 */
export const BillingWebController_createCycle = async (createBillingCycleDto: CreateBillingCycleDto, options?: RequestInit): Promise<BillingWebController_createCycleResponse> => {

  return customInstance<BillingWebController_createCycleResponse>(getBillingWebControllerCreateCycleUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createBillingCycleDto)
  }
);}





export const getBillingWebControllerCreateCycleQueryKey = (createBillingCycleDto?: CreateBillingCycleDto,) => {
    return [
    'POST', `/api/v1/wms/web/billing/cycles`, createBillingCycleDto
    ] as const;
    }


export const getBillingWebControllerCreateCycleQueryOptions = <TData = Awaited<ReturnType<typeof BillingWebController_createCycle>>, TError = unknown>(createBillingCycleDto: CreateBillingCycleDto, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof BillingWebController_createCycle>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getBillingWebControllerCreateCycleQueryKey(createBillingCycleDto);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof BillingWebController_createCycle>>> = ({ signal }) => BillingWebController_createCycle(createBillingCycleDto, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof BillingWebController_createCycle>>, TError, TData> & { queryKey: QueryKey }
}

export type BillingWebControllerCreateCycleQueryResult = NonNullable<Awaited<ReturnType<typeof BillingWebController_createCycle>>>
export type BillingWebControllerCreateCycleQueryError = unknown


/**
 * @summary Create billing cycle
 */

export function useBillingWebControllerCreateCycle<TData = Awaited<ReturnType<typeof BillingWebController_createCycle>>, TError = unknown>(
 createBillingCycleDto: CreateBillingCycleDto, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof BillingWebController_createCycle>>, TError, TData>, request?: SecondParameter<typeof customInstance>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getBillingWebControllerCreateCycleQueryOptions(createBillingCycleDto,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}






export type BillingWebController_findAllCyclesResponse200 = {
  data: BillingCyclesResponseDto
  status: 200
}

export type BillingWebController_findAllCyclesResponseSuccess = (BillingWebController_findAllCyclesResponse200) & {
  headers: Headers;
};
;

export type BillingWebController_findAllCyclesResponse = (BillingWebController_findAllCyclesResponseSuccess)

export const getBillingWebControllerFindAllCyclesUrl = () => {




  return `/api/v1/wms/web/billing/cycles`
}

/**
 * @summary List billing cycles
 */
export const BillingWebController_findAllCycles = async ( options?: RequestInit): Promise<BillingWebController_findAllCyclesResponse> => {

  return customInstance<BillingWebController_findAllCyclesResponse>(getBillingWebControllerFindAllCyclesUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getBillingWebControllerFindAllCyclesMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof BillingWebController_findAllCycles>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof BillingWebController_findAllCycles>>, TError,void, TContext> => {

const mutationKey = ['billingWebControllerFindAllCycles'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof BillingWebController_findAllCycles>>, void> = () => {


          return  BillingWebController_findAllCycles(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type BillingWebControllerFindAllCyclesMutationResult = NonNullable<Awaited<ReturnType<typeof BillingWebController_findAllCycles>>>

    export type BillingWebControllerFindAllCyclesMutationError = unknown

    /**
 * @summary List billing cycles
 */
export const useBillingWebControllerFindAllCycles = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof BillingWebController_findAllCycles>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof BillingWebController_findAllCycles>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getBillingWebControllerFindAllCyclesMutationOptions(options));
    }
    export type BillingWebController_updateCycleResponse200 = {
  data: BillingCycleDto
  status: 200
}

export type BillingWebController_updateCycleResponseSuccess = (BillingWebController_updateCycleResponse200) & {
  headers: Headers;
};
;

export type BillingWebController_updateCycleResponse = (BillingWebController_updateCycleResponseSuccess)

export const getBillingWebControllerUpdateCycleUrl = (id: string,) => {




  return `/api/v1/wms/web/billing/cycles/${id}`
}

/**
 * @summary Update billing cycle
 */
export const BillingWebController_updateCycle = async (id: string,
    updateBillingCycleDto: UpdateBillingCycleDto, options?: RequestInit): Promise<BillingWebController_updateCycleResponse> => {

  return customInstance<BillingWebController_updateCycleResponse>(getBillingWebControllerUpdateCycleUrl(id),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateBillingCycleDto)
  }
);}





export const getBillingWebControllerUpdateCycleQueryKey = (id: string,
    updateBillingCycleDto?: UpdateBillingCycleDto,) => {
    return [
    'PATCH', `/api/v1/wms/web/billing/cycles/${id}`, updateBillingCycleDto
    ] as const;
    }


export const getBillingWebControllerUpdateCycleQueryOptions = <TData = Awaited<ReturnType<typeof BillingWebController_updateCycle>>, TError = unknown>(id: string,
    updateBillingCycleDto: UpdateBillingCycleDto, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof BillingWebController_updateCycle>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getBillingWebControllerUpdateCycleQueryKey(id,updateBillingCycleDto);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof BillingWebController_updateCycle>>> = ({ signal }) => BillingWebController_updateCycle(id,updateBillingCycleDto, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof BillingWebController_updateCycle>>, TError, TData> & { queryKey: QueryKey }
}

export type BillingWebControllerUpdateCycleQueryResult = NonNullable<Awaited<ReturnType<typeof BillingWebController_updateCycle>>>
export type BillingWebControllerUpdateCycleQueryError = unknown


/**
 * @summary Update billing cycle
 */

export function useBillingWebControllerUpdateCycle<TData = Awaited<ReturnType<typeof BillingWebController_updateCycle>>, TError = unknown>(
 id: string,
    updateBillingCycleDto: UpdateBillingCycleDto, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof BillingWebController_updateCycle>>, TError, TData>, request?: SecondParameter<typeof customInstance>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getBillingWebControllerUpdateCycleQueryOptions(id,updateBillingCycleDto,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}






export type BillingWebController_deleteCycleResponse200 = {
  data: DeleteResultDto
  status: 200
}

export type BillingWebController_deleteCycleResponseSuccess = (BillingWebController_deleteCycleResponse200) & {
  headers: Headers;
};
;

export type BillingWebController_deleteCycleResponse = (BillingWebController_deleteCycleResponseSuccess)

export const getBillingWebControllerDeleteCycleUrl = (id: string,) => {




  return `/api/v1/wms/web/billing/cycles/${id}`
}

/**
 * @summary Delete billing cycle
 */
export const BillingWebController_deleteCycle = async (id: string, options?: RequestInit): Promise<BillingWebController_deleteCycleResponse> => {

  return customInstance<BillingWebController_deleteCycleResponse>(getBillingWebControllerDeleteCycleUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getBillingWebControllerDeleteCycleQueryKey = (id: string,) => {
    return [
    'DELETE', `/api/v1/wms/web/billing/cycles/${id}`
    ] as const;
    }


export const getBillingWebControllerDeleteCycleQueryOptions = <TData = Awaited<ReturnType<typeof BillingWebController_deleteCycle>>, TError = unknown>(id: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof BillingWebController_deleteCycle>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getBillingWebControllerDeleteCycleQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof BillingWebController_deleteCycle>>> = ({ signal }) => BillingWebController_deleteCycle(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof BillingWebController_deleteCycle>>, TError, TData> & { queryKey: QueryKey }
}

export type BillingWebControllerDeleteCycleQueryResult = NonNullable<Awaited<ReturnType<typeof BillingWebController_deleteCycle>>>
export type BillingWebControllerDeleteCycleQueryError = unknown


/**
 * @summary Delete billing cycle
 */

export function useBillingWebControllerDeleteCycle<TData = Awaited<ReturnType<typeof BillingWebController_deleteCycle>>, TError = unknown>(
 id: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof BillingWebController_deleteCycle>>, TError, TData>, request?: SecondParameter<typeof customInstance>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getBillingWebControllerDeleteCycleQueryOptions(id,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}






export type BillingWebController_findSnapshotsResponse200 = {
  data: SnapshotsResponseDto
  status: 200
}

export type BillingWebController_findSnapshotsResponseSuccess = (BillingWebController_findSnapshotsResponse200) & {
  headers: Headers;
};
;

export type BillingWebController_findSnapshotsResponse = (BillingWebController_findSnapshotsResponseSuccess)

export const getBillingWebControllerFindSnapshotsUrl = () => {




  return `/api/v1/wms/web/billing/snapshots`
}

/**
 * @summary List storage inventory snapshots
 */
export const BillingWebController_findSnapshots = async ( options?: RequestInit): Promise<BillingWebController_findSnapshotsResponse> => {

  return customInstance<BillingWebController_findSnapshotsResponse>(getBillingWebControllerFindSnapshotsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getBillingWebControllerFindSnapshotsMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof BillingWebController_findSnapshots>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof BillingWebController_findSnapshots>>, TError,void, TContext> => {

const mutationKey = ['billingWebControllerFindSnapshots'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof BillingWebController_findSnapshots>>, void> = () => {


          return  BillingWebController_findSnapshots(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type BillingWebControllerFindSnapshotsMutationResult = NonNullable<Awaited<ReturnType<typeof BillingWebController_findSnapshots>>>

    export type BillingWebControllerFindSnapshotsMutationError = unknown

    /**
 * @summary List storage inventory snapshots
 */
export const useBillingWebControllerFindSnapshots = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof BillingWebController_findSnapshots>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof BillingWebController_findSnapshots>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getBillingWebControllerFindSnapshotsMutationOptions(options));
    }
    export type BillingWebController_generateSnapshotsResponse201 = {
  data: SnapshotGenerateResultDto
  status: 201
}

export type BillingWebController_generateSnapshotsResponseSuccess = (BillingWebController_generateSnapshotsResponse201) & {
  headers: Headers;
};
;

export type BillingWebController_generateSnapshotsResponse = (BillingWebController_generateSnapshotsResponseSuccess)

export const getBillingWebControllerGenerateSnapshotsUrl = () => {




  return `/api/v1/wms/web/billing/snapshots/generate`
}

/**
 * @summary Generate inventory snapshots on demand
 */
export const BillingWebController_generateSnapshots = async (generateSnapshotDto: GenerateSnapshotDto, options?: RequestInit): Promise<BillingWebController_generateSnapshotsResponse> => {

  return customInstance<BillingWebController_generateSnapshotsResponse>(getBillingWebControllerGenerateSnapshotsUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(generateSnapshotDto)
  }
);}





export const getBillingWebControllerGenerateSnapshotsQueryKey = (generateSnapshotDto?: GenerateSnapshotDto,) => {
    return [
    'POST', `/api/v1/wms/web/billing/snapshots/generate`, generateSnapshotDto
    ] as const;
    }


export const getBillingWebControllerGenerateSnapshotsQueryOptions = <TData = Awaited<ReturnType<typeof BillingWebController_generateSnapshots>>, TError = unknown>(generateSnapshotDto: GenerateSnapshotDto, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof BillingWebController_generateSnapshots>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getBillingWebControllerGenerateSnapshotsQueryKey(generateSnapshotDto);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof BillingWebController_generateSnapshots>>> = ({ signal }) => BillingWebController_generateSnapshots(generateSnapshotDto, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof BillingWebController_generateSnapshots>>, TError, TData> & { queryKey: QueryKey }
}

export type BillingWebControllerGenerateSnapshotsQueryResult = NonNullable<Awaited<ReturnType<typeof BillingWebController_generateSnapshots>>>
export type BillingWebControllerGenerateSnapshotsQueryError = unknown


/**
 * @summary Generate inventory snapshots on demand
 */

export function useBillingWebControllerGenerateSnapshots<TData = Awaited<ReturnType<typeof BillingWebController_generateSnapshots>>, TError = unknown>(
 generateSnapshotDto: GenerateSnapshotDto, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof BillingWebController_generateSnapshots>>, TError, TData>, request?: SecondParameter<typeof customInstance>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getBillingWebControllerGenerateSnapshotsQueryOptions(generateSnapshotDto,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}






export type BillingWebController_findChargesResponse200 = {
  data: ChargesResponseDto
  status: 200
}

export type BillingWebController_findChargesResponseSuccess = (BillingWebController_findChargesResponse200) & {
  headers: Headers;
};
;

export type BillingWebController_findChargesResponse = (BillingWebController_findChargesResponseSuccess)

export const getBillingWebControllerFindChargesUrl = () => {




  return `/api/v1/wms/web/billing/charges`
}

/**
 * @summary List storage charges
 */
export const BillingWebController_findCharges = async ( options?: RequestInit): Promise<BillingWebController_findChargesResponse> => {

  return customInstance<BillingWebController_findChargesResponse>(getBillingWebControllerFindChargesUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getBillingWebControllerFindChargesMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof BillingWebController_findCharges>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof BillingWebController_findCharges>>, TError,void, TContext> => {

const mutationKey = ['billingWebControllerFindCharges'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof BillingWebController_findCharges>>, void> = () => {


          return  BillingWebController_findCharges(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type BillingWebControllerFindChargesMutationResult = NonNullable<Awaited<ReturnType<typeof BillingWebController_findCharges>>>

    export type BillingWebControllerFindChargesMutationError = unknown

    /**
 * @summary List storage charges
 */
export const useBillingWebControllerFindCharges = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof BillingWebController_findCharges>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof BillingWebController_findCharges>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getBillingWebControllerFindChargesMutationOptions(options));
    }
    export type BillingWebController_findAllInvoicesResponse200 = {
  data: InvoicesResponseDto
  status: 200
}

export type BillingWebController_findAllInvoicesResponseSuccess = (BillingWebController_findAllInvoicesResponse200) & {
  headers: Headers;
};
;

export type BillingWebController_findAllInvoicesResponse = (BillingWebController_findAllInvoicesResponseSuccess)

export const getBillingWebControllerFindAllInvoicesUrl = () => {




  return `/api/v1/wms/web/billing/invoices`
}

/**
 * @summary List invoices
 */
export const BillingWebController_findAllInvoices = async ( options?: RequestInit): Promise<BillingWebController_findAllInvoicesResponse> => {

  return customInstance<BillingWebController_findAllInvoicesResponse>(getBillingWebControllerFindAllInvoicesUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getBillingWebControllerFindAllInvoicesMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof BillingWebController_findAllInvoices>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof BillingWebController_findAllInvoices>>, TError,void, TContext> => {

const mutationKey = ['billingWebControllerFindAllInvoices'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof BillingWebController_findAllInvoices>>, void> = () => {


          return  BillingWebController_findAllInvoices(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type BillingWebControllerFindAllInvoicesMutationResult = NonNullable<Awaited<ReturnType<typeof BillingWebController_findAllInvoices>>>

    export type BillingWebControllerFindAllInvoicesMutationError = unknown

    /**
 * @summary List invoices
 */
export const useBillingWebControllerFindAllInvoices = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof BillingWebController_findAllInvoices>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof BillingWebController_findAllInvoices>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getBillingWebControllerFindAllInvoicesMutationOptions(options));
    }
    export type BillingWebController_findInvoiceByIdResponse200 = {
  data: ClientInvoiceDto
  status: 200
}

export type BillingWebController_findInvoiceByIdResponseSuccess = (BillingWebController_findInvoiceByIdResponse200) & {
  headers: Headers;
};
;

export type BillingWebController_findInvoiceByIdResponse = (BillingWebController_findInvoiceByIdResponseSuccess)

export const getBillingWebControllerFindInvoiceByIdUrl = (id: string,) => {




  return `/api/v1/wms/web/billing/invoices/${id}`
}

/**
 * @summary Get invoice by ID
 */
export const BillingWebController_findInvoiceById = async (id: string, options?: RequestInit): Promise<BillingWebController_findInvoiceByIdResponse> => {

  return customInstance<BillingWebController_findInvoiceByIdResponse>(getBillingWebControllerFindInvoiceByIdUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getBillingWebControllerFindInvoiceByIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof BillingWebController_findInvoiceById>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof BillingWebController_findInvoiceById>>, TError,{id: string}, TContext> => {

const mutationKey = ['billingWebControllerFindInvoiceById'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof BillingWebController_findInvoiceById>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  BillingWebController_findInvoiceById(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type BillingWebControllerFindInvoiceByIdMutationResult = NonNullable<Awaited<ReturnType<typeof BillingWebController_findInvoiceById>>>

    export type BillingWebControllerFindInvoiceByIdMutationError = unknown

    /**
 * @summary Get invoice by ID
 */
export const useBillingWebControllerFindInvoiceById = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof BillingWebController_findInvoiceById>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof BillingWebController_findInvoiceById>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getBillingWebControllerFindInvoiceByIdMutationOptions(options));
    }
    export type BillingWebController_deleteInvoiceResponse200 = {
  data: DeleteResultDto
  status: 200
}

export type BillingWebController_deleteInvoiceResponseSuccess = (BillingWebController_deleteInvoiceResponse200) & {
  headers: Headers;
};
;

export type BillingWebController_deleteInvoiceResponse = (BillingWebController_deleteInvoiceResponseSuccess)

export const getBillingWebControllerDeleteInvoiceUrl = (id: string,) => {




  return `/api/v1/wms/web/billing/invoices/${id}`
}

/**
 * @summary Delete invoice
 */
export const BillingWebController_deleteInvoice = async (id: string, options?: RequestInit): Promise<BillingWebController_deleteInvoiceResponse> => {

  return customInstance<BillingWebController_deleteInvoiceResponse>(getBillingWebControllerDeleteInvoiceUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getBillingWebControllerDeleteInvoiceQueryKey = (id: string,) => {
    return [
    'DELETE', `/api/v1/wms/web/billing/invoices/${id}`
    ] as const;
    }


export const getBillingWebControllerDeleteInvoiceQueryOptions = <TData = Awaited<ReturnType<typeof BillingWebController_deleteInvoice>>, TError = unknown>(id: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof BillingWebController_deleteInvoice>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getBillingWebControllerDeleteInvoiceQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof BillingWebController_deleteInvoice>>> = ({ signal }) => BillingWebController_deleteInvoice(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof BillingWebController_deleteInvoice>>, TError, TData> & { queryKey: QueryKey }
}

export type BillingWebControllerDeleteInvoiceQueryResult = NonNullable<Awaited<ReturnType<typeof BillingWebController_deleteInvoice>>>
export type BillingWebControllerDeleteInvoiceQueryError = unknown


/**
 * @summary Delete invoice
 */

export function useBillingWebControllerDeleteInvoice<TData = Awaited<ReturnType<typeof BillingWebController_deleteInvoice>>, TError = unknown>(
 id: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof BillingWebController_deleteInvoice>>, TError, TData>, request?: SecondParameter<typeof customInstance>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getBillingWebControllerDeleteInvoiceQueryOptions(id,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}






export type BillingWebController_generateInvoiceResponse201 = {
  data: ClientInvoiceDto
  status: 201
}

export type BillingWebController_generateInvoiceResponseSuccess = (BillingWebController_generateInvoiceResponse201) & {
  headers: Headers;
};
;

export type BillingWebController_generateInvoiceResponse = (BillingWebController_generateInvoiceResponseSuccess)

export const getBillingWebControllerGenerateInvoiceUrl = (id: string,) => {




  return `/api/v1/wms/web/billing/invoices/${id}/generate`
}

/**
 * @summary Generate invoice from billing cycle
 */
export const BillingWebController_generateInvoice = async (id: string,
    generateInvoiceDto: GenerateInvoiceDto, options?: RequestInit): Promise<BillingWebController_generateInvoiceResponse> => {

  return customInstance<BillingWebController_generateInvoiceResponse>(getBillingWebControllerGenerateInvoiceUrl(id),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(generateInvoiceDto)
  }
);}





export const getBillingWebControllerGenerateInvoiceQueryKey = (id: string,
    generateInvoiceDto?: GenerateInvoiceDto,) => {
    return [
    'POST', `/api/v1/wms/web/billing/invoices/${id}/generate`, generateInvoiceDto
    ] as const;
    }


export const getBillingWebControllerGenerateInvoiceQueryOptions = <TData = Awaited<ReturnType<typeof BillingWebController_generateInvoice>>, TError = unknown>(id: string,
    generateInvoiceDto: GenerateInvoiceDto, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof BillingWebController_generateInvoice>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getBillingWebControllerGenerateInvoiceQueryKey(id,generateInvoiceDto);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof BillingWebController_generateInvoice>>> = ({ signal }) => BillingWebController_generateInvoice(id,generateInvoiceDto, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof BillingWebController_generateInvoice>>, TError, TData> & { queryKey: QueryKey }
}

export type BillingWebControllerGenerateInvoiceQueryResult = NonNullable<Awaited<ReturnType<typeof BillingWebController_generateInvoice>>>
export type BillingWebControllerGenerateInvoiceQueryError = unknown


/**
 * @summary Generate invoice from billing cycle
 */

export function useBillingWebControllerGenerateInvoice<TData = Awaited<ReturnType<typeof BillingWebController_generateInvoice>>, TError = unknown>(
 id: string,
    generateInvoiceDto: GenerateInvoiceDto, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof BillingWebController_generateInvoice>>, TError, TData>, request?: SecondParameter<typeof customInstance>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getBillingWebControllerGenerateInvoiceQueryOptions(id,generateInvoiceDto,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}






