/**
 * Generated by orval v8.12.1 🍺
 * Do not edit manually.
 * WMS SaaS Core API
 *
 * Domain-agnostic multi-tenant SaaS platform API.
 * Provides: tenancy, auth, RBAC/ABAC, billing, notifications, webhooks, audit, quota management.
 *
 * Authentication:
 *   - **JWT Bearer**: Login via `POST /api/v1/auth/login`
 *   - **API Key**: Header `Authorization: ApiKey wms_{key}`
 *
 * Tenant Resolution:
 *   - Header `X-Tenant-Code: {tenantCode}`
 *   - OR subdomain: `{tenantCode}.yourdomain.com`
 *
 * All endpoints (except @Public) require:
 *   1. Authentication header
 *   2. X-Tenant-Code header (or subdomain)
 *
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateWebhookEndpointDto,
  UpdateWebhookEndpointDto,
  WebhookControllerListDeliveriesParams,
  WebhookControllerListEventsParams
} from '../../../types/wms-saas-core-api';

import { customInstance } from '../../../http/httpClient';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export type WebhookController_createEndpointResponse201 = {
  data: void
  status: 201
}

export type WebhookController_createEndpointResponseSuccess = (WebhookController_createEndpointResponse201) & {
  headers: Headers;
};
;

export type WebhookController_createEndpointResponse = (WebhookController_createEndpointResponseSuccess)

export const getWebhookControllerCreateEndpointUrl = () => {




  return `/api/v1/webhooks/endpoints`
}

/**
 * @summary Create a webhook endpoint
 */
export const WebhookController_createEndpoint = async (createWebhookEndpointDto: CreateWebhookEndpointDto, options?: RequestInit): Promise<WebhookController_createEndpointResponse> => {

  return customInstance<WebhookController_createEndpointResponse>(getWebhookControllerCreateEndpointUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createWebhookEndpointDto)
  }
);}





export const getWebhookControllerCreateEndpointQueryKey = (createWebhookEndpointDto?: CreateWebhookEndpointDto,) => {
    return [
    'POST', `/api/v1/webhooks/endpoints`, createWebhookEndpointDto
    ] as const;
    }


export const getWebhookControllerCreateEndpointQueryOptions = <TData = Awaited<ReturnType<typeof WebhookController_createEndpoint>>, TError = unknown>(createWebhookEndpointDto: CreateWebhookEndpointDto, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof WebhookController_createEndpoint>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getWebhookControllerCreateEndpointQueryKey(createWebhookEndpointDto);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof WebhookController_createEndpoint>>> = ({ signal }) => WebhookController_createEndpoint(createWebhookEndpointDto, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof WebhookController_createEndpoint>>, TError, TData> & { queryKey: QueryKey }
}

export type WebhookControllerCreateEndpointQueryResult = NonNullable<Awaited<ReturnType<typeof WebhookController_createEndpoint>>>
export type WebhookControllerCreateEndpointQueryError = unknown


/**
 * @summary Create a webhook endpoint
 */

export function useWebhookControllerCreateEndpoint<TData = Awaited<ReturnType<typeof WebhookController_createEndpoint>>, TError = unknown>(
 createWebhookEndpointDto: CreateWebhookEndpointDto, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof WebhookController_createEndpoint>>, TError, TData>, request?: SecondParameter<typeof customInstance>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getWebhookControllerCreateEndpointQueryOptions(createWebhookEndpointDto,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type WebhookController_listEndpointsResponse200 = {
  data: void
  status: 200
}

export type WebhookController_listEndpointsResponseSuccess = (WebhookController_listEndpointsResponse200) & {
  headers: Headers;
};
;

export type WebhookController_listEndpointsResponse = (WebhookController_listEndpointsResponseSuccess)

export const getWebhookControllerListEndpointsUrl = () => {




  return `/api/v1/webhooks/endpoints`
}

/**
 * @summary List all webhook endpoints
 */
export const WebhookController_listEndpoints = async ( options?: RequestInit): Promise<WebhookController_listEndpointsResponse> => {

  return customInstance<WebhookController_listEndpointsResponse>(getWebhookControllerListEndpointsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}




export const getWebhookControllerListEndpointsMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof WebhookController_listEndpoints>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof WebhookController_listEndpoints>>, TError,void, TContext> => {

const mutationKey = ['webhookControllerListEndpoints'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof WebhookController_listEndpoints>>, void> = () => {


          return  WebhookController_listEndpoints(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type WebhookControllerListEndpointsMutationResult = NonNullable<Awaited<ReturnType<typeof WebhookController_listEndpoints>>>

    export type WebhookControllerListEndpointsMutationError = unknown

    /**
 * @summary List all webhook endpoints
 */
export const useWebhookControllerListEndpoints = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof WebhookController_listEndpoints>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof WebhookController_listEndpoints>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getWebhookControllerListEndpointsMutationOptions(options));
    }
    export type WebhookController_getEndpointResponse200 = {
  data: void
  status: 200
}

export type WebhookController_getEndpointResponseSuccess = (WebhookController_getEndpointResponse200) & {
  headers: Headers;
};
;

export type WebhookController_getEndpointResponse = (WebhookController_getEndpointResponseSuccess)

export const getWebhookControllerGetEndpointUrl = (endpointId: string,) => {




  return `/api/v1/webhooks/endpoints/${endpointId}`
}

/**
 * @summary Get webhook endpoint by ID
 */
export const WebhookController_getEndpoint = async (endpointId: string, options?: RequestInit): Promise<WebhookController_getEndpointResponse> => {

  return customInstance<WebhookController_getEndpointResponse>(getWebhookControllerGetEndpointUrl(endpointId),
  {
    ...options,
    method: 'GET'


  }
);}




export const getWebhookControllerGetEndpointMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof WebhookController_getEndpoint>>, TError,{endpointId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof WebhookController_getEndpoint>>, TError,{endpointId: string}, TContext> => {

const mutationKey = ['webhookControllerGetEndpoint'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof WebhookController_getEndpoint>>, {endpointId: string}> = (props) => {
          const {endpointId} = props ?? {};

          return  WebhookController_getEndpoint(endpointId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type WebhookControllerGetEndpointMutationResult = NonNullable<Awaited<ReturnType<typeof WebhookController_getEndpoint>>>

    export type WebhookControllerGetEndpointMutationError = unknown

    /**
 * @summary Get webhook endpoint by ID
 */
export const useWebhookControllerGetEndpoint = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof WebhookController_getEndpoint>>, TError,{endpointId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof WebhookController_getEndpoint>>,
        TError,
        {endpointId: string},
        TContext
      > => {
      return useMutation(getWebhookControllerGetEndpointMutationOptions(options));
    }
    export type WebhookController_updateEndpointResponse200 = {
  data: void
  status: 200
}

export type WebhookController_updateEndpointResponseSuccess = (WebhookController_updateEndpointResponse200) & {
  headers: Headers;
};
;

export type WebhookController_updateEndpointResponse = (WebhookController_updateEndpointResponseSuccess)

export const getWebhookControllerUpdateEndpointUrl = (endpointId: string,) => {




  return `/api/v1/webhooks/endpoints/${endpointId}`
}

/**
 * @summary Update webhook endpoint
 */
export const WebhookController_updateEndpoint = async (endpointId: string,
    updateWebhookEndpointDto: UpdateWebhookEndpointDto, options?: RequestInit): Promise<WebhookController_updateEndpointResponse> => {

  return customInstance<WebhookController_updateEndpointResponse>(getWebhookControllerUpdateEndpointUrl(endpointId),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateWebhookEndpointDto)
  }
);}





export const getWebhookControllerUpdateEndpointQueryKey = (endpointId: string,
    updateWebhookEndpointDto?: UpdateWebhookEndpointDto,) => {
    return [
    'PATCH', `/api/v1/webhooks/endpoints/${endpointId}`, updateWebhookEndpointDto
    ] as const;
    }


export const getWebhookControllerUpdateEndpointQueryOptions = <TData = Awaited<ReturnType<typeof WebhookController_updateEndpoint>>, TError = unknown>(endpointId: string,
    updateWebhookEndpointDto: UpdateWebhookEndpointDto, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof WebhookController_updateEndpoint>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getWebhookControllerUpdateEndpointQueryKey(endpointId,updateWebhookEndpointDto);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof WebhookController_updateEndpoint>>> = ({ signal }) => WebhookController_updateEndpoint(endpointId,updateWebhookEndpointDto, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: endpointId !== null && endpointId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof WebhookController_updateEndpoint>>, TError, TData> & { queryKey: QueryKey }
}

export type WebhookControllerUpdateEndpointQueryResult = NonNullable<Awaited<ReturnType<typeof WebhookController_updateEndpoint>>>
export type WebhookControllerUpdateEndpointQueryError = unknown


/**
 * @summary Update webhook endpoint
 */

export function useWebhookControllerUpdateEndpoint<TData = Awaited<ReturnType<typeof WebhookController_updateEndpoint>>, TError = unknown>(
 endpointId: string,
    updateWebhookEndpointDto: UpdateWebhookEndpointDto, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof WebhookController_updateEndpoint>>, TError, TData>, request?: SecondParameter<typeof customInstance>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getWebhookControllerUpdateEndpointQueryOptions(endpointId,updateWebhookEndpointDto,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type WebhookController_deleteEndpointResponse204 = {
  data: void
  status: 204
}

export type WebhookController_deleteEndpointResponseSuccess = (WebhookController_deleteEndpointResponse204) & {
  headers: Headers;
};
;

export type WebhookController_deleteEndpointResponse = (WebhookController_deleteEndpointResponseSuccess)

export const getWebhookControllerDeleteEndpointUrl = (endpointId: string,) => {




  return `/api/v1/webhooks/endpoints/${endpointId}`
}

/**
 * @summary Deactivate webhook endpoint
 */
export const WebhookController_deleteEndpoint = async (endpointId: string, options?: RequestInit): Promise<WebhookController_deleteEndpointResponse> => {

  return customInstance<WebhookController_deleteEndpointResponse>(getWebhookControllerDeleteEndpointUrl(endpointId),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getWebhookControllerDeleteEndpointQueryKey = (endpointId: string,) => {
    return [
    'DELETE', `/api/v1/webhooks/endpoints/${endpointId}`
    ] as const;
    }


export const getWebhookControllerDeleteEndpointQueryOptions = <TData = Awaited<ReturnType<typeof WebhookController_deleteEndpoint>>, TError = unknown>(endpointId: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof WebhookController_deleteEndpoint>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getWebhookControllerDeleteEndpointQueryKey(endpointId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof WebhookController_deleteEndpoint>>> = ({ signal }) => WebhookController_deleteEndpoint(endpointId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: endpointId !== null && endpointId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof WebhookController_deleteEndpoint>>, TError, TData> & { queryKey: QueryKey }
}

export type WebhookControllerDeleteEndpointQueryResult = NonNullable<Awaited<ReturnType<typeof WebhookController_deleteEndpoint>>>
export type WebhookControllerDeleteEndpointQueryError = unknown


/**
 * @summary Deactivate webhook endpoint
 */

export function useWebhookControllerDeleteEndpoint<TData = Awaited<ReturnType<typeof WebhookController_deleteEndpoint>>, TError = unknown>(
 endpointId: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof WebhookController_deleteEndpoint>>, TError, TData>, request?: SecondParameter<typeof customInstance>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getWebhookControllerDeleteEndpointQueryOptions(endpointId,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type WebhookController_rotateSecretResponse201 = {
  data: void
  status: 201
}

export type WebhookController_rotateSecretResponseSuccess = (WebhookController_rotateSecretResponse201) & {
  headers: Headers;
};
;

export type WebhookController_rotateSecretResponse = (WebhookController_rotateSecretResponseSuccess)

export const getWebhookControllerRotateSecretUrl = (endpointId: string,) => {




  return `/api/v1/webhooks/endpoints/${endpointId}/rotate`
}

/**
 * @summary Rotate webhook signing secret
 */
export const WebhookController_rotateSecret = async (endpointId: string, options?: RequestInit): Promise<WebhookController_rotateSecretResponse> => {

  return customInstance<WebhookController_rotateSecretResponse>(getWebhookControllerRotateSecretUrl(endpointId),
  {
    ...options,
    method: 'POST'


  }
);}





export const getWebhookControllerRotateSecretQueryKey = (endpointId: string,) => {
    return [
    'POST', `/api/v1/webhooks/endpoints/${endpointId}/rotate`
    ] as const;
    }


export const getWebhookControllerRotateSecretQueryOptions = <TData = Awaited<ReturnType<typeof WebhookController_rotateSecret>>, TError = unknown>(endpointId: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof WebhookController_rotateSecret>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getWebhookControllerRotateSecretQueryKey(endpointId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof WebhookController_rotateSecret>>> = ({ signal }) => WebhookController_rotateSecret(endpointId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: endpointId !== null && endpointId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof WebhookController_rotateSecret>>, TError, TData> & { queryKey: QueryKey }
}

export type WebhookControllerRotateSecretQueryResult = NonNullable<Awaited<ReturnType<typeof WebhookController_rotateSecret>>>
export type WebhookControllerRotateSecretQueryError = unknown


/**
 * @summary Rotate webhook signing secret
 */

export function useWebhookControllerRotateSecret<TData = Awaited<ReturnType<typeof WebhookController_rotateSecret>>, TError = unknown>(
 endpointId: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof WebhookController_rotateSecret>>, TError, TData>, request?: SecondParameter<typeof customInstance>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getWebhookControllerRotateSecretQueryOptions(endpointId,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type WebhookController_testEndpointResponse202 = {
  data: void
  status: 202
}

export type WebhookController_testEndpointResponseSuccess = (WebhookController_testEndpointResponse202) & {
  headers: Headers;
};
;

export type WebhookController_testEndpointResponse = (WebhookController_testEndpointResponseSuccess)

export const getWebhookControllerTestEndpointUrl = (endpointId: string,) => {




  return `/api/v1/webhooks/endpoints/${endpointId}/test`
}

/**
 * @summary Send test event to endpoint
 */
export const WebhookController_testEndpoint = async (endpointId: string, options?: RequestInit): Promise<WebhookController_testEndpointResponse> => {

  return customInstance<WebhookController_testEndpointResponse>(getWebhookControllerTestEndpointUrl(endpointId),
  {
    ...options,
    method: 'POST'


  }
);}





export const getWebhookControllerTestEndpointQueryKey = (endpointId: string,) => {
    return [
    'POST', `/api/v1/webhooks/endpoints/${endpointId}/test`
    ] as const;
    }


export const getWebhookControllerTestEndpointQueryOptions = <TData = Awaited<ReturnType<typeof WebhookController_testEndpoint>>, TError = unknown>(endpointId: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof WebhookController_testEndpoint>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getWebhookControllerTestEndpointQueryKey(endpointId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof WebhookController_testEndpoint>>> = ({ signal }) => WebhookController_testEndpoint(endpointId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: endpointId !== null && endpointId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof WebhookController_testEndpoint>>, TError, TData> & { queryKey: QueryKey }
}

export type WebhookControllerTestEndpointQueryResult = NonNullable<Awaited<ReturnType<typeof WebhookController_testEndpoint>>>
export type WebhookControllerTestEndpointQueryError = unknown


/**
 * @summary Send test event to endpoint
 */

export function useWebhookControllerTestEndpoint<TData = Awaited<ReturnType<typeof WebhookController_testEndpoint>>, TError = unknown>(
 endpointId: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof WebhookController_testEndpoint>>, TError, TData>, request?: SecondParameter<typeof customInstance>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getWebhookControllerTestEndpointQueryOptions(endpointId,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type WebhookController_resetFailuresResponse200 = {
  data: void
  status: 200
}

export type WebhookController_resetFailuresResponseSuccess = (WebhookController_resetFailuresResponse200) & {
  headers: Headers;
};
;

export type WebhookController_resetFailuresResponse = (WebhookController_resetFailuresResponseSuccess)

export const getWebhookControllerResetFailuresUrl = (endpointId: string,) => {




  return `/api/v1/webhooks/endpoints/${endpointId}/reset-failures`
}

/**
 * @summary Reset failure count for endpoint
 */
export const WebhookController_resetFailures = async (endpointId: string, options?: RequestInit): Promise<WebhookController_resetFailuresResponse> => {

  return customInstance<WebhookController_resetFailuresResponse>(getWebhookControllerResetFailuresUrl(endpointId),
  {
    ...options,
    method: 'POST'


  }
);}





export const getWebhookControllerResetFailuresQueryKey = (endpointId: string,) => {
    return [
    'POST', `/api/v1/webhooks/endpoints/${endpointId}/reset-failures`
    ] as const;
    }


export const getWebhookControllerResetFailuresQueryOptions = <TData = Awaited<ReturnType<typeof WebhookController_resetFailures>>, TError = unknown>(endpointId: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof WebhookController_resetFailures>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getWebhookControllerResetFailuresQueryKey(endpointId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof WebhookController_resetFailures>>> = ({ signal }) => WebhookController_resetFailures(endpointId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: endpointId !== null && endpointId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof WebhookController_resetFailures>>, TError, TData> & { queryKey: QueryKey }
}

export type WebhookControllerResetFailuresQueryResult = NonNullable<Awaited<ReturnType<typeof WebhookController_resetFailures>>>
export type WebhookControllerResetFailuresQueryError = unknown


/**
 * @summary Reset failure count for endpoint
 */

export function useWebhookControllerResetFailures<TData = Awaited<ReturnType<typeof WebhookController_resetFailures>>, TError = unknown>(
 endpointId: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof WebhookController_resetFailures>>, TError, TData>, request?: SecondParameter<typeof customInstance>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getWebhookControllerResetFailuresQueryOptions(endpointId,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type WebhookController_listDeliveriesResponse200 = {
  data: void
  status: 200
}

export type WebhookController_listDeliveriesResponseSuccess = (WebhookController_listDeliveriesResponse200) & {
  headers: Headers;
};
;

export type WebhookController_listDeliveriesResponse = (WebhookController_listDeliveriesResponseSuccess)

export const getWebhookControllerListDeliveriesUrl = (params?: WebhookControllerListDeliveriesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/webhooks/deliveries?${stringifiedParams}` : `/api/v1/webhooks/deliveries`
}

/**
 * @summary List webhook deliveries
 */
export const WebhookController_listDeliveries = async (params?: WebhookControllerListDeliveriesParams, options?: RequestInit): Promise<WebhookController_listDeliveriesResponse> => {

  return customInstance<WebhookController_listDeliveriesResponse>(getWebhookControllerListDeliveriesUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}




export const getWebhookControllerListDeliveriesMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof WebhookController_listDeliveries>>, TError,{params?: WebhookControllerListDeliveriesParams}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof WebhookController_listDeliveries>>, TError,{params?: WebhookControllerListDeliveriesParams}, TContext> => {

const mutationKey = ['webhookControllerListDeliveries'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof WebhookController_listDeliveries>>, {params?: WebhookControllerListDeliveriesParams}> = (props) => {
          const {params} = props ?? {};

          return  WebhookController_listDeliveries(params,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type WebhookControllerListDeliveriesMutationResult = NonNullable<Awaited<ReturnType<typeof WebhookController_listDeliveries>>>

    export type WebhookControllerListDeliveriesMutationError = unknown

    /**
 * @summary List webhook deliveries
 */
export const useWebhookControllerListDeliveries = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof WebhookController_listDeliveries>>, TError,{params?: WebhookControllerListDeliveriesParams}, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof WebhookController_listDeliveries>>,
        TError,
        {params?: WebhookControllerListDeliveriesParams},
        TContext
      > => {
      return useMutation(getWebhookControllerListDeliveriesMutationOptions(options));
    }
    export type WebhookController_getDeliveryResponse200 = {
  data: void
  status: 200
}

export type WebhookController_getDeliveryResponseSuccess = (WebhookController_getDeliveryResponse200) & {
  headers: Headers;
};
;

export type WebhookController_getDeliveryResponse = (WebhookController_getDeliveryResponseSuccess)

export const getWebhookControllerGetDeliveryUrl = (deliveryId: string,) => {




  return `/api/v1/webhooks/deliveries/${deliveryId}`
}

/**
 * @summary Get delivery details
 */
export const WebhookController_getDelivery = async (deliveryId: string, options?: RequestInit): Promise<WebhookController_getDeliveryResponse> => {

  return customInstance<WebhookController_getDeliveryResponse>(getWebhookControllerGetDeliveryUrl(deliveryId),
  {
    ...options,
    method: 'GET'


  }
);}




export const getWebhookControllerGetDeliveryMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof WebhookController_getDelivery>>, TError,{deliveryId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof WebhookController_getDelivery>>, TError,{deliveryId: string}, TContext> => {

const mutationKey = ['webhookControllerGetDelivery'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof WebhookController_getDelivery>>, {deliveryId: string}> = (props) => {
          const {deliveryId} = props ?? {};

          return  WebhookController_getDelivery(deliveryId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type WebhookControllerGetDeliveryMutationResult = NonNullable<Awaited<ReturnType<typeof WebhookController_getDelivery>>>

    export type WebhookControllerGetDeliveryMutationError = unknown

    /**
 * @summary Get delivery details
 */
export const useWebhookControllerGetDelivery = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof WebhookController_getDelivery>>, TError,{deliveryId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof WebhookController_getDelivery>>,
        TError,
        {deliveryId: string},
        TContext
      > => {
      return useMutation(getWebhookControllerGetDeliveryMutationOptions(options));
    }
    export type WebhookController_retryDeliveryResponse202 = {
  data: void
  status: 202
}

export type WebhookController_retryDeliveryResponseSuccess = (WebhookController_retryDeliveryResponse202) & {
  headers: Headers;
};
;

export type WebhookController_retryDeliveryResponse = (WebhookController_retryDeliveryResponseSuccess)

export const getWebhookControllerRetryDeliveryUrl = (deliveryId: string,) => {




  return `/api/v1/webhooks/deliveries/${deliveryId}/retry`
}

/**
 * @summary Retry a failed delivery
 */
export const WebhookController_retryDelivery = async (deliveryId: string, options?: RequestInit): Promise<WebhookController_retryDeliveryResponse> => {

  return customInstance<WebhookController_retryDeliveryResponse>(getWebhookControllerRetryDeliveryUrl(deliveryId),
  {
    ...options,
    method: 'POST'


  }
);}





export const getWebhookControllerRetryDeliveryQueryKey = (deliveryId: string,) => {
    return [
    'POST', `/api/v1/webhooks/deliveries/${deliveryId}/retry`
    ] as const;
    }


export const getWebhookControllerRetryDeliveryQueryOptions = <TData = Awaited<ReturnType<typeof WebhookController_retryDelivery>>, TError = unknown>(deliveryId: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof WebhookController_retryDelivery>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getWebhookControllerRetryDeliveryQueryKey(deliveryId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof WebhookController_retryDelivery>>> = ({ signal }) => WebhookController_retryDelivery(deliveryId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: deliveryId !== null && deliveryId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof WebhookController_retryDelivery>>, TError, TData> & { queryKey: QueryKey }
}

export type WebhookControllerRetryDeliveryQueryResult = NonNullable<Awaited<ReturnType<typeof WebhookController_retryDelivery>>>
export type WebhookControllerRetryDeliveryQueryError = unknown


/**
 * @summary Retry a failed delivery
 */

export function useWebhookControllerRetryDelivery<TData = Awaited<ReturnType<typeof WebhookController_retryDelivery>>, TError = unknown>(
 deliveryId: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof WebhookController_retryDelivery>>, TError, TData>, request?: SecondParameter<typeof customInstance>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getWebhookControllerRetryDeliveryQueryOptions(deliveryId,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type WebhookController_listEventsResponse200 = {
  data: void
  status: 200
}

export type WebhookController_listEventsResponseSuccess = (WebhookController_listEventsResponse200) & {
  headers: Headers;
};
;

export type WebhookController_listEventsResponse = (WebhookController_listEventsResponseSuccess)

export const getWebhookControllerListEventsUrl = (params: WebhookControllerListEventsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/webhooks/events?${stringifiedParams}` : `/api/v1/webhooks/events`
}

/**
 * @summary List webhook events
 */
export const WebhookController_listEvents = async (params: WebhookControllerListEventsParams, options?: RequestInit): Promise<WebhookController_listEventsResponse> => {

  return customInstance<WebhookController_listEventsResponse>(getWebhookControllerListEventsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}




export const getWebhookControllerListEventsMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof WebhookController_listEvents>>, TError,{params: WebhookControllerListEventsParams}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof WebhookController_listEvents>>, TError,{params: WebhookControllerListEventsParams}, TContext> => {

const mutationKey = ['webhookControllerListEvents'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof WebhookController_listEvents>>, {params: WebhookControllerListEventsParams}> = (props) => {
          const {params} = props ?? {};

          return  WebhookController_listEvents(params,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type WebhookControllerListEventsMutationResult = NonNullable<Awaited<ReturnType<typeof WebhookController_listEvents>>>

    export type WebhookControllerListEventsMutationError = unknown

    /**
 * @summary List webhook events
 */
export const useWebhookControllerListEvents = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof WebhookController_listEvents>>, TError,{params: WebhookControllerListEventsParams}, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof WebhookController_listEvents>>,
        TError,
        {params: WebhookControllerListEventsParams},
        TContext
      > => {
      return useMutation(getWebhookControllerListEventsMutationOptions(options));
    }
