/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * WMS API
 * Warehouse Management System API
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  SettingPaginatedDto,
  SystemSettingDto,
  SystemSettingHistoryDto,
  UpdateSettingValueDto,
  UpsertSettingDto
} from '../../../types/wms-api';

import { customInstance } from '../../../http/httpClient.js';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type SettingsWebController_findAllResponse200 = {
  data: SettingPaginatedDto
  status: 200
}

export type SettingsWebController_findAllResponseSuccess = (SettingsWebController_findAllResponse200) & {
  headers: Headers;
};
;

export type SettingsWebController_findAllResponse = (SettingsWebController_findAllResponseSuccess)

export const getSettingsWebControllerFindAllUrl = () => {




  return `/api/v1/wms/web/settings`
}

export const SettingsWebController_findAll = async ( options?: RequestInit): Promise<SettingsWebController_findAllResponse> => {

  return customInstance<SettingsWebController_findAllResponse>(getSettingsWebControllerFindAllUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getSettingsWebControllerFindAllMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof SettingsWebController_findAll>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof SettingsWebController_findAll>>, TError,void, TContext> => {

const mutationKey = ['settingsWebControllerFindAll'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof SettingsWebController_findAll>>, void> = () => {


          return  SettingsWebController_findAll(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type SettingsWebControllerFindAllMutationResult = NonNullable<Awaited<ReturnType<typeof SettingsWebController_findAll>>>

    export type SettingsWebControllerFindAllMutationError = unknown

    export const useSettingsWebControllerFindAll = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof SettingsWebController_findAll>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof SettingsWebController_findAll>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getSettingsWebControllerFindAllMutationOptions(options));
    }
    export type SettingsWebController_getAllWithDefaultsResponse200 = {
  data: SystemSettingDto[]
  status: 200
}

export type SettingsWebController_getAllWithDefaultsResponseSuccess = (SettingsWebController_getAllWithDefaultsResponse200) & {
  headers: Headers;
};
;

export type SettingsWebController_getAllWithDefaultsResponse = (SettingsWebController_getAllWithDefaultsResponseSuccess)

export const getSettingsWebControllerGetAllWithDefaultsUrl = () => {




  return `/api/v1/wms/web/settings/defaults`
}

export const SettingsWebController_getAllWithDefaults = async ( options?: RequestInit): Promise<SettingsWebController_getAllWithDefaultsResponse> => {

  return customInstance<SettingsWebController_getAllWithDefaultsResponse>(getSettingsWebControllerGetAllWithDefaultsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getSettingsWebControllerGetAllWithDefaultsMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof SettingsWebController_getAllWithDefaults>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof SettingsWebController_getAllWithDefaults>>, TError,void, TContext> => {

const mutationKey = ['settingsWebControllerGetAllWithDefaults'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof SettingsWebController_getAllWithDefaults>>, void> = () => {


          return  SettingsWebController_getAllWithDefaults(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type SettingsWebControllerGetAllWithDefaultsMutationResult = NonNullable<Awaited<ReturnType<typeof SettingsWebController_getAllWithDefaults>>>

    export type SettingsWebControllerGetAllWithDefaultsMutationError = unknown

    export const useSettingsWebControllerGetAllWithDefaults = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof SettingsWebController_getAllWithDefaults>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof SettingsWebController_getAllWithDefaults>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getSettingsWebControllerGetAllWithDefaultsMutationOptions(options));
    }
    export type SettingsWebController_getResponse200 = {
  data: SystemSettingDto
  status: 200
}

export type SettingsWebController_getResponseSuccess = (SettingsWebController_getResponse200) & {
  headers: Headers;
};
;

export type SettingsWebController_getResponse = (SettingsWebController_getResponseSuccess)

export const getSettingsWebControllerGetUrl = (key: string,) => {




  return `/api/v1/wms/web/settings/${key}`
}

export const SettingsWebController_get = async (key: string, options?: RequestInit): Promise<SettingsWebController_getResponse> => {

  return customInstance<SettingsWebController_getResponse>(getSettingsWebControllerGetUrl(key),
  {
    ...options,
    method: 'GET'


  }
);}





export const getSettingsWebControllerGetMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof SettingsWebController_get>>, TError,{key: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof SettingsWebController_get>>, TError,{key: string}, TContext> => {

const mutationKey = ['settingsWebControllerGet'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof SettingsWebController_get>>, {key: string}> = (props) => {
          const {key} = props ?? {};

          return  SettingsWebController_get(key,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type SettingsWebControllerGetMutationResult = NonNullable<Awaited<ReturnType<typeof SettingsWebController_get>>>

    export type SettingsWebControllerGetMutationError = unknown

    export const useSettingsWebControllerGet = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof SettingsWebController_get>>, TError,{key: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof SettingsWebController_get>>,
        TError,
        {key: string},
        TContext
      > => {
      return useMutation(getSettingsWebControllerGetMutationOptions(options));
    }
    export type SettingsWebController_upsertResponse201 = {
  data: SystemSettingDto
  status: 201
}

export type SettingsWebController_upsertResponseSuccess = (SettingsWebController_upsertResponse201) & {
  headers: Headers;
};
;

export type SettingsWebController_upsertResponse = (SettingsWebController_upsertResponseSuccess)

export const getSettingsWebControllerUpsertUrl = (key: string,) => {




  return `/api/v1/wms/web/settings/${key}`
}

export const SettingsWebController_upsert = async (key: string,
    upsertSettingDto: UpsertSettingDto, options?: RequestInit): Promise<SettingsWebController_upsertResponse> => {

  return customInstance<SettingsWebController_upsertResponse>(getSettingsWebControllerUpsertUrl(key),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(upsertSettingDto)
  }
);}





export const getSettingsWebControllerUpsertQueryKey = (key: string,
    upsertSettingDto?: UpsertSettingDto,) => {
    return [
    'POST', `/api/v1/wms/web/settings/${key}`, upsertSettingDto
    ] as const;
    }


export const getSettingsWebControllerUpsertQueryOptions = <TData = Awaited<ReturnType<typeof SettingsWebController_upsert>>, TError = unknown>(key: string,
    upsertSettingDto: UpsertSettingDto, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof SettingsWebController_upsert>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSettingsWebControllerUpsertQueryKey(key,upsertSettingDto);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof SettingsWebController_upsert>>> = ({ signal }) => SettingsWebController_upsert(key,upsertSettingDto, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: key !== null && key !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof SettingsWebController_upsert>>, TError, TData> & { queryKey: QueryKey }
}

export type SettingsWebControllerUpsertQueryResult = NonNullable<Awaited<ReturnType<typeof SettingsWebController_upsert>>>
export type SettingsWebControllerUpsertQueryError = unknown



export function useSettingsWebControllerUpsert<TData = Awaited<ReturnType<typeof SettingsWebController_upsert>>, TError = unknown>(
 key: string,
    upsertSettingDto: UpsertSettingDto, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof SettingsWebController_upsert>>, TError, TData>, request?: SecondParameter<typeof customInstance>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getSettingsWebControllerUpsertQueryOptions(key,upsertSettingDto,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}






export type SettingsWebController_updateResponse200 = {
  data: SystemSettingDto
  status: 200
}

export type SettingsWebController_updateResponseSuccess = (SettingsWebController_updateResponse200) & {
  headers: Headers;
};
;

export type SettingsWebController_updateResponse = (SettingsWebController_updateResponseSuccess)

export const getSettingsWebControllerUpdateUrl = (key: string,) => {




  return `/api/v1/wms/web/settings/${key}`
}

export const SettingsWebController_update = async (key: string,
    updateSettingValueDto: UpdateSettingValueDto, options?: RequestInit): Promise<SettingsWebController_updateResponse> => {

  return customInstance<SettingsWebController_updateResponse>(getSettingsWebControllerUpdateUrl(key),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateSettingValueDto)
  }
);}





export const getSettingsWebControllerUpdateQueryKey = (key: string,
    updateSettingValueDto?: UpdateSettingValueDto,) => {
    return [
    'PATCH', `/api/v1/wms/web/settings/${key}`, updateSettingValueDto
    ] as const;
    }


export const getSettingsWebControllerUpdateQueryOptions = <TData = Awaited<ReturnType<typeof SettingsWebController_update>>, TError = unknown>(key: string,
    updateSettingValueDto: UpdateSettingValueDto, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof SettingsWebController_update>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSettingsWebControllerUpdateQueryKey(key,updateSettingValueDto);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof SettingsWebController_update>>> = ({ signal }) => SettingsWebController_update(key,updateSettingValueDto, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: key !== null && key !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof SettingsWebController_update>>, TError, TData> & { queryKey: QueryKey }
}

export type SettingsWebControllerUpdateQueryResult = NonNullable<Awaited<ReturnType<typeof SettingsWebController_update>>>
export type SettingsWebControllerUpdateQueryError = unknown



export function useSettingsWebControllerUpdate<TData = Awaited<ReturnType<typeof SettingsWebController_update>>, TError = unknown>(
 key: string,
    updateSettingValueDto: UpdateSettingValueDto, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof SettingsWebController_update>>, TError, TData>, request?: SecondParameter<typeof customInstance>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getSettingsWebControllerUpdateQueryOptions(key,updateSettingValueDto,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}






export type SettingsWebController_removeResponse200 = {
  data: SystemSettingDto
  status: 200
}

export type SettingsWebController_removeResponseSuccess = (SettingsWebController_removeResponse200) & {
  headers: Headers;
};
;

export type SettingsWebController_removeResponse = (SettingsWebController_removeResponseSuccess)

export const getSettingsWebControllerRemoveUrl = (key: string,) => {




  return `/api/v1/wms/web/settings/${key}`
}

export const SettingsWebController_remove = async (key: string, options?: RequestInit): Promise<SettingsWebController_removeResponse> => {

  return customInstance<SettingsWebController_removeResponse>(getSettingsWebControllerRemoveUrl(key),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getSettingsWebControllerRemoveQueryKey = (key: string,) => {
    return [
    'DELETE', `/api/v1/wms/web/settings/${key}`
    ] as const;
    }


export const getSettingsWebControllerRemoveQueryOptions = <TData = Awaited<ReturnType<typeof SettingsWebController_remove>>, TError = unknown>(key: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof SettingsWebController_remove>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSettingsWebControllerRemoveQueryKey(key);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof SettingsWebController_remove>>> = ({ signal }) => SettingsWebController_remove(key, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: key !== null && key !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof SettingsWebController_remove>>, TError, TData> & { queryKey: QueryKey }
}

export type SettingsWebControllerRemoveQueryResult = NonNullable<Awaited<ReturnType<typeof SettingsWebController_remove>>>
export type SettingsWebControllerRemoveQueryError = unknown



export function useSettingsWebControllerRemove<TData = Awaited<ReturnType<typeof SettingsWebController_remove>>, TError = unknown>(
 key: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof SettingsWebController_remove>>, TError, TData>, request?: SecondParameter<typeof customInstance>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getSettingsWebControllerRemoveQueryOptions(key,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}






export type SettingsWebController_getHistoryResponse200 = {
  data: SystemSettingHistoryDto[]
  status: 200
}

export type SettingsWebController_getHistoryResponseSuccess = (SettingsWebController_getHistoryResponse200) & {
  headers: Headers;
};
;

export type SettingsWebController_getHistoryResponse = (SettingsWebController_getHistoryResponseSuccess)

export const getSettingsWebControllerGetHistoryUrl = (key: string,) => {




  return `/api/v1/wms/web/settings/${key}/history`
}

export const SettingsWebController_getHistory = async (key: string, options?: RequestInit): Promise<SettingsWebController_getHistoryResponse> => {

  return customInstance<SettingsWebController_getHistoryResponse>(getSettingsWebControllerGetHistoryUrl(key),
  {
    ...options,
    method: 'GET'


  }
);}





export const getSettingsWebControllerGetHistoryMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof SettingsWebController_getHistory>>, TError,{key: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof SettingsWebController_getHistory>>, TError,{key: string}, TContext> => {

const mutationKey = ['settingsWebControllerGetHistory'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof SettingsWebController_getHistory>>, {key: string}> = (props) => {
          const {key} = props ?? {};

          return  SettingsWebController_getHistory(key,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type SettingsWebControllerGetHistoryMutationResult = NonNullable<Awaited<ReturnType<typeof SettingsWebController_getHistory>>>

    export type SettingsWebControllerGetHistoryMutationError = unknown

    export const useSettingsWebControllerGetHistory = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof SettingsWebController_getHistory>>, TError,{key: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof SettingsWebController_getHistory>>,
        TError,
        {key: string},
        TContext
      > => {
      return useMutation(getSettingsWebControllerGetHistoryMutationOptions(options));
    }
