/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * WMS API
 * Warehouse Management System API
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  BillingEventListResponseDto,
  BillingRunListResponseDto,
  CreateFulfillmentBillingEventDto,
  CreateFulfillmentBillingRunDto,
  CreateWorkflowDefinitionDto,
  DeleteResultDto,
  FulfillmentBillingAggregationDto,
  FulfillmentBillingEventDto,
  FulfillmentBillingRunDetailDto,
  FulfillmentBillingRunDto,
  FulfillmentWorkflowDefinitionDto,
  FulfillmentWorkflowEventDto,
  FulfillmentWorkflowTransitionDto,
  LinkEventsResultDto,
  UpdateWorkflowDefinitionDto,
  WorkflowDefinitionListResponseDto,
  WorkflowExecutionListResponseDto
} from '../../../types/wms-api';

import { customInstance } from '../../../http/httpClient.js';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type FulfillmentWebController_createDefinitionResponse201 = {
  data: FulfillmentWorkflowDefinitionDto
  status: 201
}

export type FulfillmentWebController_createDefinitionResponseSuccess = (FulfillmentWebController_createDefinitionResponse201) & {
  headers: Headers;
};
;

export type FulfillmentWebController_createDefinitionResponse = (FulfillmentWebController_createDefinitionResponseSuccess)

export const getFulfillmentWebControllerCreateDefinitionUrl = () => {




  return `/api/v1/wms/web/fulfillment/workflow-definitions`
}

/**
 * @summary Create workflow definition
 */
export const FulfillmentWebController_createDefinition = async (createWorkflowDefinitionDto: CreateWorkflowDefinitionDto, options?: RequestInit): Promise<FulfillmentWebController_createDefinitionResponse> => {

  return customInstance<FulfillmentWebController_createDefinitionResponse>(getFulfillmentWebControllerCreateDefinitionUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createWorkflowDefinitionDto)
  }
);}





export const getFulfillmentWebControllerCreateDefinitionQueryKey = (createWorkflowDefinitionDto?: CreateWorkflowDefinitionDto,) => {
    return [
    'POST', `/api/v1/wms/web/fulfillment/workflow-definitions`, createWorkflowDefinitionDto
    ] as const;
    }


export const getFulfillmentWebControllerCreateDefinitionQueryOptions = <TData = Awaited<ReturnType<typeof FulfillmentWebController_createDefinition>>, TError = unknown>(createWorkflowDefinitionDto: CreateWorkflowDefinitionDto, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof FulfillmentWebController_createDefinition>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getFulfillmentWebControllerCreateDefinitionQueryKey(createWorkflowDefinitionDto);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof FulfillmentWebController_createDefinition>>> = ({ signal }) => FulfillmentWebController_createDefinition(createWorkflowDefinitionDto, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof FulfillmentWebController_createDefinition>>, TError, TData> & { queryKey: QueryKey }
}

export type FulfillmentWebControllerCreateDefinitionQueryResult = NonNullable<Awaited<ReturnType<typeof FulfillmentWebController_createDefinition>>>
export type FulfillmentWebControllerCreateDefinitionQueryError = unknown


/**
 * @summary Create workflow definition
 */

export function useFulfillmentWebControllerCreateDefinition<TData = Awaited<ReturnType<typeof FulfillmentWebController_createDefinition>>, TError = unknown>(
 createWorkflowDefinitionDto: CreateWorkflowDefinitionDto, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof FulfillmentWebController_createDefinition>>, TError, TData>, request?: SecondParameter<typeof customInstance>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getFulfillmentWebControllerCreateDefinitionQueryOptions(createWorkflowDefinitionDto,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}






export type FulfillmentWebController_findAllDefinitionsResponse200 = {
  data: WorkflowDefinitionListResponseDto
  status: 200
}

export type FulfillmentWebController_findAllDefinitionsResponseSuccess = (FulfillmentWebController_findAllDefinitionsResponse200) & {
  headers: Headers;
};
;

export type FulfillmentWebController_findAllDefinitionsResponse = (FulfillmentWebController_findAllDefinitionsResponseSuccess)

export const getFulfillmentWebControllerFindAllDefinitionsUrl = () => {




  return `/api/v1/wms/web/fulfillment/workflow-definitions`
}

/**
 * @summary List workflow definitions
 */
export const FulfillmentWebController_findAllDefinitions = async ( options?: RequestInit): Promise<FulfillmentWebController_findAllDefinitionsResponse> => {

  return customInstance<FulfillmentWebController_findAllDefinitionsResponse>(getFulfillmentWebControllerFindAllDefinitionsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getFulfillmentWebControllerFindAllDefinitionsMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof FulfillmentWebController_findAllDefinitions>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof FulfillmentWebController_findAllDefinitions>>, TError,void, TContext> => {

const mutationKey = ['fulfillmentWebControllerFindAllDefinitions'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof FulfillmentWebController_findAllDefinitions>>, void> = () => {


          return  FulfillmentWebController_findAllDefinitions(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type FulfillmentWebControllerFindAllDefinitionsMutationResult = NonNullable<Awaited<ReturnType<typeof FulfillmentWebController_findAllDefinitions>>>

    export type FulfillmentWebControllerFindAllDefinitionsMutationError = unknown

    /**
 * @summary List workflow definitions
 */
export const useFulfillmentWebControllerFindAllDefinitions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof FulfillmentWebController_findAllDefinitions>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof FulfillmentWebController_findAllDefinitions>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getFulfillmentWebControllerFindAllDefinitionsMutationOptions(options));
    }
    export type FulfillmentWebController_findDefinitionByIdResponse200 = {
  data: FulfillmentWorkflowDefinitionDto
  status: 200
}

export type FulfillmentWebController_findDefinitionByIdResponseSuccess = (FulfillmentWebController_findDefinitionByIdResponse200) & {
  headers: Headers;
};
;

export type FulfillmentWebController_findDefinitionByIdResponse = (FulfillmentWebController_findDefinitionByIdResponseSuccess)

export const getFulfillmentWebControllerFindDefinitionByIdUrl = (id: string,) => {




  return `/api/v1/wms/web/fulfillment/workflow-definitions/${id}`
}

/**
 * @summary Get workflow definition by ID
 */
export const FulfillmentWebController_findDefinitionById = async (id: string, options?: RequestInit): Promise<FulfillmentWebController_findDefinitionByIdResponse> => {

  return customInstance<FulfillmentWebController_findDefinitionByIdResponse>(getFulfillmentWebControllerFindDefinitionByIdUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getFulfillmentWebControllerFindDefinitionByIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof FulfillmentWebController_findDefinitionById>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof FulfillmentWebController_findDefinitionById>>, TError,{id: string}, TContext> => {

const mutationKey = ['fulfillmentWebControllerFindDefinitionById'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof FulfillmentWebController_findDefinitionById>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  FulfillmentWebController_findDefinitionById(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type FulfillmentWebControllerFindDefinitionByIdMutationResult = NonNullable<Awaited<ReturnType<typeof FulfillmentWebController_findDefinitionById>>>

    export type FulfillmentWebControllerFindDefinitionByIdMutationError = unknown

    /**
 * @summary Get workflow definition by ID
 */
export const useFulfillmentWebControllerFindDefinitionById = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof FulfillmentWebController_findDefinitionById>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof FulfillmentWebController_findDefinitionById>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getFulfillmentWebControllerFindDefinitionByIdMutationOptions(options));
    }
    export type FulfillmentWebController_updateDefinitionResponse200 = {
  data: FulfillmentWorkflowDefinitionDto
  status: 200
}

export type FulfillmentWebController_updateDefinitionResponseSuccess = (FulfillmentWebController_updateDefinitionResponse200) & {
  headers: Headers;
};
;

export type FulfillmentWebController_updateDefinitionResponse = (FulfillmentWebController_updateDefinitionResponseSuccess)

export const getFulfillmentWebControllerUpdateDefinitionUrl = (id: string,) => {




  return `/api/v1/wms/web/fulfillment/workflow-definitions/${id}`
}

/**
 * @summary Update workflow definition
 */
export const FulfillmentWebController_updateDefinition = async (id: string,
    updateWorkflowDefinitionDto: UpdateWorkflowDefinitionDto, options?: RequestInit): Promise<FulfillmentWebController_updateDefinitionResponse> => {

  return customInstance<FulfillmentWebController_updateDefinitionResponse>(getFulfillmentWebControllerUpdateDefinitionUrl(id),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateWorkflowDefinitionDto)
  }
);}





export const getFulfillmentWebControllerUpdateDefinitionQueryKey = (id: string,
    updateWorkflowDefinitionDto?: UpdateWorkflowDefinitionDto,) => {
    return [
    'PATCH', `/api/v1/wms/web/fulfillment/workflow-definitions/${id}`, updateWorkflowDefinitionDto
    ] as const;
    }


export const getFulfillmentWebControllerUpdateDefinitionQueryOptions = <TData = Awaited<ReturnType<typeof FulfillmentWebController_updateDefinition>>, TError = unknown>(id: string,
    updateWorkflowDefinitionDto: UpdateWorkflowDefinitionDto, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof FulfillmentWebController_updateDefinition>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getFulfillmentWebControllerUpdateDefinitionQueryKey(id,updateWorkflowDefinitionDto);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof FulfillmentWebController_updateDefinition>>> = ({ signal }) => FulfillmentWebController_updateDefinition(id,updateWorkflowDefinitionDto, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof FulfillmentWebController_updateDefinition>>, TError, TData> & { queryKey: QueryKey }
}

export type FulfillmentWebControllerUpdateDefinitionQueryResult = NonNullable<Awaited<ReturnType<typeof FulfillmentWebController_updateDefinition>>>
export type FulfillmentWebControllerUpdateDefinitionQueryError = unknown


/**
 * @summary Update workflow definition
 */

export function useFulfillmentWebControllerUpdateDefinition<TData = Awaited<ReturnType<typeof FulfillmentWebController_updateDefinition>>, TError = unknown>(
 id: string,
    updateWorkflowDefinitionDto: UpdateWorkflowDefinitionDto, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof FulfillmentWebController_updateDefinition>>, TError, TData>, request?: SecondParameter<typeof customInstance>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getFulfillmentWebControllerUpdateDefinitionQueryOptions(id,updateWorkflowDefinitionDto,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}






export type FulfillmentWebController_deleteDefinitionResponse200 = {
  data: FulfillmentWorkflowDefinitionDto
  status: 200
}

export type FulfillmentWebController_deleteDefinitionResponseSuccess = (FulfillmentWebController_deleteDefinitionResponse200) & {
  headers: Headers;
};
;

export type FulfillmentWebController_deleteDefinitionResponse = (FulfillmentWebController_deleteDefinitionResponseSuccess)

export const getFulfillmentWebControllerDeleteDefinitionUrl = (id: string,) => {




  return `/api/v1/wms/web/fulfillment/workflow-definitions/${id}`
}

/**
 * @summary Delete workflow definition
 */
export const FulfillmentWebController_deleteDefinition = async (id: string, options?: RequestInit): Promise<FulfillmentWebController_deleteDefinitionResponse> => {

  return customInstance<FulfillmentWebController_deleteDefinitionResponse>(getFulfillmentWebControllerDeleteDefinitionUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getFulfillmentWebControllerDeleteDefinitionQueryKey = (id: string,) => {
    return [
    'DELETE', `/api/v1/wms/web/fulfillment/workflow-definitions/${id}`
    ] as const;
    }


export const getFulfillmentWebControllerDeleteDefinitionQueryOptions = <TData = Awaited<ReturnType<typeof FulfillmentWebController_deleteDefinition>>, TError = unknown>(id: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof FulfillmentWebController_deleteDefinition>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getFulfillmentWebControllerDeleteDefinitionQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof FulfillmentWebController_deleteDefinition>>> = ({ signal }) => FulfillmentWebController_deleteDefinition(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof FulfillmentWebController_deleteDefinition>>, TError, TData> & { queryKey: QueryKey }
}

export type FulfillmentWebControllerDeleteDefinitionQueryResult = NonNullable<Awaited<ReturnType<typeof FulfillmentWebController_deleteDefinition>>>
export type FulfillmentWebControllerDeleteDefinitionQueryError = unknown


/**
 * @summary Delete workflow definition
 */

export function useFulfillmentWebControllerDeleteDefinition<TData = Awaited<ReturnType<typeof FulfillmentWebController_deleteDefinition>>, TError = unknown>(
 id: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof FulfillmentWebController_deleteDefinition>>, TError, TData>, request?: SecondParameter<typeof customInstance>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getFulfillmentWebControllerDeleteDefinitionQueryOptions(id,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}






export type FulfillmentWebController_findAllExecutionsResponse200 = {
  data: WorkflowExecutionListResponseDto
  status: 200
}

export type FulfillmentWebController_findAllExecutionsResponseSuccess = (FulfillmentWebController_findAllExecutionsResponse200) & {
  headers: Headers;
};
;

export type FulfillmentWebController_findAllExecutionsResponse = (FulfillmentWebController_findAllExecutionsResponseSuccess)

export const getFulfillmentWebControllerFindAllExecutionsUrl = () => {




  return `/api/v1/wms/web/fulfillment/executions`
}

/**
 * @summary List workflow executions
 */
export const FulfillmentWebController_findAllExecutions = async ( options?: RequestInit): Promise<FulfillmentWebController_findAllExecutionsResponse> => {

  return customInstance<FulfillmentWebController_findAllExecutionsResponse>(getFulfillmentWebControllerFindAllExecutionsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getFulfillmentWebControllerFindAllExecutionsMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof FulfillmentWebController_findAllExecutions>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof FulfillmentWebController_findAllExecutions>>, TError,void, TContext> => {

const mutationKey = ['fulfillmentWebControllerFindAllExecutions'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof FulfillmentWebController_findAllExecutions>>, void> = () => {


          return  FulfillmentWebController_findAllExecutions(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type FulfillmentWebControllerFindAllExecutionsMutationResult = NonNullable<Awaited<ReturnType<typeof FulfillmentWebController_findAllExecutions>>>

    export type FulfillmentWebControllerFindAllExecutionsMutationError = unknown

    /**
 * @summary List workflow executions
 */
export const useFulfillmentWebControllerFindAllExecutions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof FulfillmentWebController_findAllExecutions>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof FulfillmentWebController_findAllExecutions>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getFulfillmentWebControllerFindAllExecutionsMutationOptions(options));
    }
    export type FulfillmentWebController_findEventsByExecutionIdResponse200 = {
  data: FulfillmentWorkflowEventDto[]
  status: 200
}

export type FulfillmentWebController_findEventsByExecutionIdResponseSuccess = (FulfillmentWebController_findEventsByExecutionIdResponse200) & {
  headers: Headers;
};
;

export type FulfillmentWebController_findEventsByExecutionIdResponse = (FulfillmentWebController_findEventsByExecutionIdResponseSuccess)

export const getFulfillmentWebControllerFindEventsByExecutionIdUrl = (id: string,) => {




  return `/api/v1/wms/web/workflows/instances/${id}/events`
}

/**
 * @summary Get events by execution ID
 */
export const FulfillmentWebController_findEventsByExecutionId = async (id: string, options?: RequestInit): Promise<FulfillmentWebController_findEventsByExecutionIdResponse> => {

  return customInstance<FulfillmentWebController_findEventsByExecutionIdResponse>(getFulfillmentWebControllerFindEventsByExecutionIdUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getFulfillmentWebControllerFindEventsByExecutionIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof FulfillmentWebController_findEventsByExecutionId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof FulfillmentWebController_findEventsByExecutionId>>, TError,{id: string}, TContext> => {

const mutationKey = ['fulfillmentWebControllerFindEventsByExecutionId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof FulfillmentWebController_findEventsByExecutionId>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  FulfillmentWebController_findEventsByExecutionId(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type FulfillmentWebControllerFindEventsByExecutionIdMutationResult = NonNullable<Awaited<ReturnType<typeof FulfillmentWebController_findEventsByExecutionId>>>

    export type FulfillmentWebControllerFindEventsByExecutionIdMutationError = unknown

    /**
 * @summary Get events by execution ID
 */
export const useFulfillmentWebControllerFindEventsByExecutionId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof FulfillmentWebController_findEventsByExecutionId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof FulfillmentWebController_findEventsByExecutionId>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getFulfillmentWebControllerFindEventsByExecutionIdMutationOptions(options));
    }
    export type FulfillmentWebController_findTransitionsByExecutionIdResponse200 = {
  data: FulfillmentWorkflowTransitionDto[]
  status: 200
}

export type FulfillmentWebController_findTransitionsByExecutionIdResponseSuccess = (FulfillmentWebController_findTransitionsByExecutionIdResponse200) & {
  headers: Headers;
};
;

export type FulfillmentWebController_findTransitionsByExecutionIdResponse = (FulfillmentWebController_findTransitionsByExecutionIdResponseSuccess)

export const getFulfillmentWebControllerFindTransitionsByExecutionIdUrl = (id: string,) => {




  return `/api/v1/wms/web/workflows/instances/${id}/transitions`
}

/**
 * @summary Get transitions by execution ID
 */
export const FulfillmentWebController_findTransitionsByExecutionId = async (id: string, options?: RequestInit): Promise<FulfillmentWebController_findTransitionsByExecutionIdResponse> => {

  return customInstance<FulfillmentWebController_findTransitionsByExecutionIdResponse>(getFulfillmentWebControllerFindTransitionsByExecutionIdUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getFulfillmentWebControllerFindTransitionsByExecutionIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof FulfillmentWebController_findTransitionsByExecutionId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof FulfillmentWebController_findTransitionsByExecutionId>>, TError,{id: string}, TContext> => {

const mutationKey = ['fulfillmentWebControllerFindTransitionsByExecutionId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof FulfillmentWebController_findTransitionsByExecutionId>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  FulfillmentWebController_findTransitionsByExecutionId(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type FulfillmentWebControllerFindTransitionsByExecutionIdMutationResult = NonNullable<Awaited<ReturnType<typeof FulfillmentWebController_findTransitionsByExecutionId>>>

    export type FulfillmentWebControllerFindTransitionsByExecutionIdMutationError = unknown

    /**
 * @summary Get transitions by execution ID
 */
export const useFulfillmentWebControllerFindTransitionsByExecutionId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof FulfillmentWebController_findTransitionsByExecutionId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof FulfillmentWebController_findTransitionsByExecutionId>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getFulfillmentWebControllerFindTransitionsByExecutionIdMutationOptions(options));
    }
    export type FulfillmentWebController_createBillingRunResponse201 = {
  data: FulfillmentBillingRunDto
  status: 201
}

export type FulfillmentWebController_createBillingRunResponseSuccess = (FulfillmentWebController_createBillingRunResponse201) & {
  headers: Headers;
};
;

export type FulfillmentWebController_createBillingRunResponse = (FulfillmentWebController_createBillingRunResponseSuccess)

export const getFulfillmentWebControllerCreateBillingRunUrl = () => {




  return `/api/v1/wms/web/fulfillment-billing/runs`
}

/**
 * @summary Create billing run
 */
export const FulfillmentWebController_createBillingRun = async (createFulfillmentBillingRunDto: CreateFulfillmentBillingRunDto, options?: RequestInit): Promise<FulfillmentWebController_createBillingRunResponse> => {

  return customInstance<FulfillmentWebController_createBillingRunResponse>(getFulfillmentWebControllerCreateBillingRunUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createFulfillmentBillingRunDto)
  }
);}





export const getFulfillmentWebControllerCreateBillingRunQueryKey = (createFulfillmentBillingRunDto?: CreateFulfillmentBillingRunDto,) => {
    return [
    'POST', `/api/v1/wms/web/fulfillment-billing/runs`, createFulfillmentBillingRunDto
    ] as const;
    }


export const getFulfillmentWebControllerCreateBillingRunQueryOptions = <TData = Awaited<ReturnType<typeof FulfillmentWebController_createBillingRun>>, TError = unknown>(createFulfillmentBillingRunDto: CreateFulfillmentBillingRunDto, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof FulfillmentWebController_createBillingRun>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getFulfillmentWebControllerCreateBillingRunQueryKey(createFulfillmentBillingRunDto);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof FulfillmentWebController_createBillingRun>>> = ({ signal }) => FulfillmentWebController_createBillingRun(createFulfillmentBillingRunDto, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof FulfillmentWebController_createBillingRun>>, TError, TData> & { queryKey: QueryKey }
}

export type FulfillmentWebControllerCreateBillingRunQueryResult = NonNullable<Awaited<ReturnType<typeof FulfillmentWebController_createBillingRun>>>
export type FulfillmentWebControllerCreateBillingRunQueryError = unknown


/**
 * @summary Create billing run
 */

export function useFulfillmentWebControllerCreateBillingRun<TData = Awaited<ReturnType<typeof FulfillmentWebController_createBillingRun>>, TError = unknown>(
 createFulfillmentBillingRunDto: CreateFulfillmentBillingRunDto, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof FulfillmentWebController_createBillingRun>>, TError, TData>, request?: SecondParameter<typeof customInstance>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getFulfillmentWebControllerCreateBillingRunQueryOptions(createFulfillmentBillingRunDto,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}






export type FulfillmentWebController_findAllBillingRunsResponse200 = {
  data: BillingRunListResponseDto
  status: 200
}

export type FulfillmentWebController_findAllBillingRunsResponseSuccess = (FulfillmentWebController_findAllBillingRunsResponse200) & {
  headers: Headers;
};
;

export type FulfillmentWebController_findAllBillingRunsResponse = (FulfillmentWebController_findAllBillingRunsResponseSuccess)

export const getFulfillmentWebControllerFindAllBillingRunsUrl = () => {




  return `/api/v1/wms/web/fulfillment-billing/runs`
}

/**
 * @summary List billing runs
 */
export const FulfillmentWebController_findAllBillingRuns = async ( options?: RequestInit): Promise<FulfillmentWebController_findAllBillingRunsResponse> => {

  return customInstance<FulfillmentWebController_findAllBillingRunsResponse>(getFulfillmentWebControllerFindAllBillingRunsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getFulfillmentWebControllerFindAllBillingRunsMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof FulfillmentWebController_findAllBillingRuns>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof FulfillmentWebController_findAllBillingRuns>>, TError,void, TContext> => {

const mutationKey = ['fulfillmentWebControllerFindAllBillingRuns'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof FulfillmentWebController_findAllBillingRuns>>, void> = () => {


          return  FulfillmentWebController_findAllBillingRuns(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type FulfillmentWebControllerFindAllBillingRunsMutationResult = NonNullable<Awaited<ReturnType<typeof FulfillmentWebController_findAllBillingRuns>>>

    export type FulfillmentWebControllerFindAllBillingRunsMutationError = unknown

    /**
 * @summary List billing runs
 */
export const useFulfillmentWebControllerFindAllBillingRuns = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof FulfillmentWebController_findAllBillingRuns>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof FulfillmentWebController_findAllBillingRuns>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getFulfillmentWebControllerFindAllBillingRunsMutationOptions(options));
    }
    export type FulfillmentWebController_findBillingRunByIdResponse200 = {
  data: FulfillmentBillingRunDetailDto
  status: 200
}

export type FulfillmentWebController_findBillingRunByIdResponseSuccess = (FulfillmentWebController_findBillingRunByIdResponse200) & {
  headers: Headers;
};
;

export type FulfillmentWebController_findBillingRunByIdResponse = (FulfillmentWebController_findBillingRunByIdResponseSuccess)

export const getFulfillmentWebControllerFindBillingRunByIdUrl = (id: string,) => {




  return `/api/v1/wms/web/fulfillment-billing/runs/${id}`
}

/**
 * @summary Get billing run by ID
 */
export const FulfillmentWebController_findBillingRunById = async (id: string, options?: RequestInit): Promise<FulfillmentWebController_findBillingRunByIdResponse> => {

  return customInstance<FulfillmentWebController_findBillingRunByIdResponse>(getFulfillmentWebControllerFindBillingRunByIdUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getFulfillmentWebControllerFindBillingRunByIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof FulfillmentWebController_findBillingRunById>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof FulfillmentWebController_findBillingRunById>>, TError,{id: string}, TContext> => {

const mutationKey = ['fulfillmentWebControllerFindBillingRunById'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof FulfillmentWebController_findBillingRunById>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  FulfillmentWebController_findBillingRunById(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type FulfillmentWebControllerFindBillingRunByIdMutationResult = NonNullable<Awaited<ReturnType<typeof FulfillmentWebController_findBillingRunById>>>

    export type FulfillmentWebControllerFindBillingRunByIdMutationError = unknown

    /**
 * @summary Get billing run by ID
 */
export const useFulfillmentWebControllerFindBillingRunById = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof FulfillmentWebController_findBillingRunById>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof FulfillmentWebController_findBillingRunById>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getFulfillmentWebControllerFindBillingRunByIdMutationOptions(options));
    }
    export type FulfillmentWebController_deleteBillingRunResponse200 = {
  data: DeleteResultDto
  status: 200
}

export type FulfillmentWebController_deleteBillingRunResponseSuccess = (FulfillmentWebController_deleteBillingRunResponse200) & {
  headers: Headers;
};
;

export type FulfillmentWebController_deleteBillingRunResponse = (FulfillmentWebController_deleteBillingRunResponseSuccess)

export const getFulfillmentWebControllerDeleteBillingRunUrl = (id: string,) => {




  return `/api/v1/wms/web/fulfillment-billing/runs/${id}`
}

/**
 * @summary Delete billing run
 */
export const FulfillmentWebController_deleteBillingRun = async (id: string, options?: RequestInit): Promise<FulfillmentWebController_deleteBillingRunResponse> => {

  return customInstance<FulfillmentWebController_deleteBillingRunResponse>(getFulfillmentWebControllerDeleteBillingRunUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getFulfillmentWebControllerDeleteBillingRunQueryKey = (id: string,) => {
    return [
    'DELETE', `/api/v1/wms/web/fulfillment-billing/runs/${id}`
    ] as const;
    }


export const getFulfillmentWebControllerDeleteBillingRunQueryOptions = <TData = Awaited<ReturnType<typeof FulfillmentWebController_deleteBillingRun>>, TError = unknown>(id: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof FulfillmentWebController_deleteBillingRun>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getFulfillmentWebControllerDeleteBillingRunQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof FulfillmentWebController_deleteBillingRun>>> = ({ signal }) => FulfillmentWebController_deleteBillingRun(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof FulfillmentWebController_deleteBillingRun>>, TError, TData> & { queryKey: QueryKey }
}

export type FulfillmentWebControllerDeleteBillingRunQueryResult = NonNullable<Awaited<ReturnType<typeof FulfillmentWebController_deleteBillingRun>>>
export type FulfillmentWebControllerDeleteBillingRunQueryError = unknown


/**
 * @summary Delete billing run
 */

export function useFulfillmentWebControllerDeleteBillingRun<TData = Awaited<ReturnType<typeof FulfillmentWebController_deleteBillingRun>>, TError = unknown>(
 id: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof FulfillmentWebController_deleteBillingRun>>, TError, TData>, request?: SecondParameter<typeof customInstance>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getFulfillmentWebControllerDeleteBillingRunQueryOptions(id,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}






export type FulfillmentWebController_linkEventsToRunResponse201 = {
  data: LinkEventsResultDto
  status: 201
}

export type FulfillmentWebController_linkEventsToRunResponseSuccess = (FulfillmentWebController_linkEventsToRunResponse201) & {
  headers: Headers;
};
;

export type FulfillmentWebController_linkEventsToRunResponse = (FulfillmentWebController_linkEventsToRunResponseSuccess)

export const getFulfillmentWebControllerLinkEventsToRunUrl = (id: string,) => {




  return `/api/v1/wms/web/fulfillment-billing/runs/${id}/link-events`
}

/**
 * @summary Link events to billing run
 */
export const FulfillmentWebController_linkEventsToRun = async (id: string, options?: RequestInit): Promise<FulfillmentWebController_linkEventsToRunResponse> => {

  return customInstance<FulfillmentWebController_linkEventsToRunResponse>(getFulfillmentWebControllerLinkEventsToRunUrl(id),
  {
    ...options,
    method: 'POST'


  }
);}





export const getFulfillmentWebControllerLinkEventsToRunQueryKey = (id: string,) => {
    return [
    'POST', `/api/v1/wms/web/fulfillment-billing/runs/${id}/link-events`
    ] as const;
    }


export const getFulfillmentWebControllerLinkEventsToRunQueryOptions = <TData = Awaited<ReturnType<typeof FulfillmentWebController_linkEventsToRun>>, TError = unknown>(id: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof FulfillmentWebController_linkEventsToRun>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getFulfillmentWebControllerLinkEventsToRunQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof FulfillmentWebController_linkEventsToRun>>> = ({ signal }) => FulfillmentWebController_linkEventsToRun(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof FulfillmentWebController_linkEventsToRun>>, TError, TData> & { queryKey: QueryKey }
}

export type FulfillmentWebControllerLinkEventsToRunQueryResult = NonNullable<Awaited<ReturnType<typeof FulfillmentWebController_linkEventsToRun>>>
export type FulfillmentWebControllerLinkEventsToRunQueryError = unknown


/**
 * @summary Link events to billing run
 */

export function useFulfillmentWebControllerLinkEventsToRun<TData = Awaited<ReturnType<typeof FulfillmentWebController_linkEventsToRun>>, TError = unknown>(
 id: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof FulfillmentWebController_linkEventsToRun>>, TError, TData>, request?: SecondParameter<typeof customInstance>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getFulfillmentWebControllerLinkEventsToRunQueryOptions(id,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}






export type FulfillmentWebController_updateBillingRunStatusResponse200 = {
  data: FulfillmentBillingRunDto
  status: 200
}

export type FulfillmentWebController_updateBillingRunStatusResponseSuccess = (FulfillmentWebController_updateBillingRunStatusResponse200) & {
  headers: Headers;
};
;

export type FulfillmentWebController_updateBillingRunStatusResponse = (FulfillmentWebController_updateBillingRunStatusResponseSuccess)

export const getFulfillmentWebControllerUpdateBillingRunStatusUrl = (id: string,) => {




  return `/api/v1/wms/web/fulfillment-billing/runs/${id}/status`
}

/**
 * @summary Update billing run status
 */
export const FulfillmentWebController_updateBillingRunStatus = async (id: string, options?: RequestInit): Promise<FulfillmentWebController_updateBillingRunStatusResponse> => {

  return customInstance<FulfillmentWebController_updateBillingRunStatusResponse>(getFulfillmentWebControllerUpdateBillingRunStatusUrl(id),
  {
    ...options,
    method: 'POST'


  }
);}





export const getFulfillmentWebControllerUpdateBillingRunStatusQueryKey = (id: string,) => {
    return [
    'POST', `/api/v1/wms/web/fulfillment-billing/runs/${id}/status`
    ] as const;
    }


export const getFulfillmentWebControllerUpdateBillingRunStatusQueryOptions = <TData = Awaited<ReturnType<typeof FulfillmentWebController_updateBillingRunStatus>>, TError = unknown>(id: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof FulfillmentWebController_updateBillingRunStatus>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getFulfillmentWebControllerUpdateBillingRunStatusQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof FulfillmentWebController_updateBillingRunStatus>>> = ({ signal }) => FulfillmentWebController_updateBillingRunStatus(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof FulfillmentWebController_updateBillingRunStatus>>, TError, TData> & { queryKey: QueryKey }
}

export type FulfillmentWebControllerUpdateBillingRunStatusQueryResult = NonNullable<Awaited<ReturnType<typeof FulfillmentWebController_updateBillingRunStatus>>>
export type FulfillmentWebControllerUpdateBillingRunStatusQueryError = unknown


/**
 * @summary Update billing run status
 */

export function useFulfillmentWebControllerUpdateBillingRunStatus<TData = Awaited<ReturnType<typeof FulfillmentWebController_updateBillingRunStatus>>, TError = unknown>(
 id: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof FulfillmentWebController_updateBillingRunStatus>>, TError, TData>, request?: SecondParameter<typeof customInstance>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getFulfillmentWebControllerUpdateBillingRunStatusQueryOptions(id,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}






export type FulfillmentWebController_createBillingEventResponse201 = {
  data: FulfillmentBillingEventDto
  status: 201
}

export type FulfillmentWebController_createBillingEventResponseSuccess = (FulfillmentWebController_createBillingEventResponse201) & {
  headers: Headers;
};
;

export type FulfillmentWebController_createBillingEventResponse = (FulfillmentWebController_createBillingEventResponseSuccess)

export const getFulfillmentWebControllerCreateBillingEventUrl = () => {




  return `/api/v1/wms/web/fulfillment-billing/events`
}

/**
 * @summary Create billing event
 */
export const FulfillmentWebController_createBillingEvent = async (createFulfillmentBillingEventDto: CreateFulfillmentBillingEventDto, options?: RequestInit): Promise<FulfillmentWebController_createBillingEventResponse> => {

  return customInstance<FulfillmentWebController_createBillingEventResponse>(getFulfillmentWebControllerCreateBillingEventUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createFulfillmentBillingEventDto)
  }
);}





export const getFulfillmentWebControllerCreateBillingEventQueryKey = (createFulfillmentBillingEventDto?: CreateFulfillmentBillingEventDto,) => {
    return [
    'POST', `/api/v1/wms/web/fulfillment-billing/events`, createFulfillmentBillingEventDto
    ] as const;
    }


export const getFulfillmentWebControllerCreateBillingEventQueryOptions = <TData = Awaited<ReturnType<typeof FulfillmentWebController_createBillingEvent>>, TError = unknown>(createFulfillmentBillingEventDto: CreateFulfillmentBillingEventDto, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof FulfillmentWebController_createBillingEvent>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getFulfillmentWebControllerCreateBillingEventQueryKey(createFulfillmentBillingEventDto);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof FulfillmentWebController_createBillingEvent>>> = ({ signal }) => FulfillmentWebController_createBillingEvent(createFulfillmentBillingEventDto, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof FulfillmentWebController_createBillingEvent>>, TError, TData> & { queryKey: QueryKey }
}

export type FulfillmentWebControllerCreateBillingEventQueryResult = NonNullable<Awaited<ReturnType<typeof FulfillmentWebController_createBillingEvent>>>
export type FulfillmentWebControllerCreateBillingEventQueryError = unknown


/**
 * @summary Create billing event
 */

export function useFulfillmentWebControllerCreateBillingEvent<TData = Awaited<ReturnType<typeof FulfillmentWebController_createBillingEvent>>, TError = unknown>(
 createFulfillmentBillingEventDto: CreateFulfillmentBillingEventDto, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof FulfillmentWebController_createBillingEvent>>, TError, TData>, request?: SecondParameter<typeof customInstance>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getFulfillmentWebControllerCreateBillingEventQueryOptions(createFulfillmentBillingEventDto,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}






export type FulfillmentWebController_findAllBillingEventsResponse200 = {
  data: BillingEventListResponseDto
  status: 200
}

export type FulfillmentWebController_findAllBillingEventsResponseSuccess = (FulfillmentWebController_findAllBillingEventsResponse200) & {
  headers: Headers;
};
;

export type FulfillmentWebController_findAllBillingEventsResponse = (FulfillmentWebController_findAllBillingEventsResponseSuccess)

export const getFulfillmentWebControllerFindAllBillingEventsUrl = () => {




  return `/api/v1/wms/web/fulfillment-billing/events`
}

/**
 * @summary List billing events
 */
export const FulfillmentWebController_findAllBillingEvents = async ( options?: RequestInit): Promise<FulfillmentWebController_findAllBillingEventsResponse> => {

  return customInstance<FulfillmentWebController_findAllBillingEventsResponse>(getFulfillmentWebControllerFindAllBillingEventsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getFulfillmentWebControllerFindAllBillingEventsMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof FulfillmentWebController_findAllBillingEvents>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof FulfillmentWebController_findAllBillingEvents>>, TError,void, TContext> => {

const mutationKey = ['fulfillmentWebControllerFindAllBillingEvents'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof FulfillmentWebController_findAllBillingEvents>>, void> = () => {


          return  FulfillmentWebController_findAllBillingEvents(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type FulfillmentWebControllerFindAllBillingEventsMutationResult = NonNullable<Awaited<ReturnType<typeof FulfillmentWebController_findAllBillingEvents>>>

    export type FulfillmentWebControllerFindAllBillingEventsMutationError = unknown

    /**
 * @summary List billing events
 */
export const useFulfillmentWebControllerFindAllBillingEvents = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof FulfillmentWebController_findAllBillingEvents>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof FulfillmentWebController_findAllBillingEvents>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getFulfillmentWebControllerFindAllBillingEventsMutationOptions(options));
    }
    export type FulfillmentWebController_calculateEventChargesResponse200 = {
  data: FulfillmentBillingAggregationDto
  status: 200
}

export type FulfillmentWebController_calculateEventChargesResponseSuccess = (FulfillmentWebController_calculateEventChargesResponse200) & {
  headers: Headers;
};
;

export type FulfillmentWebController_calculateEventChargesResponse = (FulfillmentWebController_calculateEventChargesResponseSuccess)

export const getFulfillmentWebControllerCalculateEventChargesUrl = () => {




  return `/api/v1/wms/web/fulfillment-billing/events/charges`
}

/**
 * @summary Calculate event charges
 */
export const FulfillmentWebController_calculateEventCharges = async ( options?: RequestInit): Promise<FulfillmentWebController_calculateEventChargesResponse> => {

  return customInstance<FulfillmentWebController_calculateEventChargesResponse>(getFulfillmentWebControllerCalculateEventChargesUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getFulfillmentWebControllerCalculateEventChargesMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof FulfillmentWebController_calculateEventCharges>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof FulfillmentWebController_calculateEventCharges>>, TError,void, TContext> => {

const mutationKey = ['fulfillmentWebControllerCalculateEventCharges'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof FulfillmentWebController_calculateEventCharges>>, void> = () => {


          return  FulfillmentWebController_calculateEventCharges(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type FulfillmentWebControllerCalculateEventChargesMutationResult = NonNullable<Awaited<ReturnType<typeof FulfillmentWebController_calculateEventCharges>>>

    export type FulfillmentWebControllerCalculateEventChargesMutationError = unknown

    /**
 * @summary Calculate event charges
 */
export const useFulfillmentWebControllerCalculateEventCharges = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof FulfillmentWebController_calculateEventCharges>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof FulfillmentWebController_calculateEventCharges>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getFulfillmentWebControllerCalculateEventChargesMutationOptions(options));
    }
