/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * WMS API
 * Warehouse Management System API
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  HealthCheckResponseDto
} from '../../../types/wms-api';

import { customInstance } from '../../../http/httpClient.js';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export type HealthController_checkResponse200 = {
  data: HealthCheckResponseDto
  status: 200
}

export type HealthController_checkResponseSuccess = (HealthController_checkResponse200) & {
  headers: Headers;
};
;

export type HealthController_checkResponse = (HealthController_checkResponseSuccess)

export const getHealthControllerCheckUrl = () => {




  return `/api/v1/wms/health`
}

/**
 * @summary Health check
 */
export const HealthController_check = async ( options?: RequestInit): Promise<HealthController_checkResponse> => {

  return customInstance<HealthController_checkResponse>(getHealthControllerCheckUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getHealthControllerCheckMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof HealthController_check>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof HealthController_check>>, TError,void, TContext> => {

const mutationKey = ['healthControllerCheck'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof HealthController_check>>, void> = () => {


          return  HealthController_check(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type HealthControllerCheckMutationResult = NonNullable<Awaited<ReturnType<typeof HealthController_check>>>

    export type HealthControllerCheckMutationError = unknown

    /**
 * @summary Health check
 */
export const useHealthControllerCheck = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof HealthController_check>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof HealthController_check>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getHealthControllerCheckMutationOptions(options));
    }
