/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * ElasticWMS API
 * Warehouse Management System API - Web, RF, and Integration endpoints
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  EvaluateRuleDto,
  ExecuteTransitionDto,
  ExecutionControllerListParams,
  StartProcessDto,
  UpsertBpmnProcessDto,
  UpsertRuleDto,
  UpsertStateMachineDto,
  WmsStateMachineControllerListParams
} from '../../../types/wms-api';

import { customInstance } from '../../../http/httpClient';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export type SystemSettingController_listResponse200 = {
  data: void
  status: 200
}

export type SystemSettingController_listResponseSuccess = (SystemSettingController_listResponse200) & {
  headers: Headers;
};
;

export type SystemSettingController_listResponse = (SystemSettingController_listResponseSuccess)

export const getSystemSettingControllerListUrl = () => {




  return `/api/v1/wms/web/settings`
}

export const SystemSettingController_list = async ( options?: RequestInit): Promise<SystemSettingController_listResponse> => {

  return customInstance<SystemSettingController_listResponse>(getSystemSettingControllerListUrl(),
  {
    ...options,
    method: 'GET'


  }
);}




export const getSystemSettingControllerListMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof SystemSettingController_list>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof SystemSettingController_list>>, TError,void, TContext> => {

const mutationKey = ['systemSettingControllerList'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof SystemSettingController_list>>, void> = () => {


          return  SystemSettingController_list(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type SystemSettingControllerListMutationResult = NonNullable<Awaited<ReturnType<typeof SystemSettingController_list>>>

    export type SystemSettingControllerListMutationError = unknown

    export const useSystemSettingControllerList = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof SystemSettingController_list>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof SystemSettingController_list>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getSystemSettingControllerListMutationOptions(options));
    }
    export type SystemSettingController_getResponse200 = {
  data: void
  status: 200
}

export type SystemSettingController_getResponseSuccess = (SystemSettingController_getResponse200) & {
  headers: Headers;
};
;

export type SystemSettingController_getResponse = (SystemSettingController_getResponseSuccess)

export const getSystemSettingControllerGetUrl = (key: string,) => {




  return `/api/v1/wms/web/settings/${key}`
}

export const SystemSettingController_get = async (key: string, options?: RequestInit): Promise<SystemSettingController_getResponse> => {

  return customInstance<SystemSettingController_getResponse>(getSystemSettingControllerGetUrl(key),
  {
    ...options,
    method: 'GET'


  }
);}




export const getSystemSettingControllerGetMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof SystemSettingController_get>>, TError,{key: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof SystemSettingController_get>>, TError,{key: string}, TContext> => {

const mutationKey = ['systemSettingControllerGet'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof SystemSettingController_get>>, {key: string}> = (props) => {
          const {key} = props ?? {};

          return  SystemSettingController_get(key,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type SystemSettingControllerGetMutationResult = NonNullable<Awaited<ReturnType<typeof SystemSettingController_get>>>

    export type SystemSettingControllerGetMutationError = unknown

    export const useSystemSettingControllerGet = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof SystemSettingController_get>>, TError,{key: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof SystemSettingController_get>>,
        TError,
        {key: string},
        TContext
      > => {
      return useMutation(getSystemSettingControllerGetMutationOptions(options));
    }
    export type SystemSettingController_upsertResponse201 = {
  data: void
  status: 201
}

export type SystemSettingController_upsertResponseSuccess = (SystemSettingController_upsertResponse201) & {
  headers: Headers;
};
;

export type SystemSettingController_upsertResponse = (SystemSettingController_upsertResponseSuccess)

export const getSystemSettingControllerUpsertUrl = (key: string,) => {




  return `/api/v1/wms/web/settings/${key}`
}

export const SystemSettingController_upsert = async (key: string, options?: RequestInit): Promise<SystemSettingController_upsertResponse> => {

  return customInstance<SystemSettingController_upsertResponse>(getSystemSettingControllerUpsertUrl(key),
  {
    ...options,
    method: 'POST'


  }
);}





export const getSystemSettingControllerUpsertQueryKey = (key: string,) => {
    return [
    'POST', `/api/v1/wms/web/settings/${key}`
    ] as const;
    }


export const getSystemSettingControllerUpsertQueryOptions = <TData = Awaited<ReturnType<typeof SystemSettingController_upsert>>, TError = unknown>(key: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof SystemSettingController_upsert>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSystemSettingControllerUpsertQueryKey(key);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof SystemSettingController_upsert>>> = ({ signal }) => SystemSettingController_upsert(key, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: key !== null && key !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof SystemSettingController_upsert>>, TError, TData> & { queryKey: QueryKey }
}

export type SystemSettingControllerUpsertQueryResult = NonNullable<Awaited<ReturnType<typeof SystemSettingController_upsert>>>
export type SystemSettingControllerUpsertQueryError = unknown



export function useSystemSettingControllerUpsert<TData = Awaited<ReturnType<typeof SystemSettingController_upsert>>, TError = unknown>(
 key: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof SystemSettingController_upsert>>, TError, TData>, request?: SecondParameter<typeof customInstance>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getSystemSettingControllerUpsertQueryOptions(key,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type SystemSettingController_deleteResponse200 = {
  data: void
  status: 200
}

export type SystemSettingController_deleteResponseSuccess = (SystemSettingController_deleteResponse200) & {
  headers: Headers;
};
;

export type SystemSettingController_deleteResponse = (SystemSettingController_deleteResponseSuccess)

export const getSystemSettingControllerDeleteUrl = (key: string,) => {




  return `/api/v1/wms/web/settings/${key}`
}

export const SystemSettingController_delete = async (key: string, options?: RequestInit): Promise<SystemSettingController_deleteResponse> => {

  return customInstance<SystemSettingController_deleteResponse>(getSystemSettingControllerDeleteUrl(key),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getSystemSettingControllerDeleteQueryKey = (key: string,) => {
    return [
    'DELETE', `/api/v1/wms/web/settings/${key}`
    ] as const;
    }


export const getSystemSettingControllerDeleteQueryOptions = <TData = Awaited<ReturnType<typeof SystemSettingController_delete>>, TError = unknown>(key: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof SystemSettingController_delete>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSystemSettingControllerDeleteQueryKey(key);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof SystemSettingController_delete>>> = ({ signal }) => SystemSettingController_delete(key, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: key !== null && key !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof SystemSettingController_delete>>, TError, TData> & { queryKey: QueryKey }
}

export type SystemSettingControllerDeleteQueryResult = NonNullable<Awaited<ReturnType<typeof SystemSettingController_delete>>>
export type SystemSettingControllerDeleteQueryError = unknown



export function useSystemSettingControllerDelete<TData = Awaited<ReturnType<typeof SystemSettingController_delete>>, TError = unknown>(
 key: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof SystemSettingController_delete>>, TError, TData>, request?: SecondParameter<typeof customInstance>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getSystemSettingControllerDeleteQueryOptions(key,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type WmsStateMachineController_listResponse200 = {
  data: void
  status: 200
}

export type WmsStateMachineController_listResponseSuccess = (WmsStateMachineController_listResponse200) & {
  headers: Headers;
};
;

export type WmsStateMachineController_listResponse = (WmsStateMachineController_listResponseSuccess)

export const getWmsStateMachineControllerListUrl = (params: WmsStateMachineControllerListParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/wms/web/customization/state-machines?${stringifiedParams}` : `/api/v1/wms/web/customization/state-machines`
}

export const WmsStateMachineController_list = async (params: WmsStateMachineControllerListParams, options?: RequestInit): Promise<WmsStateMachineController_listResponse> => {

  return customInstance<WmsStateMachineController_listResponse>(getWmsStateMachineControllerListUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}




export const getWmsStateMachineControllerListMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof WmsStateMachineController_list>>, TError,{params: WmsStateMachineControllerListParams}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof WmsStateMachineController_list>>, TError,{params: WmsStateMachineControllerListParams}, TContext> => {

const mutationKey = ['wmsStateMachineControllerList'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof WmsStateMachineController_list>>, {params: WmsStateMachineControllerListParams}> = (props) => {
          const {params} = props ?? {};

          return  WmsStateMachineController_list(params,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type WmsStateMachineControllerListMutationResult = NonNullable<Awaited<ReturnType<typeof WmsStateMachineController_list>>>

    export type WmsStateMachineControllerListMutationError = unknown

    export const useWmsStateMachineControllerList = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof WmsStateMachineController_list>>, TError,{params: WmsStateMachineControllerListParams}, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof WmsStateMachineController_list>>,
        TError,
        {params: WmsStateMachineControllerListParams},
        TContext
      > => {
      return useMutation(getWmsStateMachineControllerListMutationOptions(options));
    }
    export type WmsStateMachineController_createResponse201 = {
  data: void
  status: 201
}

export type WmsStateMachineController_createResponseSuccess = (WmsStateMachineController_createResponse201) & {
  headers: Headers;
};
;

export type WmsStateMachineController_createResponse = (WmsStateMachineController_createResponseSuccess)

export const getWmsStateMachineControllerCreateUrl = () => {




  return `/api/v1/wms/web/customization/state-machines`
}

export const WmsStateMachineController_create = async (upsertStateMachineDto: UpsertStateMachineDto, options?: RequestInit): Promise<WmsStateMachineController_createResponse> => {

  return customInstance<WmsStateMachineController_createResponse>(getWmsStateMachineControllerCreateUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(upsertStateMachineDto)
  }
);}





export const getWmsStateMachineControllerCreateQueryKey = (upsertStateMachineDto?: UpsertStateMachineDto,) => {
    return [
    'POST', `/api/v1/wms/web/customization/state-machines`, upsertStateMachineDto
    ] as const;
    }


export const getWmsStateMachineControllerCreateQueryOptions = <TData = Awaited<ReturnType<typeof WmsStateMachineController_create>>, TError = unknown>(upsertStateMachineDto: UpsertStateMachineDto, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof WmsStateMachineController_create>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getWmsStateMachineControllerCreateQueryKey(upsertStateMachineDto);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof WmsStateMachineController_create>>> = ({ signal }) => WmsStateMachineController_create(upsertStateMachineDto, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof WmsStateMachineController_create>>, TError, TData> & { queryKey: QueryKey }
}

export type WmsStateMachineControllerCreateQueryResult = NonNullable<Awaited<ReturnType<typeof WmsStateMachineController_create>>>
export type WmsStateMachineControllerCreateQueryError = unknown



export function useWmsStateMachineControllerCreate<TData = Awaited<ReturnType<typeof WmsStateMachineController_create>>, TError = unknown>(
 upsertStateMachineDto: UpsertStateMachineDto, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof WmsStateMachineController_create>>, TError, TData>, request?: SecondParameter<typeof customInstance>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getWmsStateMachineControllerCreateQueryOptions(upsertStateMachineDto,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type WmsStateMachineController_getResponse200 = {
  data: void
  status: 200
}

export type WmsStateMachineController_getResponseSuccess = (WmsStateMachineController_getResponse200) & {
  headers: Headers;
};
;

export type WmsStateMachineController_getResponse = (WmsStateMachineController_getResponseSuccess)

export const getWmsStateMachineControllerGetUrl = (key: string,) => {




  return `/api/v1/wms/web/customization/state-machines/${key}`
}

export const WmsStateMachineController_get = async (key: string, options?: RequestInit): Promise<WmsStateMachineController_getResponse> => {

  return customInstance<WmsStateMachineController_getResponse>(getWmsStateMachineControllerGetUrl(key),
  {
    ...options,
    method: 'GET'


  }
);}




export const getWmsStateMachineControllerGetMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof WmsStateMachineController_get>>, TError,{key: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof WmsStateMachineController_get>>, TError,{key: string}, TContext> => {

const mutationKey = ['wmsStateMachineControllerGet'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof WmsStateMachineController_get>>, {key: string}> = (props) => {
          const {key} = props ?? {};

          return  WmsStateMachineController_get(key,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type WmsStateMachineControllerGetMutationResult = NonNullable<Awaited<ReturnType<typeof WmsStateMachineController_get>>>

    export type WmsStateMachineControllerGetMutationError = unknown

    export const useWmsStateMachineControllerGet = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof WmsStateMachineController_get>>, TError,{key: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof WmsStateMachineController_get>>,
        TError,
        {key: string},
        TContext
      > => {
      return useMutation(getWmsStateMachineControllerGetMutationOptions(options));
    }
    export type WmsStateMachineController_updateResponse200 = {
  data: void
  status: 200
}

export type WmsStateMachineController_updateResponseSuccess = (WmsStateMachineController_updateResponse200) & {
  headers: Headers;
};
;

export type WmsStateMachineController_updateResponse = (WmsStateMachineController_updateResponseSuccess)

export const getWmsStateMachineControllerUpdateUrl = (key: string,) => {




  return `/api/v1/wms/web/customization/state-machines/${key}`
}

export const WmsStateMachineController_update = async (key: string, options?: RequestInit): Promise<WmsStateMachineController_updateResponse> => {

  return customInstance<WmsStateMachineController_updateResponse>(getWmsStateMachineControllerUpdateUrl(key),
  {
    ...options,
    method: 'PATCH'


  }
);}





export const getWmsStateMachineControllerUpdateQueryKey = (key: string,) => {
    return [
    'PATCH', `/api/v1/wms/web/customization/state-machines/${key}`
    ] as const;
    }


export const getWmsStateMachineControllerUpdateQueryOptions = <TData = Awaited<ReturnType<typeof WmsStateMachineController_update>>, TError = unknown>(key: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof WmsStateMachineController_update>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getWmsStateMachineControllerUpdateQueryKey(key);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof WmsStateMachineController_update>>> = ({ signal }) => WmsStateMachineController_update(key, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: key !== null && key !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof WmsStateMachineController_update>>, TError, TData> & { queryKey: QueryKey }
}

export type WmsStateMachineControllerUpdateQueryResult = NonNullable<Awaited<ReturnType<typeof WmsStateMachineController_update>>>
export type WmsStateMachineControllerUpdateQueryError = unknown



export function useWmsStateMachineControllerUpdate<TData = Awaited<ReturnType<typeof WmsStateMachineController_update>>, TError = unknown>(
 key: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof WmsStateMachineController_update>>, TError, TData>, request?: SecondParameter<typeof customInstance>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getWmsStateMachineControllerUpdateQueryOptions(key,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type WmsStateMachineController_validateResponse201 = {
  data: void
  status: 201
}

export type WmsStateMachineController_validateResponseSuccess = (WmsStateMachineController_validateResponse201) & {
  headers: Headers;
};
;

export type WmsStateMachineController_validateResponse = (WmsStateMachineController_validateResponseSuccess)

export const getWmsStateMachineControllerValidateUrl = (key: string,) => {




  return `/api/v1/wms/web/customization/state-machines/${key}/validate`
}

export const WmsStateMachineController_validate = async (key: string, options?: RequestInit): Promise<WmsStateMachineController_validateResponse> => {

  return customInstance<WmsStateMachineController_validateResponse>(getWmsStateMachineControllerValidateUrl(key),
  {
    ...options,
    method: 'POST'


  }
);}





export const getWmsStateMachineControllerValidateQueryKey = (key: string,) => {
    return [
    'POST', `/api/v1/wms/web/customization/state-machines/${key}/validate`
    ] as const;
    }


export const getWmsStateMachineControllerValidateQueryOptions = <TData = Awaited<ReturnType<typeof WmsStateMachineController_validate>>, TError = unknown>(key: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof WmsStateMachineController_validate>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getWmsStateMachineControllerValidateQueryKey(key);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof WmsStateMachineController_validate>>> = ({ signal }) => WmsStateMachineController_validate(key, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: key !== null && key !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof WmsStateMachineController_validate>>, TError, TData> & { queryKey: QueryKey }
}

export type WmsStateMachineControllerValidateQueryResult = NonNullable<Awaited<ReturnType<typeof WmsStateMachineController_validate>>>
export type WmsStateMachineControllerValidateQueryError = unknown



export function useWmsStateMachineControllerValidate<TData = Awaited<ReturnType<typeof WmsStateMachineController_validate>>, TError = unknown>(
 key: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof WmsStateMachineController_validate>>, TError, TData>, request?: SecondParameter<typeof customInstance>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getWmsStateMachineControllerValidateQueryOptions(key,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type WmsStateMachineController_testTransitionResponse201 = {
  data: void
  status: 201
}

export type WmsStateMachineController_testTransitionResponseSuccess = (WmsStateMachineController_testTransitionResponse201) & {
  headers: Headers;
};
;

export type WmsStateMachineController_testTransitionResponse = (WmsStateMachineController_testTransitionResponseSuccess)

export const getWmsStateMachineControllerTestTransitionUrl = (key: string,) => {




  return `/api/v1/wms/web/customization/state-machines/${key}/test`
}

export const WmsStateMachineController_testTransition = async (key: string,
    executeTransitionDto: ExecuteTransitionDto, options?: RequestInit): Promise<WmsStateMachineController_testTransitionResponse> => {

  return customInstance<WmsStateMachineController_testTransitionResponse>(getWmsStateMachineControllerTestTransitionUrl(key),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(executeTransitionDto)
  }
);}





export const getWmsStateMachineControllerTestTransitionQueryKey = (key: string,
    executeTransitionDto?: ExecuteTransitionDto,) => {
    return [
    'POST', `/api/v1/wms/web/customization/state-machines/${key}/test`, executeTransitionDto
    ] as const;
    }


export const getWmsStateMachineControllerTestTransitionQueryOptions = <TData = Awaited<ReturnType<typeof WmsStateMachineController_testTransition>>, TError = unknown>(key: string,
    executeTransitionDto: ExecuteTransitionDto, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof WmsStateMachineController_testTransition>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getWmsStateMachineControllerTestTransitionQueryKey(key,executeTransitionDto);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof WmsStateMachineController_testTransition>>> = ({ signal }) => WmsStateMachineController_testTransition(key,executeTransitionDto, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: key !== null && key !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof WmsStateMachineController_testTransition>>, TError, TData> & { queryKey: QueryKey }
}

export type WmsStateMachineControllerTestTransitionQueryResult = NonNullable<Awaited<ReturnType<typeof WmsStateMachineController_testTransition>>>
export type WmsStateMachineControllerTestTransitionQueryError = unknown



export function useWmsStateMachineControllerTestTransition<TData = Awaited<ReturnType<typeof WmsStateMachineController_testTransition>>, TError = unknown>(
 key: string,
    executeTransitionDto: ExecuteTransitionDto, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof WmsStateMachineController_testTransition>>, TError, TData>, request?: SecondParameter<typeof customInstance>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getWmsStateMachineControllerTestTransitionQueryOptions(key,executeTransitionDto,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type WmsStateMachineController_rollbackResponse201 = {
  data: void
  status: 201
}

export type WmsStateMachineController_rollbackResponseSuccess = (WmsStateMachineController_rollbackResponse201) & {
  headers: Headers;
};
;

export type WmsStateMachineController_rollbackResponse = (WmsStateMachineController_rollbackResponseSuccess)

export const getWmsStateMachineControllerRollbackUrl = (key: string,
    version: string,) => {




  return `/api/v1/wms/web/customization/state-machines/${key}/rollback/${version}`
}

export const WmsStateMachineController_rollback = async (key: string,
    version: string, options?: RequestInit): Promise<WmsStateMachineController_rollbackResponse> => {

  return customInstance<WmsStateMachineController_rollbackResponse>(getWmsStateMachineControllerRollbackUrl(key,version),
  {
    ...options,
    method: 'POST'


  }
);}





export const getWmsStateMachineControllerRollbackQueryKey = (key: string,
    version: string,) => {
    return [
    'POST', `/api/v1/wms/web/customization/state-machines/${key}/rollback/${version}`
    ] as const;
    }


export const getWmsStateMachineControllerRollbackQueryOptions = <TData = Awaited<ReturnType<typeof WmsStateMachineController_rollback>>, TError = unknown>(key: string,
    version: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof WmsStateMachineController_rollback>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getWmsStateMachineControllerRollbackQueryKey(key,version);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof WmsStateMachineController_rollback>>> = ({ signal }) => WmsStateMachineController_rollback(key,version, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: key !== null && key !== undefined && version !== null && version !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof WmsStateMachineController_rollback>>, TError, TData> & { queryKey: QueryKey }
}

export type WmsStateMachineControllerRollbackQueryResult = NonNullable<Awaited<ReturnType<typeof WmsStateMachineController_rollback>>>
export type WmsStateMachineControllerRollbackQueryError = unknown



export function useWmsStateMachineControllerRollback<TData = Awaited<ReturnType<typeof WmsStateMachineController_rollback>>, TError = unknown>(
 key: string,
    version: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof WmsStateMachineController_rollback>>, TError, TData>, request?: SecondParameter<typeof customInstance>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getWmsStateMachineControllerRollbackQueryOptions(key,version,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type WmsRuleController_listResponse200 = {
  data: void
  status: 200
}

export type WmsRuleController_listResponseSuccess = (WmsRuleController_listResponse200) & {
  headers: Headers;
};
;

export type WmsRuleController_listResponse = (WmsRuleController_listResponseSuccess)

export const getWmsRuleControllerListUrl = () => {




  return `/api/v1/wms/web/customization/rules`
}

export const WmsRuleController_list = async ( options?: RequestInit): Promise<WmsRuleController_listResponse> => {

  return customInstance<WmsRuleController_listResponse>(getWmsRuleControllerListUrl(),
  {
    ...options,
    method: 'GET'


  }
);}




export const getWmsRuleControllerListMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof WmsRuleController_list>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof WmsRuleController_list>>, TError,void, TContext> => {

const mutationKey = ['wmsRuleControllerList'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof WmsRuleController_list>>, void> = () => {


          return  WmsRuleController_list(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type WmsRuleControllerListMutationResult = NonNullable<Awaited<ReturnType<typeof WmsRuleController_list>>>

    export type WmsRuleControllerListMutationError = unknown

    export const useWmsRuleControllerList = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof WmsRuleController_list>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof WmsRuleController_list>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getWmsRuleControllerListMutationOptions(options));
    }
    export type WmsRuleController_createResponse201 = {
  data: void
  status: 201
}

export type WmsRuleController_createResponseSuccess = (WmsRuleController_createResponse201) & {
  headers: Headers;
};
;

export type WmsRuleController_createResponse = (WmsRuleController_createResponseSuccess)

export const getWmsRuleControllerCreateUrl = () => {




  return `/api/v1/wms/web/customization/rules`
}

export const WmsRuleController_create = async (upsertRuleDto: UpsertRuleDto, options?: RequestInit): Promise<WmsRuleController_createResponse> => {

  return customInstance<WmsRuleController_createResponse>(getWmsRuleControllerCreateUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(upsertRuleDto)
  }
);}





export const getWmsRuleControllerCreateQueryKey = (upsertRuleDto?: UpsertRuleDto,) => {
    return [
    'POST', `/api/v1/wms/web/customization/rules`, upsertRuleDto
    ] as const;
    }


export const getWmsRuleControllerCreateQueryOptions = <TData = Awaited<ReturnType<typeof WmsRuleController_create>>, TError = unknown>(upsertRuleDto: UpsertRuleDto, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof WmsRuleController_create>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getWmsRuleControllerCreateQueryKey(upsertRuleDto);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof WmsRuleController_create>>> = ({ signal }) => WmsRuleController_create(upsertRuleDto, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof WmsRuleController_create>>, TError, TData> & { queryKey: QueryKey }
}

export type WmsRuleControllerCreateQueryResult = NonNullable<Awaited<ReturnType<typeof WmsRuleController_create>>>
export type WmsRuleControllerCreateQueryError = unknown



export function useWmsRuleControllerCreate<TData = Awaited<ReturnType<typeof WmsRuleController_create>>, TError = unknown>(
 upsertRuleDto: UpsertRuleDto, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof WmsRuleController_create>>, TError, TData>, request?: SecondParameter<typeof customInstance>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getWmsRuleControllerCreateQueryOptions(upsertRuleDto,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type WmsRuleController_getResponse200 = {
  data: void
  status: 200
}

export type WmsRuleController_getResponseSuccess = (WmsRuleController_getResponse200) & {
  headers: Headers;
};
;

export type WmsRuleController_getResponse = (WmsRuleController_getResponseSuccess)

export const getWmsRuleControllerGetUrl = (key: string,) => {




  return `/api/v1/wms/web/customization/rules/${key}`
}

export const WmsRuleController_get = async (key: string, options?: RequestInit): Promise<WmsRuleController_getResponse> => {

  return customInstance<WmsRuleController_getResponse>(getWmsRuleControllerGetUrl(key),
  {
    ...options,
    method: 'GET'


  }
);}




export const getWmsRuleControllerGetMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof WmsRuleController_get>>, TError,{key: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof WmsRuleController_get>>, TError,{key: string}, TContext> => {

const mutationKey = ['wmsRuleControllerGet'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof WmsRuleController_get>>, {key: string}> = (props) => {
          const {key} = props ?? {};

          return  WmsRuleController_get(key,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type WmsRuleControllerGetMutationResult = NonNullable<Awaited<ReturnType<typeof WmsRuleController_get>>>

    export type WmsRuleControllerGetMutationError = unknown

    export const useWmsRuleControllerGet = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof WmsRuleController_get>>, TError,{key: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof WmsRuleController_get>>,
        TError,
        {key: string},
        TContext
      > => {
      return useMutation(getWmsRuleControllerGetMutationOptions(options));
    }
    export type WmsRuleController_updateResponse200 = {
  data: void
  status: 200
}

export type WmsRuleController_updateResponseSuccess = (WmsRuleController_updateResponse200) & {
  headers: Headers;
};
;

export type WmsRuleController_updateResponse = (WmsRuleController_updateResponseSuccess)

export const getWmsRuleControllerUpdateUrl = (key: string,) => {




  return `/api/v1/wms/web/customization/rules/${key}`
}

export const WmsRuleController_update = async (key: string, options?: RequestInit): Promise<WmsRuleController_updateResponse> => {

  return customInstance<WmsRuleController_updateResponse>(getWmsRuleControllerUpdateUrl(key),
  {
    ...options,
    method: 'PATCH'


  }
);}





export const getWmsRuleControllerUpdateQueryKey = (key: string,) => {
    return [
    'PATCH', `/api/v1/wms/web/customization/rules/${key}`
    ] as const;
    }


export const getWmsRuleControllerUpdateQueryOptions = <TData = Awaited<ReturnType<typeof WmsRuleController_update>>, TError = unknown>(key: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof WmsRuleController_update>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getWmsRuleControllerUpdateQueryKey(key);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof WmsRuleController_update>>> = ({ signal }) => WmsRuleController_update(key, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: key !== null && key !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof WmsRuleController_update>>, TError, TData> & { queryKey: QueryKey }
}

export type WmsRuleControllerUpdateQueryResult = NonNullable<Awaited<ReturnType<typeof WmsRuleController_update>>>
export type WmsRuleControllerUpdateQueryError = unknown



export function useWmsRuleControllerUpdate<TData = Awaited<ReturnType<typeof WmsRuleController_update>>, TError = unknown>(
 key: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof WmsRuleController_update>>, TError, TData>, request?: SecondParameter<typeof customInstance>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getWmsRuleControllerUpdateQueryOptions(key,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type WmsRuleController_evaluateResponse201 = {
  data: void
  status: 201
}

export type WmsRuleController_evaluateResponseSuccess = (WmsRuleController_evaluateResponse201) & {
  headers: Headers;
};
;

export type WmsRuleController_evaluateResponse = (WmsRuleController_evaluateResponseSuccess)

export const getWmsRuleControllerEvaluateUrl = (key: string,) => {




  return `/api/v1/wms/web/customization/rules/${key}/evaluate`
}

export const WmsRuleController_evaluate = async (key: string,
    evaluateRuleDto: EvaluateRuleDto, options?: RequestInit): Promise<WmsRuleController_evaluateResponse> => {

  return customInstance<WmsRuleController_evaluateResponse>(getWmsRuleControllerEvaluateUrl(key),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(evaluateRuleDto)
  }
);}





export const getWmsRuleControllerEvaluateQueryKey = (key: string,
    evaluateRuleDto?: EvaluateRuleDto,) => {
    return [
    'POST', `/api/v1/wms/web/customization/rules/${key}/evaluate`, evaluateRuleDto
    ] as const;
    }


export const getWmsRuleControllerEvaluateQueryOptions = <TData = Awaited<ReturnType<typeof WmsRuleController_evaluate>>, TError = unknown>(key: string,
    evaluateRuleDto: EvaluateRuleDto, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof WmsRuleController_evaluate>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getWmsRuleControllerEvaluateQueryKey(key,evaluateRuleDto);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof WmsRuleController_evaluate>>> = ({ signal }) => WmsRuleController_evaluate(key,evaluateRuleDto, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: key !== null && key !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof WmsRuleController_evaluate>>, TError, TData> & { queryKey: QueryKey }
}

export type WmsRuleControllerEvaluateQueryResult = NonNullable<Awaited<ReturnType<typeof WmsRuleController_evaluate>>>
export type WmsRuleControllerEvaluateQueryError = unknown



export function useWmsRuleControllerEvaluate<TData = Awaited<ReturnType<typeof WmsRuleController_evaluate>>, TError = unknown>(
 key: string,
    evaluateRuleDto: EvaluateRuleDto, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof WmsRuleController_evaluate>>, TError, TData>, request?: SecondParameter<typeof customInstance>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getWmsRuleControllerEvaluateQueryOptions(key,evaluateRuleDto,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type WmsRuleController_rollbackResponse201 = {
  data: void
  status: 201
}

export type WmsRuleController_rollbackResponseSuccess = (WmsRuleController_rollbackResponse201) & {
  headers: Headers;
};
;

export type WmsRuleController_rollbackResponse = (WmsRuleController_rollbackResponseSuccess)

export const getWmsRuleControllerRollbackUrl = (key: string,
    version: string,) => {




  return `/api/v1/wms/web/customization/rules/${key}/rollback/${version}`
}

export const WmsRuleController_rollback = async (key: string,
    version: string, options?: RequestInit): Promise<WmsRuleController_rollbackResponse> => {

  return customInstance<WmsRuleController_rollbackResponse>(getWmsRuleControllerRollbackUrl(key,version),
  {
    ...options,
    method: 'POST'


  }
);}





export const getWmsRuleControllerRollbackQueryKey = (key: string,
    version: string,) => {
    return [
    'POST', `/api/v1/wms/web/customization/rules/${key}/rollback/${version}`
    ] as const;
    }


export const getWmsRuleControllerRollbackQueryOptions = <TData = Awaited<ReturnType<typeof WmsRuleController_rollback>>, TError = unknown>(key: string,
    version: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof WmsRuleController_rollback>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getWmsRuleControllerRollbackQueryKey(key,version);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof WmsRuleController_rollback>>> = ({ signal }) => WmsRuleController_rollback(key,version, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: key !== null && key !== undefined && version !== null && version !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof WmsRuleController_rollback>>, TError, TData> & { queryKey: QueryKey }
}

export type WmsRuleControllerRollbackQueryResult = NonNullable<Awaited<ReturnType<typeof WmsRuleController_rollback>>>
export type WmsRuleControllerRollbackQueryError = unknown



export function useWmsRuleControllerRollback<TData = Awaited<ReturnType<typeof WmsRuleController_rollback>>, TError = unknown>(
 key: string,
    version: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof WmsRuleController_rollback>>, TError, TData>, request?: SecondParameter<typeof customInstance>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getWmsRuleControllerRollbackQueryOptions(key,version,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type WmsBpmnController_listResponse200 = {
  data: void
  status: 200
}

export type WmsBpmnController_listResponseSuccess = (WmsBpmnController_listResponse200) & {
  headers: Headers;
};
;

export type WmsBpmnController_listResponse = (WmsBpmnController_listResponseSuccess)

export const getWmsBpmnControllerListUrl = () => {




  return `/api/v1/wms/web/customization/processes`
}

export const WmsBpmnController_list = async ( options?: RequestInit): Promise<WmsBpmnController_listResponse> => {

  return customInstance<WmsBpmnController_listResponse>(getWmsBpmnControllerListUrl(),
  {
    ...options,
    method: 'GET'


  }
);}




export const getWmsBpmnControllerListMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof WmsBpmnController_list>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof WmsBpmnController_list>>, TError,void, TContext> => {

const mutationKey = ['wmsBpmnControllerList'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof WmsBpmnController_list>>, void> = () => {


          return  WmsBpmnController_list(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type WmsBpmnControllerListMutationResult = NonNullable<Awaited<ReturnType<typeof WmsBpmnController_list>>>

    export type WmsBpmnControllerListMutationError = unknown

    export const useWmsBpmnControllerList = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof WmsBpmnController_list>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof WmsBpmnController_list>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getWmsBpmnControllerListMutationOptions(options));
    }
    export type WmsBpmnController_createResponse201 = {
  data: void
  status: 201
}

export type WmsBpmnController_createResponseSuccess = (WmsBpmnController_createResponse201) & {
  headers: Headers;
};
;

export type WmsBpmnController_createResponse = (WmsBpmnController_createResponseSuccess)

export const getWmsBpmnControllerCreateUrl = () => {




  return `/api/v1/wms/web/customization/processes`
}

export const WmsBpmnController_create = async (upsertBpmnProcessDto: UpsertBpmnProcessDto, options?: RequestInit): Promise<WmsBpmnController_createResponse> => {

  return customInstance<WmsBpmnController_createResponse>(getWmsBpmnControllerCreateUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(upsertBpmnProcessDto)
  }
);}





export const getWmsBpmnControllerCreateQueryKey = (upsertBpmnProcessDto?: UpsertBpmnProcessDto,) => {
    return [
    'POST', `/api/v1/wms/web/customization/processes`, upsertBpmnProcessDto
    ] as const;
    }


export const getWmsBpmnControllerCreateQueryOptions = <TData = Awaited<ReturnType<typeof WmsBpmnController_create>>, TError = unknown>(upsertBpmnProcessDto: UpsertBpmnProcessDto, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof WmsBpmnController_create>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getWmsBpmnControllerCreateQueryKey(upsertBpmnProcessDto);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof WmsBpmnController_create>>> = ({ signal }) => WmsBpmnController_create(upsertBpmnProcessDto, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof WmsBpmnController_create>>, TError, TData> & { queryKey: QueryKey }
}

export type WmsBpmnControllerCreateQueryResult = NonNullable<Awaited<ReturnType<typeof WmsBpmnController_create>>>
export type WmsBpmnControllerCreateQueryError = unknown



export function useWmsBpmnControllerCreate<TData = Awaited<ReturnType<typeof WmsBpmnController_create>>, TError = unknown>(
 upsertBpmnProcessDto: UpsertBpmnProcessDto, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof WmsBpmnController_create>>, TError, TData>, request?: SecondParameter<typeof customInstance>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getWmsBpmnControllerCreateQueryOptions(upsertBpmnProcessDto,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type WmsBpmnController_getResponse200 = {
  data: void
  status: 200
}

export type WmsBpmnController_getResponseSuccess = (WmsBpmnController_getResponse200) & {
  headers: Headers;
};
;

export type WmsBpmnController_getResponse = (WmsBpmnController_getResponseSuccess)

export const getWmsBpmnControllerGetUrl = (key: string,) => {




  return `/api/v1/wms/web/customization/processes/${key}`
}

export const WmsBpmnController_get = async (key: string, options?: RequestInit): Promise<WmsBpmnController_getResponse> => {

  return customInstance<WmsBpmnController_getResponse>(getWmsBpmnControllerGetUrl(key),
  {
    ...options,
    method: 'GET'


  }
);}




export const getWmsBpmnControllerGetMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof WmsBpmnController_get>>, TError,{key: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof WmsBpmnController_get>>, TError,{key: string}, TContext> => {

const mutationKey = ['wmsBpmnControllerGet'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof WmsBpmnController_get>>, {key: string}> = (props) => {
          const {key} = props ?? {};

          return  WmsBpmnController_get(key,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type WmsBpmnControllerGetMutationResult = NonNullable<Awaited<ReturnType<typeof WmsBpmnController_get>>>

    export type WmsBpmnControllerGetMutationError = unknown

    export const useWmsBpmnControllerGet = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof WmsBpmnController_get>>, TError,{key: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof WmsBpmnController_get>>,
        TError,
        {key: string},
        TContext
      > => {
      return useMutation(getWmsBpmnControllerGetMutationOptions(options));
    }
    export type WmsBpmnController_updateResponse200 = {
  data: void
  status: 200
}

export type WmsBpmnController_updateResponseSuccess = (WmsBpmnController_updateResponse200) & {
  headers: Headers;
};
;

export type WmsBpmnController_updateResponse = (WmsBpmnController_updateResponseSuccess)

export const getWmsBpmnControllerUpdateUrl = (key: string,) => {




  return `/api/v1/wms/web/customization/processes/${key}`
}

export const WmsBpmnController_update = async (key: string, options?: RequestInit): Promise<WmsBpmnController_updateResponse> => {

  return customInstance<WmsBpmnController_updateResponse>(getWmsBpmnControllerUpdateUrl(key),
  {
    ...options,
    method: 'PATCH'


  }
);}





export const getWmsBpmnControllerUpdateQueryKey = (key: string,) => {
    return [
    'PATCH', `/api/v1/wms/web/customization/processes/${key}`
    ] as const;
    }


export const getWmsBpmnControllerUpdateQueryOptions = <TData = Awaited<ReturnType<typeof WmsBpmnController_update>>, TError = unknown>(key: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof WmsBpmnController_update>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getWmsBpmnControllerUpdateQueryKey(key);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof WmsBpmnController_update>>> = ({ signal }) => WmsBpmnController_update(key, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: key !== null && key !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof WmsBpmnController_update>>, TError, TData> & { queryKey: QueryKey }
}

export type WmsBpmnControllerUpdateQueryResult = NonNullable<Awaited<ReturnType<typeof WmsBpmnController_update>>>
export type WmsBpmnControllerUpdateQueryError = unknown



export function useWmsBpmnControllerUpdate<TData = Awaited<ReturnType<typeof WmsBpmnController_update>>, TError = unknown>(
 key: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof WmsBpmnController_update>>, TError, TData>, request?: SecondParameter<typeof customInstance>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getWmsBpmnControllerUpdateQueryOptions(key,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type WmsBpmnController_parseResponse201 = {
  data: void
  status: 201
}

export type WmsBpmnController_parseResponseSuccess = (WmsBpmnController_parseResponse201) & {
  headers: Headers;
};
;

export type WmsBpmnController_parseResponse = (WmsBpmnController_parseResponseSuccess)

export const getWmsBpmnControllerParseUrl = (key: string,) => {




  return `/api/v1/wms/web/customization/processes/${key}/parse`
}

export const WmsBpmnController_parse = async (key: string, options?: RequestInit): Promise<WmsBpmnController_parseResponse> => {

  return customInstance<WmsBpmnController_parseResponse>(getWmsBpmnControllerParseUrl(key),
  {
    ...options,
    method: 'POST'


  }
);}





export const getWmsBpmnControllerParseQueryKey = (key: string,) => {
    return [
    'POST', `/api/v1/wms/web/customization/processes/${key}/parse`
    ] as const;
    }


export const getWmsBpmnControllerParseQueryOptions = <TData = Awaited<ReturnType<typeof WmsBpmnController_parse>>, TError = unknown>(key: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof WmsBpmnController_parse>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getWmsBpmnControllerParseQueryKey(key);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof WmsBpmnController_parse>>> = ({ signal }) => WmsBpmnController_parse(key, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: key !== null && key !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof WmsBpmnController_parse>>, TError, TData> & { queryKey: QueryKey }
}

export type WmsBpmnControllerParseQueryResult = NonNullable<Awaited<ReturnType<typeof WmsBpmnController_parse>>>
export type WmsBpmnControllerParseQueryError = unknown



export function useWmsBpmnControllerParse<TData = Awaited<ReturnType<typeof WmsBpmnController_parse>>, TError = unknown>(
 key: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof WmsBpmnController_parse>>, TError, TData>, request?: SecondParameter<typeof customInstance>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getWmsBpmnControllerParseQueryOptions(key,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type WmsBpmnController_simulateResponse201 = {
  data: void
  status: 201
}

export type WmsBpmnController_simulateResponseSuccess = (WmsBpmnController_simulateResponse201) & {
  headers: Headers;
};
;

export type WmsBpmnController_simulateResponse = (WmsBpmnController_simulateResponseSuccess)

export const getWmsBpmnControllerSimulateUrl = (key: string,) => {




  return `/api/v1/wms/web/customization/processes/${key}/simulate`
}

export const WmsBpmnController_simulate = async (key: string,
    startProcessDto: StartProcessDto, options?: RequestInit): Promise<WmsBpmnController_simulateResponse> => {

  return customInstance<WmsBpmnController_simulateResponse>(getWmsBpmnControllerSimulateUrl(key),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(startProcessDto)
  }
);}





export const getWmsBpmnControllerSimulateQueryKey = (key: string,
    startProcessDto?: StartProcessDto,) => {
    return [
    'POST', `/api/v1/wms/web/customization/processes/${key}/simulate`, startProcessDto
    ] as const;
    }


export const getWmsBpmnControllerSimulateQueryOptions = <TData = Awaited<ReturnType<typeof WmsBpmnController_simulate>>, TError = unknown>(key: string,
    startProcessDto: StartProcessDto, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof WmsBpmnController_simulate>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getWmsBpmnControllerSimulateQueryKey(key,startProcessDto);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof WmsBpmnController_simulate>>> = ({ signal }) => WmsBpmnController_simulate(key,startProcessDto, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: key !== null && key !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof WmsBpmnController_simulate>>, TError, TData> & { queryKey: QueryKey }
}

export type WmsBpmnControllerSimulateQueryResult = NonNullable<Awaited<ReturnType<typeof WmsBpmnController_simulate>>>
export type WmsBpmnControllerSimulateQueryError = unknown



export function useWmsBpmnControllerSimulate<TData = Awaited<ReturnType<typeof WmsBpmnController_simulate>>, TError = unknown>(
 key: string,
    startProcessDto: StartProcessDto, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof WmsBpmnController_simulate>>, TError, TData>, request?: SecondParameter<typeof customInstance>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getWmsBpmnControllerSimulateQueryOptions(key,startProcessDto,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type WmsBpmnController_rollbackResponse201 = {
  data: void
  status: 201
}

export type WmsBpmnController_rollbackResponseSuccess = (WmsBpmnController_rollbackResponse201) & {
  headers: Headers;
};
;

export type WmsBpmnController_rollbackResponse = (WmsBpmnController_rollbackResponseSuccess)

export const getWmsBpmnControllerRollbackUrl = (key: string,
    version: string,) => {




  return `/api/v1/wms/web/customization/processes/${key}/rollback/${version}`
}

export const WmsBpmnController_rollback = async (key: string,
    version: string, options?: RequestInit): Promise<WmsBpmnController_rollbackResponse> => {

  return customInstance<WmsBpmnController_rollbackResponse>(getWmsBpmnControllerRollbackUrl(key,version),
  {
    ...options,
    method: 'POST'


  }
);}





export const getWmsBpmnControllerRollbackQueryKey = (key: string,
    version: string,) => {
    return [
    'POST', `/api/v1/wms/web/customization/processes/${key}/rollback/${version}`
    ] as const;
    }


export const getWmsBpmnControllerRollbackQueryOptions = <TData = Awaited<ReturnType<typeof WmsBpmnController_rollback>>, TError = unknown>(key: string,
    version: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof WmsBpmnController_rollback>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getWmsBpmnControllerRollbackQueryKey(key,version);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof WmsBpmnController_rollback>>> = ({ signal }) => WmsBpmnController_rollback(key,version, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: key !== null && key !== undefined && version !== null && version !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof WmsBpmnController_rollback>>, TError, TData> & { queryKey: QueryKey }
}

export type WmsBpmnControllerRollbackQueryResult = NonNullable<Awaited<ReturnType<typeof WmsBpmnController_rollback>>>
export type WmsBpmnControllerRollbackQueryError = unknown



export function useWmsBpmnControllerRollback<TData = Awaited<ReturnType<typeof WmsBpmnController_rollback>>, TError = unknown>(
 key: string,
    version: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof WmsBpmnController_rollback>>, TError, TData>, request?: SecondParameter<typeof customInstance>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getWmsBpmnControllerRollbackQueryOptions(key,version,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type ExecutionController_listResponse200 = {
  data: void
  status: 200
}

export type ExecutionController_listResponseSuccess = (ExecutionController_listResponse200) & {
  headers: Headers;
};
;

export type ExecutionController_listResponse = (ExecutionController_listResponseSuccess)

export const getExecutionControllerListUrl = (params?: ExecutionControllerListParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/wms/web/customization/executions?${stringifiedParams}` : `/api/v1/wms/web/customization/executions`
}

export const ExecutionController_list = async (params?: ExecutionControllerListParams, options?: RequestInit): Promise<ExecutionController_listResponse> => {

  return customInstance<ExecutionController_listResponse>(getExecutionControllerListUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}




export const getExecutionControllerListMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof ExecutionController_list>>, TError,{params?: ExecutionControllerListParams}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof ExecutionController_list>>, TError,{params?: ExecutionControllerListParams}, TContext> => {

const mutationKey = ['executionControllerList'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof ExecutionController_list>>, {params?: ExecutionControllerListParams}> = (props) => {
          const {params} = props ?? {};

          return  ExecutionController_list(params,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ExecutionControllerListMutationResult = NonNullable<Awaited<ReturnType<typeof ExecutionController_list>>>

    export type ExecutionControllerListMutationError = unknown

    export const useExecutionControllerList = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof ExecutionController_list>>, TError,{params?: ExecutionControllerListParams}, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof ExecutionController_list>>,
        TError,
        {params?: ExecutionControllerListParams},
        TContext
      > => {
      return useMutation(getExecutionControllerListMutationOptions(options));
    }
    export type ExecutionController_getResponse200 = {
  data: void
  status: 200
}

export type ExecutionController_getResponseSuccess = (ExecutionController_getResponse200) & {
  headers: Headers;
};
;

export type ExecutionController_getResponse = (ExecutionController_getResponseSuccess)

export const getExecutionControllerGetUrl = (id: string,) => {




  return `/api/v1/wms/web/customization/executions/${id}`
}

export const ExecutionController_get = async (id: string, options?: RequestInit): Promise<ExecutionController_getResponse> => {

  return customInstance<ExecutionController_getResponse>(getExecutionControllerGetUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}




export const getExecutionControllerGetMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof ExecutionController_get>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof ExecutionController_get>>, TError,{id: string}, TContext> => {

const mutationKey = ['executionControllerGet'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof ExecutionController_get>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  ExecutionController_get(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ExecutionControllerGetMutationResult = NonNullable<Awaited<ReturnType<typeof ExecutionController_get>>>

    export type ExecutionControllerGetMutationError = unknown

    export const useExecutionControllerGet = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof ExecutionController_get>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof ExecutionController_get>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getExecutionControllerGetMutationOptions(options));
    }
