/**
 * Generated by orval v8.12.1 🍺
 * Do not edit manually.
 * WMS SaaS Core API
 *
 * Domain-agnostic multi-tenant SaaS platform API.
 * Provides: tenancy, auth, RBAC/ABAC, billing, notifications, webhooks, audit, quota management.
 *
 * Authentication:
 *   - **JWT Bearer**: Login via `POST /api/v1/auth/login`
 *   - **API Key**: Header `Authorization: ApiKey wms_{key}`
 *
 * Tenant Resolution:
 *   - Header `X-Tenant-Code: {tenantCode}`
 *   - OR subdomain: `{tenantCode}.yourdomain.com`
 *
 * All endpoints (except @Public) require:
 *   1. Authentication header
 *   2. X-Tenant-Code header (or subdomain)
 *
 * OpenAPI spec version: 1.0
 */

export interface ResetPasswordDto {
  /** New password (min 8 chars) */
  newPassword: string;
  /** Reset token */
  token: string;
}
