/**
 * Generated by orval v8.12.1 🍺
 * Do not edit manually.
 * WMS SaaS Core API
 *
 * Domain-agnostic multi-tenant SaaS platform API.
 * Provides: tenancy, auth, RBAC/ABAC, billing, notifications, webhooks, audit, quota management.
 *
 * Authentication:
 *   - **JWT Bearer**: Login via `POST /api/v1/auth/login`
 *   - **API Key**: Header `Authorization: ApiKey wms_{key}`
 *
 * Tenant Resolution:
 *   - Header `X-Tenant-Code: {tenantCode}`
 *   - OR subdomain: `{tenantCode}.yourdomain.com`
 *
 * All endpoints (except @Public) require:
 *   1. Authentication header
 *   2. X-Tenant-Code header (or subdomain)
 *
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  SystemAdminControllerGetAuditParams,
  SystemAdminControllerGetSecurityEventsParams,
  SystemAdminControllerListTenantsParams
} from '../../../types/wms-saas-core-api';

import { customInstance } from '../../../http/httpClient';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export type SystemAdminController_getStatsResponse200 = {
  data: void
  status: 200
}

export type SystemAdminController_getStatsResponseSuccess = (SystemAdminController_getStatsResponse200) & {
  headers: Headers;
};
;

export type SystemAdminController_getStatsResponse = (SystemAdminController_getStatsResponseSuccess)

export const getSystemAdminControllerGetStatsUrl = () => {




  return `/api/v1/system/stats`
}

/**
 * @summary Get platform statistics (system only)
 */
export const SystemAdminController_getStats = async ( options?: RequestInit): Promise<SystemAdminController_getStatsResponse> => {

  return customInstance<SystemAdminController_getStatsResponse>(getSystemAdminControllerGetStatsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}




export const getSystemAdminControllerGetStatsMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof SystemAdminController_getStats>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof SystemAdminController_getStats>>, TError,void, TContext> => {

const mutationKey = ['systemAdminControllerGetStats'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof SystemAdminController_getStats>>, void> = () => {


          return  SystemAdminController_getStats(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type SystemAdminControllerGetStatsMutationResult = NonNullable<Awaited<ReturnType<typeof SystemAdminController_getStats>>>

    export type SystemAdminControllerGetStatsMutationError = unknown

    /**
 * @summary Get platform statistics (system only)
 */
export const useSystemAdminControllerGetStats = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof SystemAdminController_getStats>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof SystemAdminController_getStats>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getSystemAdminControllerGetStatsMutationOptions(options));
    }
    export type SystemAdminController_getSettingsResponse200 = {
  data: void
  status: 200
}

export type SystemAdminController_getSettingsResponseSuccess = (SystemAdminController_getSettingsResponse200) & {
  headers: Headers;
};
;

export type SystemAdminController_getSettingsResponse = (SystemAdminController_getSettingsResponseSuccess)

export const getSystemAdminControllerGetSettingsUrl = () => {




  return `/api/v1/system/settings`
}

/**
 * @summary Get all system settings
 */
export const SystemAdminController_getSettings = async ( options?: RequestInit): Promise<SystemAdminController_getSettingsResponse> => {

  return customInstance<SystemAdminController_getSettingsResponse>(getSystemAdminControllerGetSettingsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}




export const getSystemAdminControllerGetSettingsMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof SystemAdminController_getSettings>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof SystemAdminController_getSettings>>, TError,void, TContext> => {

const mutationKey = ['systemAdminControllerGetSettings'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof SystemAdminController_getSettings>>, void> = () => {


          return  SystemAdminController_getSettings(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type SystemAdminControllerGetSettingsMutationResult = NonNullable<Awaited<ReturnType<typeof SystemAdminController_getSettings>>>

    export type SystemAdminControllerGetSettingsMutationError = unknown

    /**
 * @summary Get all system settings
 */
export const useSystemAdminControllerGetSettings = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof SystemAdminController_getSettings>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof SystemAdminController_getSettings>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getSystemAdminControllerGetSettingsMutationOptions(options));
    }
    export type SystemAdminController_updateSettingResponse200 = {
  data: void
  status: 200
}

export type SystemAdminController_updateSettingResponseSuccess = (SystemAdminController_updateSettingResponse200) & {
  headers: Headers;
};
;

export type SystemAdminController_updateSettingResponse = (SystemAdminController_updateSettingResponseSuccess)

export const getSystemAdminControllerUpdateSettingUrl = (key: string,) => {




  return `/api/v1/system/settings/${key}`
}

/**
 * @summary Update a system setting
 */
export const SystemAdminController_updateSetting = async (key: string, options?: RequestInit): Promise<SystemAdminController_updateSettingResponse> => {

  return customInstance<SystemAdminController_updateSettingResponse>(getSystemAdminControllerUpdateSettingUrl(key),
  {
    ...options,
    method: 'PATCH'


  }
);}





export const getSystemAdminControllerUpdateSettingQueryKey = (key: string,) => {
    return [
    'PATCH', `/api/v1/system/settings/${key}`
    ] as const;
    }


export const getSystemAdminControllerUpdateSettingQueryOptions = <TData = Awaited<ReturnType<typeof SystemAdminController_updateSetting>>, TError = unknown>(key: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof SystemAdminController_updateSetting>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSystemAdminControllerUpdateSettingQueryKey(key);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof SystemAdminController_updateSetting>>> = ({ signal }) => SystemAdminController_updateSetting(key, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: key !== null && key !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof SystemAdminController_updateSetting>>, TError, TData> & { queryKey: QueryKey }
}

export type SystemAdminControllerUpdateSettingQueryResult = NonNullable<Awaited<ReturnType<typeof SystemAdminController_updateSetting>>>
export type SystemAdminControllerUpdateSettingQueryError = unknown


/**
 * @summary Update a system setting
 */

export function useSystemAdminControllerUpdateSetting<TData = Awaited<ReturnType<typeof SystemAdminController_updateSetting>>, TError = unknown>(
 key: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof SystemAdminController_updateSetting>>, TError, TData>, request?: SecondParameter<typeof customInstance>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getSystemAdminControllerUpdateSettingQueryOptions(key,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type SystemAdminController_listTenantsResponse200 = {
  data: void
  status: 200
}

export type SystemAdminController_listTenantsResponseSuccess = (SystemAdminController_listTenantsResponse200) & {
  headers: Headers;
};
;

export type SystemAdminController_listTenantsResponse = (SystemAdminController_listTenantsResponseSuccess)

export const getSystemAdminControllerListTenantsUrl = (params?: SystemAdminControllerListTenantsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/system/tenants?${stringifiedParams}` : `/api/v1/system/tenants`
}

/**
 * @summary List all tenants
 */
export const SystemAdminController_listTenants = async (params?: SystemAdminControllerListTenantsParams, options?: RequestInit): Promise<SystemAdminController_listTenantsResponse> => {

  return customInstance<SystemAdminController_listTenantsResponse>(getSystemAdminControllerListTenantsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}




export const getSystemAdminControllerListTenantsMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof SystemAdminController_listTenants>>, TError,{params?: SystemAdminControllerListTenantsParams}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof SystemAdminController_listTenants>>, TError,{params?: SystemAdminControllerListTenantsParams}, TContext> => {

const mutationKey = ['systemAdminControllerListTenants'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof SystemAdminController_listTenants>>, {params?: SystemAdminControllerListTenantsParams}> = (props) => {
          const {params} = props ?? {};

          return  SystemAdminController_listTenants(params,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type SystemAdminControllerListTenantsMutationResult = NonNullable<Awaited<ReturnType<typeof SystemAdminController_listTenants>>>

    export type SystemAdminControllerListTenantsMutationError = unknown

    /**
 * @summary List all tenants
 */
export const useSystemAdminControllerListTenants = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof SystemAdminController_listTenants>>, TError,{params?: SystemAdminControllerListTenantsParams}, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof SystemAdminController_listTenants>>,
        TError,
        {params?: SystemAdminControllerListTenantsParams},
        TContext
      > => {
      return useMutation(getSystemAdminControllerListTenantsMutationOptions(options));
    }
    export type SystemAdminController_suspendTenantResponse201 = {
  data: void
  status: 201
}

export type SystemAdminController_suspendTenantResponseSuccess = (SystemAdminController_suspendTenantResponse201) & {
  headers: Headers;
};
;

export type SystemAdminController_suspendTenantResponse = (SystemAdminController_suspendTenantResponseSuccess)

export const getSystemAdminControllerSuspendTenantUrl = (id: string,) => {




  return `/api/v1/system/tenants/${id}/suspend`
}

/**
 * @summary Suspend a tenant
 */
export const SystemAdminController_suspendTenant = async (id: string, options?: RequestInit): Promise<SystemAdminController_suspendTenantResponse> => {

  return customInstance<SystemAdminController_suspendTenantResponse>(getSystemAdminControllerSuspendTenantUrl(id),
  {
    ...options,
    method: 'POST'


  }
);}





export const getSystemAdminControllerSuspendTenantQueryKey = (id: string,) => {
    return [
    'POST', `/api/v1/system/tenants/${id}/suspend`
    ] as const;
    }


export const getSystemAdminControllerSuspendTenantQueryOptions = <TData = Awaited<ReturnType<typeof SystemAdminController_suspendTenant>>, TError = unknown>(id: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof SystemAdminController_suspendTenant>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSystemAdminControllerSuspendTenantQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof SystemAdminController_suspendTenant>>> = ({ signal }) => SystemAdminController_suspendTenant(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof SystemAdminController_suspendTenant>>, TError, TData> & { queryKey: QueryKey }
}

export type SystemAdminControllerSuspendTenantQueryResult = NonNullable<Awaited<ReturnType<typeof SystemAdminController_suspendTenant>>>
export type SystemAdminControllerSuspendTenantQueryError = unknown


/**
 * @summary Suspend a tenant
 */

export function useSystemAdminControllerSuspendTenant<TData = Awaited<ReturnType<typeof SystemAdminController_suspendTenant>>, TError = unknown>(
 id: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof SystemAdminController_suspendTenant>>, TError, TData>, request?: SecondParameter<typeof customInstance>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getSystemAdminControllerSuspendTenantQueryOptions(id,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type SystemAdminController_reactivateTenantResponse201 = {
  data: void
  status: 201
}

export type SystemAdminController_reactivateTenantResponseSuccess = (SystemAdminController_reactivateTenantResponse201) & {
  headers: Headers;
};
;

export type SystemAdminController_reactivateTenantResponse = (SystemAdminController_reactivateTenantResponseSuccess)

export const getSystemAdminControllerReactivateTenantUrl = (id: string,) => {




  return `/api/v1/system/tenants/${id}/reactivate`
}

/**
 * @summary Reactivate a tenant
 */
export const SystemAdminController_reactivateTenant = async (id: string, options?: RequestInit): Promise<SystemAdminController_reactivateTenantResponse> => {

  return customInstance<SystemAdminController_reactivateTenantResponse>(getSystemAdminControllerReactivateTenantUrl(id),
  {
    ...options,
    method: 'POST'


  }
);}





export const getSystemAdminControllerReactivateTenantQueryKey = (id: string,) => {
    return [
    'POST', `/api/v1/system/tenants/${id}/reactivate`
    ] as const;
    }


export const getSystemAdminControllerReactivateTenantQueryOptions = <TData = Awaited<ReturnType<typeof SystemAdminController_reactivateTenant>>, TError = unknown>(id: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof SystemAdminController_reactivateTenant>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSystemAdminControllerReactivateTenantQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof SystemAdminController_reactivateTenant>>> = ({ signal }) => SystemAdminController_reactivateTenant(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof SystemAdminController_reactivateTenant>>, TError, TData> & { queryKey: QueryKey }
}

export type SystemAdminControllerReactivateTenantQueryResult = NonNullable<Awaited<ReturnType<typeof SystemAdminController_reactivateTenant>>>
export type SystemAdminControllerReactivateTenantQueryError = unknown


/**
 * @summary Reactivate a tenant
 */

export function useSystemAdminControllerReactivateTenant<TData = Awaited<ReturnType<typeof SystemAdminController_reactivateTenant>>, TError = unknown>(
 id: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof SystemAdminController_reactivateTenant>>, TError, TData>, request?: SecondParameter<typeof customInstance>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getSystemAdminControllerReactivateTenantQueryOptions(id,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type SystemAdminController_impersonateTenantResponse201 = {
  data: void
  status: 201
}

export type SystemAdminController_impersonateTenantResponseSuccess = (SystemAdminController_impersonateTenantResponse201) & {
  headers: Headers;
};
;

export type SystemAdminController_impersonateTenantResponse = (SystemAdminController_impersonateTenantResponseSuccess)

export const getSystemAdminControllerImpersonateTenantUrl = (id: string,) => {




  return `/api/v1/system/tenants/${id}/impersonate`
}

/**
 * @summary Impersonate a tenant (15min token)
 */
export const SystemAdminController_impersonateTenant = async (id: string, options?: RequestInit): Promise<SystemAdminController_impersonateTenantResponse> => {

  return customInstance<SystemAdminController_impersonateTenantResponse>(getSystemAdminControllerImpersonateTenantUrl(id),
  {
    ...options,
    method: 'POST'


  }
);}





export const getSystemAdminControllerImpersonateTenantQueryKey = (id: string,) => {
    return [
    'POST', `/api/v1/system/tenants/${id}/impersonate`
    ] as const;
    }


export const getSystemAdminControllerImpersonateTenantQueryOptions = <TData = Awaited<ReturnType<typeof SystemAdminController_impersonateTenant>>, TError = unknown>(id: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof SystemAdminController_impersonateTenant>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSystemAdminControllerImpersonateTenantQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof SystemAdminController_impersonateTenant>>> = ({ signal }) => SystemAdminController_impersonateTenant(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof SystemAdminController_impersonateTenant>>, TError, TData> & { queryKey: QueryKey }
}

export type SystemAdminControllerImpersonateTenantQueryResult = NonNullable<Awaited<ReturnType<typeof SystemAdminController_impersonateTenant>>>
export type SystemAdminControllerImpersonateTenantQueryError = unknown


/**
 * @summary Impersonate a tenant (15min token)
 */

export function useSystemAdminControllerImpersonateTenant<TData = Awaited<ReturnType<typeof SystemAdminController_impersonateTenant>>, TError = unknown>(
 id: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof SystemAdminController_impersonateTenant>>, TError, TData>, request?: SecondParameter<typeof customInstance>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getSystemAdminControllerImpersonateTenantQueryOptions(id,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type SystemAdminController_getQueuesResponse200 = {
  data: void
  status: 200
}

export type SystemAdminController_getQueuesResponseSuccess = (SystemAdminController_getQueuesResponse200) & {
  headers: Headers;
};
;

export type SystemAdminController_getQueuesResponse = (SystemAdminController_getQueuesResponseSuccess)

export const getSystemAdminControllerGetQueuesUrl = () => {




  return `/api/v1/system/queues`
}

/**
 * @summary Get queue statistics
 */
export const SystemAdminController_getQueues = async ( options?: RequestInit): Promise<SystemAdminController_getQueuesResponse> => {

  return customInstance<SystemAdminController_getQueuesResponse>(getSystemAdminControllerGetQueuesUrl(),
  {
    ...options,
    method: 'GET'


  }
);}




export const getSystemAdminControllerGetQueuesMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof SystemAdminController_getQueues>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof SystemAdminController_getQueues>>, TError,void, TContext> => {

const mutationKey = ['systemAdminControllerGetQueues'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof SystemAdminController_getQueues>>, void> = () => {


          return  SystemAdminController_getQueues(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type SystemAdminControllerGetQueuesMutationResult = NonNullable<Awaited<ReturnType<typeof SystemAdminController_getQueues>>>

    export type SystemAdminControllerGetQueuesMutationError = unknown

    /**
 * @summary Get queue statistics
 */
export const useSystemAdminControllerGetQueues = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof SystemAdminController_getQueues>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof SystemAdminController_getQueues>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getSystemAdminControllerGetQueuesMutationOptions(options));
    }
    export type SystemAdminController_purgeQueueResponse200 = {
  data: void
  status: 200
}

export type SystemAdminController_purgeQueueResponseSuccess = (SystemAdminController_purgeQueueResponse200) & {
  headers: Headers;
};
;

export type SystemAdminController_purgeQueueResponse = (SystemAdminController_purgeQueueResponseSuccess)

export const getSystemAdminControllerPurgeQueueUrl = (name: string,) => {




  return `/api/v1/system/queues/${name}/failed`
}

/**
 * @summary Purge failed jobs from a queue
 */
export const SystemAdminController_purgeQueue = async (name: string, options?: RequestInit): Promise<SystemAdminController_purgeQueueResponse> => {

  return customInstance<SystemAdminController_purgeQueueResponse>(getSystemAdminControllerPurgeQueueUrl(name),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getSystemAdminControllerPurgeQueueQueryKey = (name: string,) => {
    return [
    'DELETE', `/api/v1/system/queues/${name}/failed`
    ] as const;
    }


export const getSystemAdminControllerPurgeQueueQueryOptions = <TData = Awaited<ReturnType<typeof SystemAdminController_purgeQueue>>, TError = unknown>(name: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof SystemAdminController_purgeQueue>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSystemAdminControllerPurgeQueueQueryKey(name);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof SystemAdminController_purgeQueue>>> = ({ signal }) => SystemAdminController_purgeQueue(name, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: name !== null && name !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof SystemAdminController_purgeQueue>>, TError, TData> & { queryKey: QueryKey }
}

export type SystemAdminControllerPurgeQueueQueryResult = NonNullable<Awaited<ReturnType<typeof SystemAdminController_purgeQueue>>>
export type SystemAdminControllerPurgeQueueQueryError = unknown


/**
 * @summary Purge failed jobs from a queue
 */

export function useSystemAdminControllerPurgeQueue<TData = Awaited<ReturnType<typeof SystemAdminController_purgeQueue>>, TError = unknown>(
 name: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof SystemAdminController_purgeQueue>>, TError, TData>, request?: SecondParameter<typeof customInstance>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getSystemAdminControllerPurgeQueueQueryOptions(name,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type SystemAdminController_getPendingPaymentsResponse200 = {
  data: void
  status: 200
}

export type SystemAdminController_getPendingPaymentsResponseSuccess = (SystemAdminController_getPendingPaymentsResponse200) & {
  headers: Headers;
};
;

export type SystemAdminController_getPendingPaymentsResponse = (SystemAdminController_getPendingPaymentsResponseSuccess)

export const getSystemAdminControllerGetPendingPaymentsUrl = () => {




  return `/api/v1/system/billing/pending-payments`
}

/**
 * @summary Get pending payments across all tenants
 */
export const SystemAdminController_getPendingPayments = async ( options?: RequestInit): Promise<SystemAdminController_getPendingPaymentsResponse> => {

  return customInstance<SystemAdminController_getPendingPaymentsResponse>(getSystemAdminControllerGetPendingPaymentsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}




export const getSystemAdminControllerGetPendingPaymentsMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof SystemAdminController_getPendingPayments>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof SystemAdminController_getPendingPayments>>, TError,void, TContext> => {

const mutationKey = ['systemAdminControllerGetPendingPayments'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof SystemAdminController_getPendingPayments>>, void> = () => {


          return  SystemAdminController_getPendingPayments(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type SystemAdminControllerGetPendingPaymentsMutationResult = NonNullable<Awaited<ReturnType<typeof SystemAdminController_getPendingPayments>>>

    export type SystemAdminControllerGetPendingPaymentsMutationError = unknown

    /**
 * @summary Get pending payments across all tenants
 */
export const useSystemAdminControllerGetPendingPayments = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof SystemAdminController_getPendingPayments>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof SystemAdminController_getPendingPayments>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getSystemAdminControllerGetPendingPaymentsMutationOptions(options));
    }
    export type SystemAdminController_getAuditResponse200 = {
  data: void
  status: 200
}

export type SystemAdminController_getAuditResponseSuccess = (SystemAdminController_getAuditResponse200) & {
  headers: Headers;
};
;

export type SystemAdminController_getAuditResponse = (SystemAdminController_getAuditResponseSuccess)

export const getSystemAdminControllerGetAuditUrl = (params?: SystemAdminControllerGetAuditParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/system/audit?${stringifiedParams}` : `/api/v1/system/audit`
}

/**
 * @summary Cross-tenant audit log view
 */
export const SystemAdminController_getAudit = async (params?: SystemAdminControllerGetAuditParams, options?: RequestInit): Promise<SystemAdminController_getAuditResponse> => {

  return customInstance<SystemAdminController_getAuditResponse>(getSystemAdminControllerGetAuditUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}




export const getSystemAdminControllerGetAuditMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof SystemAdminController_getAudit>>, TError,{params?: SystemAdminControllerGetAuditParams}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof SystemAdminController_getAudit>>, TError,{params?: SystemAdminControllerGetAuditParams}, TContext> => {

const mutationKey = ['systemAdminControllerGetAudit'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof SystemAdminController_getAudit>>, {params?: SystemAdminControllerGetAuditParams}> = (props) => {
          const {params} = props ?? {};

          return  SystemAdminController_getAudit(params,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type SystemAdminControllerGetAuditMutationResult = NonNullable<Awaited<ReturnType<typeof SystemAdminController_getAudit>>>

    export type SystemAdminControllerGetAuditMutationError = unknown

    /**
 * @summary Cross-tenant audit log view
 */
export const useSystemAdminControllerGetAudit = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof SystemAdminController_getAudit>>, TError,{params?: SystemAdminControllerGetAuditParams}, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof SystemAdminController_getAudit>>,
        TError,
        {params?: SystemAdminControllerGetAuditParams},
        TContext
      > => {
      return useMutation(getSystemAdminControllerGetAuditMutationOptions(options));
    }
    export type SystemAdminController_getSecurityEventsResponse200 = {
  data: void
  status: 200
}

export type SystemAdminController_getSecurityEventsResponseSuccess = (SystemAdminController_getSecurityEventsResponse200) & {
  headers: Headers;
};
;

export type SystemAdminController_getSecurityEventsResponse = (SystemAdminController_getSecurityEventsResponseSuccess)

export const getSystemAdminControllerGetSecurityEventsUrl = (params?: SystemAdminControllerGetSecurityEventsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/system/security-events?${stringifiedParams}` : `/api/v1/system/security-events`
}

/**
 * @summary Cross-tenant security events view
 */
export const SystemAdminController_getSecurityEvents = async (params?: SystemAdminControllerGetSecurityEventsParams, options?: RequestInit): Promise<SystemAdminController_getSecurityEventsResponse> => {

  return customInstance<SystemAdminController_getSecurityEventsResponse>(getSystemAdminControllerGetSecurityEventsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}




export const getSystemAdminControllerGetSecurityEventsMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof SystemAdminController_getSecurityEvents>>, TError,{params?: SystemAdminControllerGetSecurityEventsParams}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof SystemAdminController_getSecurityEvents>>, TError,{params?: SystemAdminControllerGetSecurityEventsParams}, TContext> => {

const mutationKey = ['systemAdminControllerGetSecurityEvents'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof SystemAdminController_getSecurityEvents>>, {params?: SystemAdminControllerGetSecurityEventsParams}> = (props) => {
          const {params} = props ?? {};

          return  SystemAdminController_getSecurityEvents(params,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type SystemAdminControllerGetSecurityEventsMutationResult = NonNullable<Awaited<ReturnType<typeof SystemAdminController_getSecurityEvents>>>

    export type SystemAdminControllerGetSecurityEventsMutationError = unknown

    /**
 * @summary Cross-tenant security events view
 */
export const useSystemAdminControllerGetSecurityEvents = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof SystemAdminController_getSecurityEvents>>, TError,{params?: SystemAdminControllerGetSecurityEventsParams}, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof SystemAdminController_getSecurityEvents>>,
        TError,
        {params?: SystemAdminControllerGetSecurityEventsParams},
        TContext
      > => {
      return useMutation(getSystemAdminControllerGetSecurityEventsMutationOptions(options));
    }
    export type SystemAdminController_seedResponse201 = {
  data: void
  status: 201
}

export type SystemAdminController_seedResponseSuccess = (SystemAdminController_seedResponse201) & {
  headers: Headers;
};
;

export type SystemAdminController_seedResponse = (SystemAdminController_seedResponseSuccess)

export const getSystemAdminControllerSeedUrl = () => {




  return `/api/v1/system/seed`
}

/**
 * @summary Re-run system seeder
 */
export const SystemAdminController_seed = async ( options?: RequestInit): Promise<SystemAdminController_seedResponse> => {

  return customInstance<SystemAdminController_seedResponse>(getSystemAdminControllerSeedUrl(),
  {
    ...options,
    method: 'POST'


  }
);}





export const getSystemAdminControllerSeedQueryKey = () => {
    return [
    'POST', `/api/v1/system/seed`
    ] as const;
    }


export const getSystemAdminControllerSeedQueryOptions = <TData = Awaited<ReturnType<typeof SystemAdminController_seed>>, TError = unknown>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof SystemAdminController_seed>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSystemAdminControllerSeedQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof SystemAdminController_seed>>> = ({ signal }) => SystemAdminController_seed({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof SystemAdminController_seed>>, TError, TData> & { queryKey: QueryKey }
}

export type SystemAdminControllerSeedQueryResult = NonNullable<Awaited<ReturnType<typeof SystemAdminController_seed>>>
export type SystemAdminControllerSeedQueryError = unknown


/**
 * @summary Re-run system seeder
 */

export function useSystemAdminControllerSeed<TData = Awaited<ReturnType<typeof SystemAdminController_seed>>, TError = unknown>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof SystemAdminController_seed>>, TError, TData>, request?: SecondParameter<typeof customInstance>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getSystemAdminControllerSeedQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}






