/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * WMS API
 * Warehouse Management System API
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreatePickCartDto,
  PaginatedResponseDto,
  PickCartDto,
  UpdatePickCartDto
} from '../../../types/wms-api';

import { customInstance } from '../../../http/httpClient.js';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type PickCartController_createResponse201 = {
  data: PickCartDto
  status: 201
}

export type PickCartController_createResponseSuccess = (PickCartController_createResponse201) & {
  headers: Headers;
};
;

export type PickCartController_createResponse = (PickCartController_createResponseSuccess)

export const getPickCartControllerCreateUrl = () => {




  return `/api/v1/wms/web/pick-carts`
}

/**
 * @summary Create pick cart
 */
export const PickCartController_create = async (createPickCartDto: CreatePickCartDto, options?: RequestInit): Promise<PickCartController_createResponse> => {

  return customInstance<PickCartController_createResponse>(getPickCartControllerCreateUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createPickCartDto)
  }
);}





export const getPickCartControllerCreateQueryKey = (createPickCartDto?: CreatePickCartDto,) => {
    return [
    'POST', `/api/v1/wms/web/pick-carts`, createPickCartDto
    ] as const;
    }


export const getPickCartControllerCreateQueryOptions = <TData = Awaited<ReturnType<typeof PickCartController_create>>, TError = unknown>(createPickCartDto: CreatePickCartDto, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof PickCartController_create>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPickCartControllerCreateQueryKey(createPickCartDto);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof PickCartController_create>>> = ({ signal }) => PickCartController_create(createPickCartDto, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof PickCartController_create>>, TError, TData> & { queryKey: QueryKey }
}

export type PickCartControllerCreateQueryResult = NonNullable<Awaited<ReturnType<typeof PickCartController_create>>>
export type PickCartControllerCreateQueryError = unknown


/**
 * @summary Create pick cart
 */

export function usePickCartControllerCreate<TData = Awaited<ReturnType<typeof PickCartController_create>>, TError = unknown>(
 createPickCartDto: CreatePickCartDto, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof PickCartController_create>>, TError, TData>, request?: SecondParameter<typeof customInstance>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getPickCartControllerCreateQueryOptions(createPickCartDto,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}






export type PickCartController_findAllResponse200 = {
  data: PaginatedResponseDto
  status: 200
}

export type PickCartController_findAllResponseSuccess = (PickCartController_findAllResponse200) & {
  headers: Headers;
};
;

export type PickCartController_findAllResponse = (PickCartController_findAllResponseSuccess)

export const getPickCartControllerFindAllUrl = () => {




  return `/api/v1/wms/web/pick-carts`
}

/**
 * @summary List pick carts
 */
export const PickCartController_findAll = async ( options?: RequestInit): Promise<PickCartController_findAllResponse> => {

  return customInstance<PickCartController_findAllResponse>(getPickCartControllerFindAllUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getPickCartControllerFindAllMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof PickCartController_findAll>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof PickCartController_findAll>>, TError,void, TContext> => {

const mutationKey = ['pickCartControllerFindAll'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof PickCartController_findAll>>, void> = () => {


          return  PickCartController_findAll(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PickCartControllerFindAllMutationResult = NonNullable<Awaited<ReturnType<typeof PickCartController_findAll>>>

    export type PickCartControllerFindAllMutationError = unknown

    /**
 * @summary List pick carts
 */
export const usePickCartControllerFindAll = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof PickCartController_findAll>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof PickCartController_findAll>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getPickCartControllerFindAllMutationOptions(options));
    }
    export type PickCartController_findByIdResponse200 = {
  data: PickCartDto
  status: 200
}

export type PickCartController_findByIdResponseSuccess = (PickCartController_findByIdResponse200) & {
  headers: Headers;
};
;

export type PickCartController_findByIdResponse = (PickCartController_findByIdResponseSuccess)

export const getPickCartControllerFindByIdUrl = (id: string,) => {




  return `/api/v1/wms/web/pick-carts/${id}`
}

/**
 * @summary Get pick cart
 */
export const PickCartController_findById = async (id: string, options?: RequestInit): Promise<PickCartController_findByIdResponse> => {

  return customInstance<PickCartController_findByIdResponse>(getPickCartControllerFindByIdUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getPickCartControllerFindByIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof PickCartController_findById>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof PickCartController_findById>>, TError,{id: string}, TContext> => {

const mutationKey = ['pickCartControllerFindById'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof PickCartController_findById>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  PickCartController_findById(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PickCartControllerFindByIdMutationResult = NonNullable<Awaited<ReturnType<typeof PickCartController_findById>>>

    export type PickCartControllerFindByIdMutationError = unknown

    /**
 * @summary Get pick cart
 */
export const usePickCartControllerFindById = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof PickCartController_findById>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof PickCartController_findById>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getPickCartControllerFindByIdMutationOptions(options));
    }
    export type PickCartController_updateResponse200 = {
  data: PickCartDto
  status: 200
}

export type PickCartController_updateResponseSuccess = (PickCartController_updateResponse200) & {
  headers: Headers;
};
;

export type PickCartController_updateResponse = (PickCartController_updateResponseSuccess)

export const getPickCartControllerUpdateUrl = (id: string,) => {




  return `/api/v1/wms/web/pick-carts/${id}`
}

/**
 * @summary Update pick cart
 */
export const PickCartController_update = async (id: string,
    updatePickCartDto: UpdatePickCartDto, options?: RequestInit): Promise<PickCartController_updateResponse> => {

  return customInstance<PickCartController_updateResponse>(getPickCartControllerUpdateUrl(id),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updatePickCartDto)
  }
);}





export const getPickCartControllerUpdateQueryKey = (id: string,
    updatePickCartDto?: UpdatePickCartDto,) => {
    return [
    'PATCH', `/api/v1/wms/web/pick-carts/${id}`, updatePickCartDto
    ] as const;
    }


export const getPickCartControllerUpdateQueryOptions = <TData = Awaited<ReturnType<typeof PickCartController_update>>, TError = unknown>(id: string,
    updatePickCartDto: UpdatePickCartDto, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof PickCartController_update>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPickCartControllerUpdateQueryKey(id,updatePickCartDto);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof PickCartController_update>>> = ({ signal }) => PickCartController_update(id,updatePickCartDto, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof PickCartController_update>>, TError, TData> & { queryKey: QueryKey }
}

export type PickCartControllerUpdateQueryResult = NonNullable<Awaited<ReturnType<typeof PickCartController_update>>>
export type PickCartControllerUpdateQueryError = unknown


/**
 * @summary Update pick cart
 */

export function usePickCartControllerUpdate<TData = Awaited<ReturnType<typeof PickCartController_update>>, TError = unknown>(
 id: string,
    updatePickCartDto: UpdatePickCartDto, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof PickCartController_update>>, TError, TData>, request?: SecondParameter<typeof customInstance>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getPickCartControllerUpdateQueryOptions(id,updatePickCartDto,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}






export type PickCartController_deleteResponse200 = {
  data: PickCartDto
  status: 200
}

export type PickCartController_deleteResponseSuccess = (PickCartController_deleteResponse200) & {
  headers: Headers;
};
;

export type PickCartController_deleteResponse = (PickCartController_deleteResponseSuccess)

export const getPickCartControllerDeleteUrl = (id: string,) => {




  return `/api/v1/wms/web/pick-carts/${id}`
}

/**
 * @summary Delete pick cart
 */
export const PickCartController_delete = async (id: string, options?: RequestInit): Promise<PickCartController_deleteResponse> => {

  return customInstance<PickCartController_deleteResponse>(getPickCartControllerDeleteUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getPickCartControllerDeleteQueryKey = (id: string,) => {
    return [
    'DELETE', `/api/v1/wms/web/pick-carts/${id}`
    ] as const;
    }


export const getPickCartControllerDeleteQueryOptions = <TData = Awaited<ReturnType<typeof PickCartController_delete>>, TError = unknown>(id: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof PickCartController_delete>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPickCartControllerDeleteQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof PickCartController_delete>>> = ({ signal }) => PickCartController_delete(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof PickCartController_delete>>, TError, TData> & { queryKey: QueryKey }
}

export type PickCartControllerDeleteQueryResult = NonNullable<Awaited<ReturnType<typeof PickCartController_delete>>>
export type PickCartControllerDeleteQueryError = unknown


/**
 * @summary Delete pick cart
 */

export function usePickCartControllerDelete<TData = Awaited<ReturnType<typeof PickCartController_delete>>, TError = unknown>(
 id: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof PickCartController_delete>>, TError, TData>, request?: SecondParameter<typeof customInstance>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getPickCartControllerDeleteQueryOptions(id,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}






