/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * WMS API
 * Warehouse Management System API
 * OpenAPI spec version: 1.0.0
 */
import type { AdvanceShipNoticeDtoActualArrivalDate } from './advanceShipNoticeDtoActualArrivalDate.js';
import type { AdvanceShipNoticeDtoCarrierName } from './advanceShipNoticeDtoCarrierName.js';
import type { AdvanceShipNoticeDtoClientName } from './advanceShipNoticeDtoClientName.js';
import type { AdvanceShipNoticeDtoCreatedAt } from './advanceShipNoticeDtoCreatedAt.js';
import type { AdvanceShipNoticeDtoCreatedBy } from './advanceShipNoticeDtoCreatedBy.js';
import type { AdvanceShipNoticeDtoExpectedArrivalDate } from './advanceShipNoticeDtoExpectedArrivalDate.js';
import type { AdvanceShipNoticeDtoFacilityName } from './advanceShipNoticeDtoFacilityName.js';
import type { AdvanceShipNoticeDtoInboundForClientId } from './advanceShipNoticeDtoInboundForClientId.js';
import type { AdvanceShipNoticeDtoNotes } from './advanceShipNoticeDtoNotes.js';
import type { AdvanceShipNoticeDtoPoNumber } from './advanceShipNoticeDtoPoNumber.js';
import type { AdvanceShipNoticeDtoShipmentDate } from './advanceShipNoticeDtoShipmentDate.js';
import type { AdvanceShipNoticeDtoStatusChangedAt } from './advanceShipNoticeDtoStatusChangedAt.js';
import type { AdvanceShipNoticeDtoStatusChangedBy } from './advanceShipNoticeDtoStatusChangedBy.js';
import type { AdvanceShipNoticeDtoTrackingNumber } from './advanceShipNoticeDtoTrackingNumber.js';
import type { AdvanceShipNoticeDtoUpdatedAt } from './advanceShipNoticeDtoUpdatedAt.js';
import type { AdvanceShipNoticeDtoUpdatedBy } from './advanceShipNoticeDtoUpdatedBy.js';
import type { AdvanceShipNoticeDtoVendorId } from './advanceShipNoticeDtoVendorId.js';
import type { AdvanceShipNoticeDtoVendorName } from './advanceShipNoticeDtoVendorName.js';
import type { AdvanceShipNoticeDtoVersion } from './advanceShipNoticeDtoVersion.js';
import type { AdvanceShipNoticeDtoVolume } from './advanceShipNoticeDtoVolume.js';
import type { AdvanceShipNoticeDtoWeight } from './advanceShipNoticeDtoWeight.js';

export interface AdvanceShipNoticeDto {
  actual_arrival_date?: AdvanceShipNoticeDtoActualArrivalDate;
  asn_id: number;
  asn_number: string;
  carrier_name?: AdvanceShipNoticeDtoCarrierName;
  client_name?: AdvanceShipNoticeDtoClientName;
  created_at?: AdvanceShipNoticeDtoCreatedAt;
  created_by?: AdvanceShipNoticeDtoCreatedBy;
  expected_arrival_date?: AdvanceShipNoticeDtoExpectedArrivalDate;
  facility_id: number;
  facility_name?: AdvanceShipNoticeDtoFacilityName;
  inbound_for_client_id?: AdvanceShipNoticeDtoInboundForClientId;
  notes?: AdvanceShipNoticeDtoNotes;
  po_number?: AdvanceShipNoticeDtoPoNumber;
  shipment_date?: AdvanceShipNoticeDtoShipmentDate;
  status: string;
  status_changed_at?: AdvanceShipNoticeDtoStatusChangedAt;
  status_changed_by?: AdvanceShipNoticeDtoStatusChangedBy;
  tenant_id: string;
  tracking_number?: AdvanceShipNoticeDtoTrackingNumber;
  updated_at?: AdvanceShipNoticeDtoUpdatedAt;
  updated_by?: AdvanceShipNoticeDtoUpdatedBy;
  vendor_id?: AdvanceShipNoticeDtoVendorId;
  vendor_name?: AdvanceShipNoticeDtoVendorName;
  version?: AdvanceShipNoticeDtoVersion;
  volume?: AdvanceShipNoticeDtoVolume;
  weight?: AdvanceShipNoticeDtoWeight;
}
