/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * WMS API
 * Warehouse Management System API
 * OpenAPI spec version: 1.0.0
 */
import type { AisleResponseDtoAisleName } from './aisleResponseDtoAisleName.js';
import type { AisleResponseDtoAisleNumber } from './aisleResponseDtoAisleNumber.js';
import type { AisleResponseDtoAllowedEquipmentTypesJson } from './aisleResponseDtoAllowedEquipmentTypesJson.js';
import type { AisleResponseDtoBlockReason } from './aisleResponseDtoBlockReason.js';
import type { AisleResponseDtoCreatedAt } from './aisleResponseDtoCreatedAt.js';
import type { AisleResponseDtoCreatedBy } from './aisleResponseDtoCreatedBy.js';
import type { AisleResponseDtoFacilityName } from './aisleResponseDtoFacilityName.js';
import type { AisleResponseDtoIsBlocked } from './aisleResponseDtoIsBlocked.js';
import type { AisleResponseDtoLengthMeters } from './aisleResponseDtoLengthMeters.js';
import type { AisleResponseDtoMaxEquipmentHeightCm } from './aisleResponseDtoMaxEquipmentHeightCm.js';
import type { AisleResponseDtoPickingDirection } from './aisleResponseDtoPickingDirection.js';
import type { AisleResponseDtoStartSequenceNumber } from './aisleResponseDtoStartSequenceNumber.js';
import type { AisleResponseDtoUpdatedAt } from './aisleResponseDtoUpdatedAt.js';
import type { AisleResponseDtoUpdatedBy } from './aisleResponseDtoUpdatedBy.js';
import type { AisleResponseDtoVersion } from './aisleResponseDtoVersion.js';
import type { AisleResponseDtoWidthMeters } from './aisleResponseDtoWidthMeters.js';
import type { AisleResponseDtoZoneName } from './aisleResponseDtoZoneName.js';

export interface AisleResponseDto {
  aisle_code: string;
  aisle_id: number;
  aisle_name?: AisleResponseDtoAisleName;
  aisle_number?: AisleResponseDtoAisleNumber;
  allowed_equipment_types_json?: AisleResponseDtoAllowedEquipmentTypesJson;
  block_reason?: AisleResponseDtoBlockReason;
  created_at?: AisleResponseDtoCreatedAt;
  created_by?: AisleResponseDtoCreatedBy;
  facility_id: number;
  facility_name?: AisleResponseDtoFacilityName;
  is_active: boolean;
  is_blocked?: AisleResponseDtoIsBlocked;
  length_meters?: AisleResponseDtoLengthMeters;
  max_equipment_height_cm?: AisleResponseDtoMaxEquipmentHeightCm;
  picking_direction?: AisleResponseDtoPickingDirection;
  start_sequence_number?: AisleResponseDtoStartSequenceNumber;
  tenant_id: string;
  updated_at?: AisleResponseDtoUpdatedAt;
  updated_by?: AisleResponseDtoUpdatedBy;
  version?: AisleResponseDtoVersion;
  width_meters?: AisleResponseDtoWidthMeters;
  zone_id: number;
  zone_name?: AisleResponseDtoZoneName;
}
