/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * WMS API
 * Warehouse Management System API
 * OpenAPI spec version: 1.0.0
 */

export interface ApprovalThresholdConfigResponseDto {
  auto_approve_abs?: number;
  auto_approve_pct?: number;
  config_id?: string;
  created_at?: string;
  created_by?: string;
  facility_id?: string;
  facility_name?: string;
  is_active?: boolean;
  recount_pct?: number;
  supervisor_review_pct?: number;
  tenant_id?: string;
  threshold_type?: string;
  updated_at?: string;
  updated_by?: string;
  version?: number;
}
