/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * WMS API
 * Warehouse Management System API
 * OpenAPI spec version: 1.0.0
 */

export interface CompleteVasTaskDto {
  actual_duration_minutes?: number;
  exception_notes?: string;
  execution_notes?: string;
  quality_check_required?: boolean;
  quality_checked_at?: string;
  quality_checked_by?: string;
  quality_status?: string;
  quantity_completed?: number;
}
