/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * WMS API
 * Warehouse Management System API
 * OpenAPI spec version: 1.0.0
 */

export interface CreateTransferDto {
  destination_warehouse_id: string;
  facility_id: string;
  lines?: string[];
  notes?: string;
  source_warehouse_id: string;
}
