/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * WMS API
 * Warehouse Management System API
 * OpenAPI spec version: 1.0.0
 */

export interface CreatePutawayRuleDto {
  action_type?: string;
  client_id?: number;
  description?: string;
  destination_location_attributes_json?: string;
  destination_location_types_json?: string;
  destination_zone_id?: number;
  destination_zone_ids_json?: string;
  facility_id: number;
  fixed_location_code?: string;
  is_active?: boolean;
  is_overflow_rule?: boolean;
  location_type_preference?: string;
  min_pick_frequency_per_day?: number;
  parent_rule_id?: number;
  prefer_pick_face_for_fast_movers?: boolean;
  priority?: number;
  product_attribute_rules_json?: string;
  product_category_id?: number;
  product_category_ids_json?: string;
  product_id?: number;
  product_uom_ids_json?: string;
  rotation_logic?: string;
  rule_code: string;
  rule_name: string;
  storage_condition_requirements_json?: string;
  velocity_class_filter?: string[];
}
