/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * WMS API
 * Warehouse Management System API
 * OpenAPI spec version: 1.0.0
 */

export interface CreateBayDto {
  aisle_id: string;
  bay_code: string;
  bay_name?: string;
  bay_number?: number;
  facility_id: string;
  is_active?: boolean;
  is_reserved?: boolean;
  length_meters?: number;
  position_start_meters?: number;
  positions_per_level?: number;
  rack_row_id: string;
  reservation_notes?: string;
  side?: string;
  status?: string;
  zone_id: string;
}
