/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * WMS API
 * Warehouse Management System API
 * OpenAPI spec version: 1.0.0
 */

export interface CreateBatchSortationDto {
  batch_id: string;
  completed_at?: string;
  created_by?: string;
  sorted_items?: number;
  status?: string;
  total_items?: number;
}
