/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * WMS API
 * Warehouse Management System API
 * OpenAPI spec version: 1.0.0
 */

export interface CreateProductClientAssignmentDto {
  client_id: number;
  effective_date?: string;
  expiry_date?: string;
  facility_id: number;
  is_active?: boolean;
  notes?: string;
  product_id: number;
}
