/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * WMS API
 * Warehouse Management System API
 * OpenAPI spec version: 1.0.0
 */

export interface CreateAsnImportJobDto {
  facility_id: number;
  import_channel?: string;
  job_number: string;
  source_system: string;
}
