/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * WMS API
 * Warehouse Management System API
 * OpenAPI spec version: 1.0.0
 */

export interface CreateFacilityUserDto {
  facility_id: number;
  is_active?: boolean;
  notes?: string;
  user_email?: string;
  user_id: string;
  user_name?: string;
}
