/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * WMS API
 * Warehouse Management System API
 * OpenAPI spec version: 1.0.0
 */

export interface CreateEquipmentDto {
  assigned_user_id?: string;
  current_location_id?: string;
  description?: string;
  equipment_code: string;
  equipment_name: string;
  equipment_type: string;
  facility_id: string;
  is_active?: boolean;
  last_maintenance_date?: string;
  maintenance_interval_months?: number;
  manufacturer?: string;
  model_number?: string;
  next_maintenance_date?: string;
  purchase_cost?: number;
  purchase_date?: string;
  serial_number?: string;
  status?: string;
}
