/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * WMS API
 * Warehouse Management System API
 * OpenAPI spec version: 1.0.0
 */

export interface CreateGoodsReceiptDto {
  asn_number?: string;
  description?: string;
  expected_date?: string;
  facility_id: number;
  inbound_for_client_id?: number;
  notes?: string;
  po_number?: string;
  receipt_name?: string;
  receipt_number?: string;
  vendor_id?: number;
}
