/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * WMS API
 * Warehouse Management System API
 * OpenAPI spec version: 1.0.0
 */

export interface CreateQualityHoldDto {
  affected_quantity?: number;
  description?: string;
  facility_id: string;
  hold_name?: string;
  hold_number: string;
  hold_reason: string;
  hold_reason_code?: string;
  location_id?: string;
  lot_id?: string;
  notes?: string;
  placed_by_user_id: string;
  product_id?: string;
  reference_id: string;
  reference_type: string;
  status?: string;
  uom_id?: string;
}
