/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * WMS API
 * Warehouse Management System API
 * OpenAPI spec version: 1.0.0
 */

export interface CreatePickCartDto {
  cart_code: string;
  cart_type?: string;
  facility_id: string;
  is_active?: boolean;
  num_shelves?: number;
}
