/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * WMS API
 * Warehouse Management System API
 * OpenAPI spec version: 1.0.0
 */

export interface CycleCountEventResponseDto {
  count_id: string;
  event_data?: string;
  event_id: string;
  event_type: string;
  facility_id: string;
  performed_at: string;
  performed_by?: string;
  snapshot?: string;
  tenant_id: string;
}
