/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * WMS API
 * Warehouse Management System API
 * OpenAPI spec version: 1.0.0
 */

export interface DefectCodeDto {
  category: string;
  code: string;
  created_at: string;
  created_by: string;
  defect_code_id: number;
  description: string;
  is_active: boolean;
  severity: string;
  tenant_id: string;
  updated_at: string;
  updated_by: string;
}
