/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * WMS API
 * Warehouse Management System API
 * OpenAPI spec version: 1.0.0
 */
import type { EquipmentMaintenanceDtoCreatedAt } from './equipmentMaintenanceDtoCreatedAt.js';
import type { EquipmentMaintenanceDtoCreatedBy } from './equipmentMaintenanceDtoCreatedBy.js';
import type { EquipmentMaintenanceDtoDescription } from './equipmentMaintenanceDtoDescription.js';
import type { EquipmentMaintenanceDtoDurationMinutes } from './equipmentMaintenanceDtoDurationMinutes.js';
import type { EquipmentMaintenanceDtoMaintenanceCost } from './equipmentMaintenanceDtoMaintenanceCost.js';
import type { EquipmentMaintenanceDtoNextMaintenanceDate } from './equipmentMaintenanceDtoNextMaintenanceDate.js';
import type { EquipmentMaintenanceDtoNotes } from './equipmentMaintenanceDtoNotes.js';
import type { EquipmentMaintenanceDtoPerformedByUserId } from './equipmentMaintenanceDtoPerformedByUserId.js';
import type { EquipmentMaintenanceDtoTechnicianName } from './equipmentMaintenanceDtoTechnicianName.js';
import type { EquipmentMaintenanceDtoUpdatedAt } from './equipmentMaintenanceDtoUpdatedAt.js';
import type { EquipmentMaintenanceDtoUpdatedBy } from './equipmentMaintenanceDtoUpdatedBy.js';
import type { EquipmentMaintenanceDtoVersion } from './equipmentMaintenanceDtoVersion.js';

export interface EquipmentMaintenanceDto {
  created_at?: EquipmentMaintenanceDtoCreatedAt;
  created_by?: EquipmentMaintenanceDtoCreatedBy;
  description?: EquipmentMaintenanceDtoDescription;
  duration_minutes?: EquipmentMaintenanceDtoDurationMinutes;
  equipment_id: number;
  equipment_name: string;
  facility_id: number;
  facility_name: string;
  maintenance_cost?: EquipmentMaintenanceDtoMaintenanceCost;
  maintenance_date: string;
  maintenance_id: number;
  maintenance_type: string;
  next_maintenance_date?: EquipmentMaintenanceDtoNextMaintenanceDate;
  notes?: EquipmentMaintenanceDtoNotes;
  performed_by_user_id?: EquipmentMaintenanceDtoPerformedByUserId;
  status: string;
  technician_name?: EquipmentMaintenanceDtoTechnicianName;
  tenant_id: string;
  updated_at?: EquipmentMaintenanceDtoUpdatedAt;
  updated_by?: EquipmentMaintenanceDtoUpdatedBy;
  version?: EquipmentMaintenanceDtoVersion;
}
