/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * WMS API
 * Warehouse Management System API
 * OpenAPI spec version: 1.0.0
 */
import type { ExternalEntityMappingDtoMetadata } from './externalEntityMappingDtoMetadata.js';

export interface ExternalEntityMappingDto {
  created_at?: string;
  external_entity_id?: string;
  external_entity_type?: string;
  mapping_id?: string;
  metadata?: ExternalEntityMappingDtoMetadata;
  platform?: string;
  tenant_id?: string;
  updated_at?: string;
  wms_entity_id?: number;
  wms_entity_type?: string;
}
