/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * WMS API
 * Warehouse Management System API
 * OpenAPI spec version: 1.0.0
 */
import type { FacilitySummaryEntryDto } from './facilitySummaryEntryDto.js';

export interface FacilitySummaryDto {
  facilities: FacilitySummaryEntryDto[];
  total: number;
}
