/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * WMS API
 * Warehouse Management System API
 * OpenAPI spec version: 1.0.0
 */

export interface FacilityUserResponseDto {
  assigned_at: string;
  assigned_by?: string;
  assignment_id: number;
  created_at: string;
  created_by?: string;
  facility_id: number;
  is_active: boolean;
  notes?: string;
  tenant_id: string;
  unassigned_at?: string;
  unassigned_by?: string;
  updated_at: string;
  updated_by?: string;
  user_email?: string;
  user_id: string;
  user_name?: string;
  version?: number;
}
