/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * WMS API
 * Warehouse Management System API
 * OpenAPI spec version: 1.0.0
 */
import type { GoodsReceiptResponseDtoAsnNumber } from './goodsReceiptResponseDtoAsnNumber.js';
import type { GoodsReceiptResponseDtoClientName } from './goodsReceiptResponseDtoClientName.js';
import type { GoodsReceiptResponseDtoCreatedAt } from './goodsReceiptResponseDtoCreatedAt.js';
import type { GoodsReceiptResponseDtoCreatedBy } from './goodsReceiptResponseDtoCreatedBy.js';
import type { GoodsReceiptResponseDtoDescription } from './goodsReceiptResponseDtoDescription.js';
import type { GoodsReceiptResponseDtoExpectedDate } from './goodsReceiptResponseDtoExpectedDate.js';
import type { GoodsReceiptResponseDtoFacilityName } from './goodsReceiptResponseDtoFacilityName.js';
import type { GoodsReceiptResponseDtoInboundForClientId } from './goodsReceiptResponseDtoInboundForClientId.js';
import type { GoodsReceiptResponseDtoNotes } from './goodsReceiptResponseDtoNotes.js';
import type { GoodsReceiptResponseDtoPoNumber } from './goodsReceiptResponseDtoPoNumber.js';
import type { GoodsReceiptResponseDtoQcCompletedAt } from './goodsReceiptResponseDtoQcCompletedAt.js';
import type { GoodsReceiptResponseDtoQcCompletedByUserId } from './goodsReceiptResponseDtoQcCompletedByUserId.js';
import type { GoodsReceiptResponseDtoQcFailureReason } from './goodsReceiptResponseDtoQcFailureReason.js';
import type { GoodsReceiptResponseDtoQcRequired } from './goodsReceiptResponseDtoQcRequired.js';
import type { GoodsReceiptResponseDtoQcResult } from './goodsReceiptResponseDtoQcResult.js';
import type { GoodsReceiptResponseDtoQcStatusSummary } from './goodsReceiptResponseDtoQcStatusSummary.js';
import type { GoodsReceiptResponseDtoReceiptName } from './goodsReceiptResponseDtoReceiptName.js';
import type { GoodsReceiptResponseDtoReceivedDate } from './goodsReceiptResponseDtoReceivedDate.js';
import type { GoodsReceiptResponseDtoStatusChangedAt } from './goodsReceiptResponseDtoStatusChangedAt.js';
import type { GoodsReceiptResponseDtoStatusChangedBy } from './goodsReceiptResponseDtoStatusChangedBy.js';
import type { GoodsReceiptResponseDtoTotalVolume } from './goodsReceiptResponseDtoTotalVolume.js';
import type { GoodsReceiptResponseDtoTotalWeight } from './goodsReceiptResponseDtoTotalWeight.js';
import type { GoodsReceiptResponseDtoUpdatedAt } from './goodsReceiptResponseDtoUpdatedAt.js';
import type { GoodsReceiptResponseDtoUpdatedBy } from './goodsReceiptResponseDtoUpdatedBy.js';
import type { GoodsReceiptResponseDtoVendorId } from './goodsReceiptResponseDtoVendorId.js';
import type { GoodsReceiptResponseDtoVendorName } from './goodsReceiptResponseDtoVendorName.js';
import type { GoodsReceiptResponseDtoVersion } from './goodsReceiptResponseDtoVersion.js';

export interface GoodsReceiptResponseDto {
  asn_number?: GoodsReceiptResponseDtoAsnNumber;
  client_name?: GoodsReceiptResponseDtoClientName;
  created_at?: GoodsReceiptResponseDtoCreatedAt;
  created_by?: GoodsReceiptResponseDtoCreatedBy;
  description?: GoodsReceiptResponseDtoDescription;
  expected_date?: GoodsReceiptResponseDtoExpectedDate;
  facility_id: number;
  facility_name?: GoodsReceiptResponseDtoFacilityName;
  inbound_for_client_id?: GoodsReceiptResponseDtoInboundForClientId;
  notes?: GoodsReceiptResponseDtoNotes;
  po_number?: GoodsReceiptResponseDtoPoNumber;
  qc_completed_at?: GoodsReceiptResponseDtoQcCompletedAt;
  qc_completed_by_user_id?: GoodsReceiptResponseDtoQcCompletedByUserId;
  qc_failure_reason?: GoodsReceiptResponseDtoQcFailureReason;
  qc_required?: GoodsReceiptResponseDtoQcRequired;
  qc_result?: GoodsReceiptResponseDtoQcResult;
  qc_status_summary?: GoodsReceiptResponseDtoQcStatusSummary;
  receipt_id: number;
  receipt_name?: GoodsReceiptResponseDtoReceiptName;
  receipt_number: string;
  received_date?: GoodsReceiptResponseDtoReceivedDate;
  status: string;
  status_changed_at?: GoodsReceiptResponseDtoStatusChangedAt;
  status_changed_by?: GoodsReceiptResponseDtoStatusChangedBy;
  tenant_id: string;
  total_volume?: GoodsReceiptResponseDtoTotalVolume;
  total_weight?: GoodsReceiptResponseDtoTotalWeight;
  updated_at?: GoodsReceiptResponseDtoUpdatedAt;
  updated_by?: GoodsReceiptResponseDtoUpdatedBy;
  vendor_id?: GoodsReceiptResponseDtoVendorId;
  vendor_name?: GoodsReceiptResponseDtoVendorName;
  version?: GoodsReceiptResponseDtoVersion;
}
