/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * WMS API
 * Warehouse Management System API
 * OpenAPI spec version: 1.0.0
 */
import type { LocationExceptionDtoLocationName } from './locationExceptionDtoLocationName.js';
import type { LocationExceptionDtoNotes } from './locationExceptionDtoNotes.js';
import type { LocationExceptionDtoReportedAt } from './locationExceptionDtoReportedAt.js';
import type { LocationExceptionDtoReportedBy } from './locationExceptionDtoReportedBy.js';
import type { LocationExceptionDtoResolvedAt } from './locationExceptionDtoResolvedAt.js';

export interface LocationExceptionDto {
  exception_id: number;
  exception_type: string;
  location_id: number;
  location_name?: LocationExceptionDtoLocationName;
  notes?: LocationExceptionDtoNotes;
  reported_at?: LocationExceptionDtoReportedAt;
  reported_by?: LocationExceptionDtoReportedBy;
  resolved_at?: LocationExceptionDtoResolvedAt;
  tenant_id: string;
}
