/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * WMS API
 * Warehouse Management System API
 * OpenAPI spec version: 1.0.0
 */
import type { LookupPoResponseDtoLinesItem } from './lookupPoResponseDtoLinesItem.js';
import type { LookupPoResponseDtoPo } from './lookupPoResponseDtoPo.js';

export interface LookupPoResponseDto {
  lines: LookupPoResponseDtoLinesItem[];
  po: LookupPoResponseDtoPo;
}
