/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * WMS API
 * Warehouse Management System API
 * OpenAPI spec version: 1.0.0
 */
import type { ProductResponseDtoBarcodes } from './productResponseDtoBarcodes.js';
import type { ProductResponseDtoPackaging } from './productResponseDtoPackaging.js';
import type { ProductResponseDtoSuppliers } from './productResponseDtoSuppliers.js';
import type { ProductResponseDtoVariants } from './productResponseDtoVariants.js';

export interface ProductResponseDto {
  abc_analysis_class?: string;
  barcodes?: ProductResponseDtoBarcodes;
  base_price?: number;
  brand_id?: number;
  brand_name?: string;
  cases_per_pallet?: number;
  category_id: number;
  category_name: string;
  cost_price?: number;
  created_at?: string;
  created_by?: string;
  default_cycle_count_frequency_days?: number;
  description?: string;
  eaches_per_case?: number;
  hazmat_class?: string;
  hazmat_description?: string;
  height?: number;
  image_gallery_urls?: string[];
  is_active: boolean;
  is_hazardous: boolean;
  is_perishable: boolean;
  is_sensitive: boolean;
  last_counted_at?: string;
  length?: number;
  next_count_due_at?: string;
  packaging?: ProductResponseDtoPackaging;
  preferred_pick_uom?: string;
  primary_image_url?: string;
  primary_uom_id: number;
  product_code: string;
  product_id: number;
  product_name: string;
  requires_humidity_control: boolean;
  requires_light_control: boolean;
  requires_temperature_control: boolean;
  sensitivity_level?: string;
  shelf_life_days?: number;
  short_description?: string;
  storage_temperature_max?: number;
  storage_temperature_min?: number;
  suppliers?: ProductResponseDtoSuppliers;
  thumbnail_image_url?: string;
  track_expiry?: boolean;
  track_lot_numbers: boolean;
  track_serial_numbers: boolean;
  uom_name: string;
  updated_at?: string;
  updated_by?: string;
  variants?: ProductResponseDtoVariants;
  version?: number;
  volume?: number;
  weight?: number;
  width?: number;
}
