/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * WMS API
 * Warehouse Management System API
 * OpenAPI spec version: 1.0.0
 */
import type { PutawaySuggestResultDtoVelocityClass } from './putawaySuggestResultDtoVelocityClass.js';
import type { PutawaySuggestResultDtoZoneId } from './putawaySuggestResultDtoZoneId.js';

export interface PutawaySuggestResultDto {
  checkDigit: string;
  locationCode: string;
  locationId: string;
  locationTier: string;
  locationType: string;
  ruleCode: string;
  ruleName: string;
  velocityClass?: PutawaySuggestResultDtoVelocityClass;
  zoneId?: PutawaySuggestResultDtoZoneId;
}
