/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * WMS API
 * Warehouse Management System API
 * OpenAPI spec version: 1.0.0
 */
import type { RfGetNextPackWorkResponseDtoCartonPlan } from './rfGetNextPackWorkResponseDtoCartonPlan.js';
import type { RfGetNextPackWorkResponseDtoOrder } from './rfGetNextPackWorkResponseDtoOrder.js';
import type { RfGetNextPackWorkResponseDtoPickLpnsItem } from './rfGetNextPackWorkResponseDtoPickLpnsItem.js';

export interface RfGetNextPackWorkResponseDto {
  cartonPlan?: RfGetNextPackWorkResponseDtoCartonPlan;
  order?: RfGetNextPackWorkResponseDtoOrder;
  pickLpns?: RfGetNextPackWorkResponseDtoPickLpnsItem[];
}
