/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * WMS API
 * Warehouse Management System API
 * OpenAPI spec version: 1.0.0
 */
import type { RfGetNextStagingResponseDtoCarton } from './rfGetNextStagingResponseDtoCarton.js';
import type { RfGetNextStagingResponseDtoSuggestedLane } from './rfGetNextStagingResponseDtoSuggestedLane.js';

export interface RfGetNextStagingResponseDto {
  carton?: RfGetNextStagingResponseDtoCarton;
  suggestedLane?: RfGetNextStagingResponseDtoSuggestedLane;
}
