/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * WMS API
 * Warehouse Management System API
 * OpenAPI spec version: 1.0.0
 */

export interface RfRecordResultRequestDto {
  defect_code_id?: number;
  failure_reason?: string;
  notes?: string;
  quantity_affected?: number;
  result_status?: string;
}
