/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * WMS API
 * Warehouse Management System API
 * OpenAPI spec version: 1.0.0
 */

export interface RfReportDamageDto {
  damage_code_id?: string;
  damage_notes?: string;
  damage_quantity?: number;
  lpn_barcode?: string;
  notes?: string;
  task_id: string;
  user_id?: string;
}
