/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * WMS API
 * Warehouse Management System API
 * OpenAPI spec version: 1.0.0
 */
import type { RfReplenishmentScanProductResponseDtoResult } from './rfReplenishmentScanProductResponseDtoResult.js';

export interface RfReplenishmentScanProductResponseDto {
  result?: RfReplenishmentScanProductResponseDtoResult;
}
