/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * WMS API
 * Warehouse Management System API
 * OpenAPI spec version: 1.0.0
 */
import type { RfSavePickStateDtoState } from './rfSavePickStateDtoState.js';

export interface RfSavePickStateDto {
  state?: RfSavePickStateDtoState;
  user_id?: string;
}
