/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * WMS API
 * Warehouse Management System API
 * OpenAPI spec version: 1.0.0
 */

export interface RfValidateCartonResponseDto {
  lpnId: string;
  lpnNumber: string;
  shipmentId?: string;
  status?: string;
  valid: boolean;
  weight?: string;
}
