/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * WMS API
 * Warehouse Management System API
 * OpenAPI spec version: 1.0.0
 */
import type { RfVerifyCartonResponseDtoExtraItem } from './rfVerifyCartonResponseDtoExtraItem.js';
import type { RfVerifyCartonResponseDtoMatchedItem } from './rfVerifyCartonResponseDtoMatchedItem.js';
import type { RfVerifyCartonResponseDtoMissingItem } from './rfVerifyCartonResponseDtoMissingItem.js';

export interface RfVerifyCartonResponseDto {
  extra?: RfVerifyCartonResponseDtoExtraItem[];
  isComplete: boolean;
  matched?: RfVerifyCartonResponseDtoMatchedItem[];
  missing?: RfVerifyCartonResponseDtoMissingItem[];
}
