/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * WMS API
 * Warehouse Management System API
 * OpenAPI spec version: 1.0.0
 */

export interface ShiftAssignmentResponseDto {
  assignment_date: string;
  assignment_id: number;
  created_at?: string;
  created_by?: string;
  facility_id: number;
  notes?: string;
  scheduled_end_time?: string;
  scheduled_start_time?: string;
  shift_id: number;
  status: string;
  tenant_id: string;
  updated_at?: string;
  updated_by?: string;
  user_id: string;
  version?: number;
}
