/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * WMS API
 * Warehouse Management System API
 * OpenAPI spec version: 1.0.0
 */

export interface TimeLogResponseDto {
  assignment_id: number;
  clock_in_time: string;
  clock_out_time: string;
  created_at: string;
  date_worked: string;
  facility_id: number;
  facility_name: string;
  net_worked_minutes: number;
  notes: string;
  status: string;
  tenant_id: string;
  time_log_id: number;
  total_break_minutes: number;
  total_worked_minutes: number;
  updated_at: string;
  user_id: string;
}
