/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * WMS API
 * Warehouse Management System API
 * OpenAPI spec version: 1.0.0
 */

export interface UpdateVasServiceDto {
  base_charge?: number;
  charge_type?: string;
  currency_code?: string;
  description?: string;
  is_active?: boolean;
  maximum_charge?: number;
  minimum_charge?: number;
  requires_approval?: boolean;
  service_category?: string;
  vas_name?: string;
}
