/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * WMS API
 * Warehouse Management System API
 * OpenAPI spec version: 1.0.0
 */

export interface UpdateReturnDto {
  assigned_to_user_id?: string;
  notes?: string;
  reason_code?: string;
}
