/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * WMS API
 * Warehouse Management System API
 * OpenAPI spec version: 1.0.0
 */

export interface UpdateCrossDockDto {
  actual_arrival_time?: string;
  actual_departure_time?: string;
  assigned_to?: string;
  carrier_id?: string;
  cross_dock_number?: string;
  customer_order_id?: string;
  expected_arrival_time?: string;
  expected_departure_time?: string;
  inbound_shipment_id?: string;
  notes?: string;
  outbound_shipment_id?: string;
  priority?: string;
  product_id?: string;
  quantity?: number;
  receiving_dock_id?: string;
  shipping_dock_id?: string;
  sku?: string;
  staging_location_id?: string;
  status?: string;
  transfer_end_time?: string;
  transfer_start_time?: string;
  unit_of_measure?: string;
}
