/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * WMS API
 * Warehouse Management System API
 * OpenAPI spec version: 1.0.0
 */

export interface UpdateExceptionDto {
  assigned_to_user_id?: string;
  description?: string;
  exception_name?: string;
  exception_severity?: string;
  impact_level?: string;
  notes?: string;
  updated_by?: string;
}
