/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * WMS API
 * Warehouse Management System API
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateVasWorkstationDtoEquipmentJson } from './updateVasWorkstationDtoEquipmentJson.js';
import type { UpdateVasWorkstationDtoSupportedServices } from './updateVasWorkstationDtoSupportedServices.js';

export interface UpdateVasWorkstationDto {
  aisle?: string;
  equipment_json?: UpdateVasWorkstationDtoEquipmentJson;
  floor_level?: number;
  is_active?: boolean;
  max_concurrent_tasks?: number;
  station_type?: string;
  status?: string;
  supported_services?: UpdateVasWorkstationDtoSupportedServices;
  workstation_name?: string;
  zone_id?: string;
}
