/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * WMS API
 * Warehouse Management System API
 * OpenAPI spec version: 1.0.0
 */

export interface UpdateWorkOrderDto {
  assigned_to_user_id?: string;
  description?: string;
  notes?: string;
  priority?: number;
  scheduled_end_date?: string;
  scheduled_start_date?: string;
  work_order_name?: string;
  work_order_type?: string;
}
