/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * WMS API
 * Warehouse Management System API
 * OpenAPI spec version: 1.0.0
 */

export interface UpdateProductSupplierDto {
  cost_price?: number;
  currency_code?: string;
  is_active?: boolean;
  lead_time_days?: number;
  maximum_order_quantity?: number;
  minimum_order_quantity?: number;
  preferred_supplier?: boolean;
  supplier_part_number?: string;
}
