/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * WMS API
 * Warehouse Management System API
 * OpenAPI spec version: 1.0.0
 */

export interface UpdateInspectionProfileDto {
  checklist_items?: string[];
  description?: string;
  is_active?: boolean;
  profile_name?: string;
}
