/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * WMS API
 * Warehouse Management System API
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateCartonizationRuleDtoConditionsJson } from './updateCartonizationRuleDtoConditionsJson.js';

export interface UpdateCartonizationRuleDto {
  carton_type_id?: string;
  conditions_json?: UpdateCartonizationRuleDtoConditionsJson;
  is_active?: boolean;
  priority?: number;
  rule_name?: string;
}
