/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * WMS API
 * Warehouse Management System API
 * OpenAPI spec version: 1.0.0
 */

export interface UpdateHoldDto {
  facility_id?: string;
  hold_reason?: string;
  hold_reason_code?: string;
  hold_reason_description?: string;
  inventory_item_id?: string;
  lpn_id?: string;
  notes?: string;
}
