/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * WMS API
 * Warehouse Management System API
 * OpenAPI spec version: 1.0.0
 */

export interface UpdatePurchaseOrderDto {
  assigned_buyer_id?: string;
  description?: string;
  expected_receipt_date?: string;
  notes?: string;
  po_name?: string;
  promised_date?: string;
  required_date?: string;
}
