/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * WMS API
 * Warehouse Management System API
 * OpenAPI spec version: 1.0.0
 */

export interface UpdateQualityHoldDto {
  affected_quantity?: number;
  description?: string;
  hold_name?: string;
  hold_reason?: string;
  hold_reason_code?: string;
  notes?: string;
  status?: string;
  uom_id?: string;
}
