/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * WMS API
 * Warehouse Management System API
 * OpenAPI spec version: 1.0.0
 */

export interface UpdateShippingRouteDto {
  description?: string;
  is_active?: boolean;
  origin_facility_id?: string;
  route_code?: string;
}
