/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * WMS API
 * Warehouse Management System API
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateRuleDtoDefinitionJson } from './updateRuleDtoDefinitionJson.js';

export interface UpdateRuleDto {
  definition_json?: UpdateRuleDtoDefinitionJson;
  is_active?: boolean;
  name?: string;
}
