/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * WMS API
 * Warehouse Management System API
 * OpenAPI spec version: 1.0.0
 */

export interface UpdateLpnDto {
  assigned_load_id?: string;
  assigned_shipment_id?: string;
  facility_id?: string;
  grn_line_id?: string;
  gross_weight?: number;
  loaded_at?: string;
  location_id?: string;
  lpn_number?: string;
  lpn_type?: string;
  net_weight?: number;
  parent_lpn_id?: string;
  product_id?: string;
  staged_at?: string;
  staging_location_id?: string;
  status?: string;
  volume?: number;
}
