/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * WMS API
 * Warehouse Management System API
 * OpenAPI spec version: 1.0.0
 */

export interface UpdateTrailerDto {
  arrival_time?: string;
  assigned_dock_id?: string;
  assigned_load_id?: string;
  carrier_id?: string;
  departure_time?: string;
  is_active?: boolean;
  max_cartons?: number;
  max_pallets?: number;
  max_volume_cbm?: number;
  max_weight_kg?: number;
  notes?: string;
  seal_number?: string;
  status?: string;
  trailer_number?: string;
  trailer_type?: string;
}
