/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * WMS API
 * Warehouse Management System API
 * OpenAPI spec version: 1.0.0
 */

export interface UpdatePickCartAssignmentDto {
  assignment_order?: number;
  session_id?: string;
  shelf_position?: string;
  tote_barcode?: string;
  tote_lpn_id?: string;
}
