/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * WMS API
 * Warehouse Management System API
 * OpenAPI spec version: 1.0.0
 */

export interface VarianceInvestigationResponseDto {
  accuracy_history_id?: string;
  assigned_at?: string;
  assigned_to?: string;
  assigned_to_name?: string;
  corrective_action?: string;
  count_id: string;
  count_number?: string;
  counted_quantity: number;
  created_at?: string;
  created_by?: string;
  days_to_resolve?: number;
  facility_id: string;
  facility_name?: string;
  investigated_at?: string;
  investigated_by?: string;
  investigated_by_name?: string;
  investigation_id: string;
  investigation_notes?: string;
  is_recurring_variance?: boolean;
  location_code?: string;
  location_id?: string;
  location_name?: string;
  occurrences_last_30_days?: number;
  occurrences_last_90_days?: number;
  priority?: string;
  product_id: string;
  product_name?: string;
  product_sku?: string;
  resolved_at?: string;
  root_cause?: string;
  status: string;
  system_quantity: number;
  tenant_id: string;
  updated_at?: string;
  updated_by?: string;
  variance_percentage: number;
  variance_quantity: number;
  variance_reason?: string;
  version?: number;
}
