/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * WMS API
 * Warehouse Management System API
 * OpenAPI spec version: 1.0.0
 */
import type { WorkOrderOperationResponseDtoAssignedToUserId } from './workOrderOperationResponseDtoAssignedToUserId.js';
import type { WorkOrderOperationResponseDtoCompletedAt } from './workOrderOperationResponseDtoCompletedAt.js';
import type { WorkOrderOperationResponseDtoCreatedBy } from './workOrderOperationResponseDtoCreatedBy.js';
import type { WorkOrderOperationResponseDtoDescription } from './workOrderOperationResponseDtoDescription.js';
import type { WorkOrderOperationResponseDtoNotes } from './workOrderOperationResponseDtoNotes.js';
import type { WorkOrderOperationResponseDtoRequiredEquipmentType } from './workOrderOperationResponseDtoRequiredEquipmentType.js';
import type { WorkOrderOperationResponseDtoRequiredSkillSet } from './workOrderOperationResponseDtoRequiredSkillSet.js';
import type { WorkOrderOperationResponseDtoStandardTimeMinutes } from './workOrderOperationResponseDtoStandardTimeMinutes.js';
import type { WorkOrderOperationResponseDtoStartedAt } from './workOrderOperationResponseDtoStartedAt.js';
import type { WorkOrderOperationResponseDtoUpdatedBy } from './workOrderOperationResponseDtoUpdatedBy.js';
import type { WorkOrderOperationResponseDtoVersion } from './workOrderOperationResponseDtoVersion.js';

export interface WorkOrderOperationResponseDto {
  assigned_to_user_id?: WorkOrderOperationResponseDtoAssignedToUserId;
  completed_at?: WorkOrderOperationResponseDtoCompletedAt;
  created_at: string;
  created_by?: WorkOrderOperationResponseDtoCreatedBy;
  description?: WorkOrderOperationResponseDtoDescription;
  facility_id: number;
  notes?: WorkOrderOperationResponseDtoNotes;
  operation_id: number;
  operation_name: string;
  operation_number: number;
  required_equipment_type?: WorkOrderOperationResponseDtoRequiredEquipmentType;
  required_skill_set?: WorkOrderOperationResponseDtoRequiredSkillSet;
  standard_time_minutes?: WorkOrderOperationResponseDtoStandardTimeMinutes;
  started_at?: WorkOrderOperationResponseDtoStartedAt;
  status: string;
  tenant_id: string;
  updated_at: string;
  updated_by?: WorkOrderOperationResponseDtoUpdatedBy;
  version?: WorkOrderOperationResponseDtoVersion;
  work_order_id: number;
}
