/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * WMS API
 * Warehouse Management System API
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  PaginatedResponseDto,
  TimeLogResponseDto
} from '../../../types/wms-api';

import { customInstance } from '../../../http/httpClient.js';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type TimeTrackingController_findAllResponse200 = {
  data: PaginatedResponseDto
  status: 200
}

export type TimeTrackingController_findAllResponseSuccess = (TimeTrackingController_findAllResponse200) & {
  headers: Headers;
};
;

export type TimeTrackingController_findAllResponse = (TimeTrackingController_findAllResponseSuccess)

export const getTimeTrackingControllerFindAllUrl = () => {




  return `/api/v1/wms/web/labor/time-logs`
}

/**
 * @summary List time logs
 */
export const TimeTrackingController_findAll = async ( options?: RequestInit): Promise<TimeTrackingController_findAllResponse> => {

  return customInstance<TimeTrackingController_findAllResponse>(getTimeTrackingControllerFindAllUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getTimeTrackingControllerFindAllMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof TimeTrackingController_findAll>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof TimeTrackingController_findAll>>, TError,void, TContext> => {

const mutationKey = ['timeTrackingControllerFindAll'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof TimeTrackingController_findAll>>, void> = () => {


          return  TimeTrackingController_findAll(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type TimeTrackingControllerFindAllMutationResult = NonNullable<Awaited<ReturnType<typeof TimeTrackingController_findAll>>>

    export type TimeTrackingControllerFindAllMutationError = unknown

    /**
 * @summary List time logs
 */
export const useTimeTrackingControllerFindAll = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof TimeTrackingController_findAll>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof TimeTrackingController_findAll>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getTimeTrackingControllerFindAllMutationOptions(options));
    }
    export type TimeTrackingController_deleteResponse200 = {
  data: TimeLogResponseDto
  status: 200
}

export type TimeTrackingController_deleteResponseSuccess = (TimeTrackingController_deleteResponse200) & {
  headers: Headers;
};
;

export type TimeTrackingController_deleteResponse = (TimeTrackingController_deleteResponseSuccess)

export const getTimeTrackingControllerDeleteUrl = (id: string,) => {




  return `/api/v1/wms/web/labor/time-logs/${id}`
}

/**
 * @summary Delete time log
 */
export const TimeTrackingController_delete = async (id: string, options?: RequestInit): Promise<TimeTrackingController_deleteResponse> => {

  return customInstance<TimeTrackingController_deleteResponse>(getTimeTrackingControllerDeleteUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getTimeTrackingControllerDeleteQueryKey = (id: string,) => {
    return [
    'DELETE', `/api/v1/wms/web/labor/time-logs/${id}`
    ] as const;
    }


export const getTimeTrackingControllerDeleteQueryOptions = <TData = Awaited<ReturnType<typeof TimeTrackingController_delete>>, TError = unknown>(id: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof TimeTrackingController_delete>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getTimeTrackingControllerDeleteQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof TimeTrackingController_delete>>> = ({ signal }) => TimeTrackingController_delete(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof TimeTrackingController_delete>>, TError, TData> & { queryKey: QueryKey }
}

export type TimeTrackingControllerDeleteQueryResult = NonNullable<Awaited<ReturnType<typeof TimeTrackingController_delete>>>
export type TimeTrackingControllerDeleteQueryError = unknown


/**
 * @summary Delete time log
 */

export function useTimeTrackingControllerDelete<TData = Awaited<ReturnType<typeof TimeTrackingController_delete>>, TError = unknown>(
 id: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof TimeTrackingController_delete>>, TError, TData>, request?: SecondParameter<typeof customInstance>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getTimeTrackingControllerDeleteQueryOptions(id,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}






