/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * WMS API
 * Warehouse Management System API
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AuditLogResponseDto,
  PaginatedResponseDto,
  WarehouseEventResponseDto
} from '../../../types/wms-api';

import { customInstance } from '../../../http/httpClient.js';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type EventsController_findAllResponse200 = {
  data: PaginatedResponseDto
  status: 200
}

export type EventsController_findAllResponseSuccess = (EventsController_findAllResponse200) & {
  headers: Headers;
};
;

export type EventsController_findAllResponse = (EventsController_findAllResponseSuccess)

export const getEventsControllerFindAllUrl = () => {




  return `/api/v1/wms/web/events`
}

/**
 * @summary List warehouse events (filterable by type, severity, objectType, dateRange)
 */
export const EventsController_findAll = async ( options?: RequestInit): Promise<EventsController_findAllResponse> => {

  return customInstance<EventsController_findAllResponse>(getEventsControllerFindAllUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getEventsControllerFindAllMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof EventsController_findAll>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof EventsController_findAll>>, TError,void, TContext> => {

const mutationKey = ['eventsControllerFindAll'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof EventsController_findAll>>, void> = () => {


          return  EventsController_findAll(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type EventsControllerFindAllMutationResult = NonNullable<Awaited<ReturnType<typeof EventsController_findAll>>>

    export type EventsControllerFindAllMutationError = unknown

    /**
 * @summary List warehouse events (filterable by type, severity, objectType, dateRange)
 */
export const useEventsControllerFindAll = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof EventsController_findAll>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof EventsController_findAll>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getEventsControllerFindAllMutationOptions(options));
    }
    export type EventsController_findByIdResponse200 = {
  data: WarehouseEventResponseDto
  status: 200
}

export type EventsController_findByIdResponseSuccess = (EventsController_findByIdResponse200) & {
  headers: Headers;
};
;

export type EventsController_findByIdResponse = (EventsController_findByIdResponseSuccess)

export const getEventsControllerFindByIdUrl = (id: string,) => {




  return `/api/v1/wms/web/events/${id}`
}

/**
 * @summary Get warehouse event by ID
 */
export const EventsController_findById = async (id: string, options?: RequestInit): Promise<EventsController_findByIdResponse> => {

  return customInstance<EventsController_findByIdResponse>(getEventsControllerFindByIdUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getEventsControllerFindByIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof EventsController_findById>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof EventsController_findById>>, TError,{id: string}, TContext> => {

const mutationKey = ['eventsControllerFindById'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof EventsController_findById>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  EventsController_findById(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type EventsControllerFindByIdMutationResult = NonNullable<Awaited<ReturnType<typeof EventsController_findById>>>

    export type EventsControllerFindByIdMutationError = unknown

    /**
 * @summary Get warehouse event by ID
 */
export const useEventsControllerFindById = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof EventsController_findById>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof EventsController_findById>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getEventsControllerFindByIdMutationOptions(options));
    }
    export type EventsController_deleteResponse200 = {
  data: WarehouseEventResponseDto
  status: 200
}

export type EventsController_deleteResponseSuccess = (EventsController_deleteResponse200) & {
  headers: Headers;
};
;

export type EventsController_deleteResponse = (EventsController_deleteResponseSuccess)

export const getEventsControllerDeleteUrl = (id: string,) => {




  return `/api/v1/wms/web/events/${id}`
}

/**
 * @summary Delete warehouse event
 */
export const EventsController_delete = async (id: string, options?: RequestInit): Promise<EventsController_deleteResponse> => {

  return customInstance<EventsController_deleteResponse>(getEventsControllerDeleteUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getEventsControllerDeleteQueryKey = (id: string,) => {
    return [
    'DELETE', `/api/v1/wms/web/events/${id}`
    ] as const;
    }


export const getEventsControllerDeleteQueryOptions = <TData = Awaited<ReturnType<typeof EventsController_delete>>, TError = unknown>(id: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof EventsController_delete>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getEventsControllerDeleteQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof EventsController_delete>>> = ({ signal }) => EventsController_delete(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof EventsController_delete>>, TError, TData> & { queryKey: QueryKey }
}

export type EventsControllerDeleteQueryResult = NonNullable<Awaited<ReturnType<typeof EventsController_delete>>>
export type EventsControllerDeleteQueryError = unknown


/**
 * @summary Delete warehouse event
 */

export function useEventsControllerDelete<TData = Awaited<ReturnType<typeof EventsController_delete>>, TError = unknown>(
 id: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof EventsController_delete>>, TError, TData>, request?: SecondParameter<typeof customInstance>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getEventsControllerDeleteQueryOptions(id,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}






export type AuditController_findAllResponse200 = {
  data: PaginatedResponseDto
  status: 200
}

export type AuditController_findAllResponseSuccess = (AuditController_findAllResponse200) & {
  headers: Headers;
};
;

export type AuditController_findAllResponse = (AuditController_findAllResponseSuccess)

export const getAuditControllerFindAllUrl = () => {




  return `/api/v1/wms/web/audit-logs`
}

/**
 * @summary List audit logs (filterable by action, tableName, userId, dateRange)
 */
export const AuditController_findAll = async ( options?: RequestInit): Promise<AuditController_findAllResponse> => {

  return customInstance<AuditController_findAllResponse>(getAuditControllerFindAllUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getAuditControllerFindAllMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof AuditController_findAll>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof AuditController_findAll>>, TError,void, TContext> => {

const mutationKey = ['auditControllerFindAll'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof AuditController_findAll>>, void> = () => {


          return  AuditController_findAll(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AuditControllerFindAllMutationResult = NonNullable<Awaited<ReturnType<typeof AuditController_findAll>>>

    export type AuditControllerFindAllMutationError = unknown

    /**
 * @summary List audit logs (filterable by action, tableName, userId, dateRange)
 */
export const useAuditControllerFindAll = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof AuditController_findAll>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof AuditController_findAll>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getAuditControllerFindAllMutationOptions(options));
    }
    export type AuditController_findByIdResponse200 = {
  data: AuditLogResponseDto
  status: 200
}

export type AuditController_findByIdResponseSuccess = (AuditController_findByIdResponse200) & {
  headers: Headers;
};
;

export type AuditController_findByIdResponse = (AuditController_findByIdResponseSuccess)

export const getAuditControllerFindByIdUrl = (id: string,) => {




  return `/api/v1/wms/web/audit-logs/${id}`
}

/**
 * @summary Get audit log detail by ID
 */
export const AuditController_findById = async (id: string, options?: RequestInit): Promise<AuditController_findByIdResponse> => {

  return customInstance<AuditController_findByIdResponse>(getAuditControllerFindByIdUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getAuditControllerFindByIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof AuditController_findById>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof AuditController_findById>>, TError,{id: string}, TContext> => {

const mutationKey = ['auditControllerFindById'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof AuditController_findById>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  AuditController_findById(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AuditControllerFindByIdMutationResult = NonNullable<Awaited<ReturnType<typeof AuditController_findById>>>

    export type AuditControllerFindByIdMutationError = unknown

    /**
 * @summary Get audit log detail by ID
 */
export const useAuditControllerFindById = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof AuditController_findById>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof AuditController_findById>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getAuditControllerFindByIdMutationOptions(options));
    }
    export type AuditController_deleteResponse200 = {
  data: AuditLogResponseDto
  status: 200
}

export type AuditController_deleteResponseSuccess = (AuditController_deleteResponse200) & {
  headers: Headers;
};
;

export type AuditController_deleteResponse = (AuditController_deleteResponseSuccess)

export const getAuditControllerDeleteUrl = (id: string,) => {




  return `/api/v1/wms/web/audit-logs/${id}`
}

/**
 * @summary Delete audit log
 */
export const AuditController_delete = async (id: string, options?: RequestInit): Promise<AuditController_deleteResponse> => {

  return customInstance<AuditController_deleteResponse>(getAuditControllerDeleteUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getAuditControllerDeleteQueryKey = (id: string,) => {
    return [
    'DELETE', `/api/v1/wms/web/audit-logs/${id}`
    ] as const;
    }


export const getAuditControllerDeleteQueryOptions = <TData = Awaited<ReturnType<typeof AuditController_delete>>, TError = unknown>(id: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof AuditController_delete>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAuditControllerDeleteQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof AuditController_delete>>> = ({ signal }) => AuditController_delete(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof AuditController_delete>>, TError, TData> & { queryKey: QueryKey }
}

export type AuditControllerDeleteQueryResult = NonNullable<Awaited<ReturnType<typeof AuditController_delete>>>
export type AuditControllerDeleteQueryError = unknown


/**
 * @summary Delete audit log
 */

export function useAuditControllerDelete<TData = Awaited<ReturnType<typeof AuditController_delete>>, TError = unknown>(
 id: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof AuditController_delete>>, TError, TData>, request?: SecondParameter<typeof customInstance>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getAuditControllerDeleteQueryOptions(id,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}






