/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * ElasticWMS API
 * Warehouse Management System API - Web, RF, and Integration endpoints
 * OpenAPI spec version: 1.0.0
 */

export interface CreateCarrierDto {
  carrierCode: string;
  isActive?: boolean;
  name: string;
  phone?: string;
  scac?: string;
  website?: string;
}
