/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * ElasticWMS API
 * Warehouse Management System API - Web, RF, and Integration endpoints
 * OpenAPI spec version: 1.0.0
 */

export type CreateEquipmentDtoEquipmentType = typeof CreateEquipmentDtoEquipmentType[keyof typeof CreateEquipmentDtoEquipmentType];


export const CreateEquipmentDtoEquipmentType = {
  FORKLIFT: 'FORKLIFT',
  PALLET_JACK: 'PALLET_JACK',
  HAND_TRUCK: 'HAND_TRUCK',
  CONVEYOR: 'CONVEYOR',
  SCANNER: 'SCANNER',
  PRINTER: 'PRINTER',
} as const;
