/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * ElasticWMS API
 * Warehouse Management System API - Web, RF, and Integration endpoints
 * OpenAPI spec version: 1.0.0
 */

export type CreateOperationDtoOperationType = typeof CreateOperationDtoOperationType[keyof typeof CreateOperationDtoOperationType];


export const CreateOperationDtoOperationType = {
  TASK: 'TASK',
  QUALITY_CHECK: 'QUALITY_CHECK',
  MOVE: 'MOVE',
  LABEL: 'LABEL',
} as const;
