/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * ElasticWMS API
 * Warehouse Management System API - Web, RF, and Integration endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { CreateLoadingDockDtoDockType } from './createLoadingDockDtoDockType.js';

export interface CreateLoadingDockDto {
  description?: string;
  dockCode: string;
  dockName?: string;
  dockType?: CreateLoadingDockDtoDockType;
  facilityId: string;
  hasLeveler?: boolean;
  hasSealant?: boolean;
  isActive?: boolean;
  isAvailable?: boolean;
  locationId?: string;
  maxTrailerHeight?: number;
  maxTrailerLength?: number;
}
