/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * ElasticWMS API
 * Warehouse Management System API - Web, RF, and Integration endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { CreateReturnItemDto } from './createReturnItemDto.js';

export interface CreateCustomerReturnDto {
  carrier?: string;
  clientCode?: string;
  facilityId: string;
  items: CreateReturnItemDto[];
  notes?: string;
  returnNumber: string;
  rmaNumber?: string;
  trackingNumber?: string;
}
