/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * ElasticWMS API
 * Warehouse Management System API - Web, RF, and Integration endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { VendorAddressDto } from './vendorAddressDto.js';
import type { VendorContactDto } from './vendorContactDto.js';

export interface CreateVendorDto {
  addresses?: VendorAddressDto[];
  contacts?: VendorContactDto[];
  isActive?: boolean;
  name: string;
  vendorCode: string;
}
