/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * ElasticWMS API
 * Warehouse Management System API - Web, RF, and Integration endpoints
 * OpenAPI spec version: 1.0.0
 */

export type CreateReplenishmentTaskDtoPriority = typeof CreateReplenishmentTaskDtoPriority[keyof typeof CreateReplenishmentTaskDtoPriority];


export const CreateReplenishmentTaskDtoPriority = {
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
} as const;
