/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * ElasticWMS API
 * Warehouse Management System API - Web, RF, and Integration endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { RegisterVehicleDtoVehicleType } from './registerVehicleDtoVehicleType.js';

export interface RegisterVehicleDto {
  carrierCode?: string;
  driverName?: string;
  driverPhone?: string;
  facilityId: string;
  sealNumber?: string;
  vehiclePlate: string;
  vehicleType: RegisterVehicleDtoVehicleType;
  yardLocation?: string;
}
