/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * ElasticWMS API
 * Warehouse Management System API - Web, RF, and Integration endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateLpnDtoStatus } from './updateLpnDtoStatus.js';

export interface UpdateLpnDto {
  locationId?: string;
  lotNumber?: string;
  productId?: string;
  quantity?: number;
  status?: UpdateLpnDtoStatus;
}
