/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * ElasticWMS API
 * Warehouse Management System API - Web, RF, and Integration endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateZoneDtoAttributes } from './updateZoneDtoAttributes.js';
import type { UpdateZoneDtoZoneType } from './updateZoneDtoZoneType.js';

export interface UpdateZoneDto {
  attributes?: UpdateZoneDtoAttributes;
  facilityId?: string;
  isActive?: boolean;
  name?: string;
  zoneCode?: string;
  zoneType?: UpdateZoneDtoZoneType;
}
