/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * ElasticWMS API
 * Warehouse Management System API - Web, RF, and Integration endpoints
 * OpenAPI spec version: 1.0.0
 */

export interface UpdateClientAddressDto {
  addressLine1?: string;
  addressLine2?: string;
  addressType?: string;
  city?: string;
  countryCode?: string;
  isActive?: boolean;
  isDefault?: boolean;
  postalCode?: string;
  state?: string;
}
