/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * WMS API
 * Warehouse Management System API
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateReturnDto,
  DeleteResultDto,
  ReceiveReturnDto,
  ReturnDto,
  ReturnListResponseDto,
  UpdateReturnDto
} from '../../../types/wms-api';

import { customInstance } from '../../../http/httpClient.js';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type ReturnsController_createResponse201 = {
  data: ReturnDto
  status: 201
}

export type ReturnsController_createResponseSuccess = (ReturnsController_createResponse201) & {
  headers: Headers;
};
;

export type ReturnsController_createResponse = (ReturnsController_createResponseSuccess)

export const getReturnsControllerCreateUrl = () => {




  return `/api/v1/wms/web/customer-returns`
}

/**
 * @summary Create customer return with items
 */
export const ReturnsController_create = async (createReturnDto: CreateReturnDto, options?: RequestInit): Promise<ReturnsController_createResponse> => {

  return customInstance<ReturnsController_createResponse>(getReturnsControllerCreateUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createReturnDto)
  }
);}





export const getReturnsControllerCreateQueryKey = (createReturnDto?: CreateReturnDto,) => {
    return [
    'POST', `/api/v1/wms/web/customer-returns`, createReturnDto
    ] as const;
    }


export const getReturnsControllerCreateQueryOptions = <TData = Awaited<ReturnType<typeof ReturnsController_create>>, TError = unknown>(createReturnDto: CreateReturnDto, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof ReturnsController_create>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getReturnsControllerCreateQueryKey(createReturnDto);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof ReturnsController_create>>> = ({ signal }) => ReturnsController_create(createReturnDto, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof ReturnsController_create>>, TError, TData> & { queryKey: QueryKey }
}

export type ReturnsControllerCreateQueryResult = NonNullable<Awaited<ReturnType<typeof ReturnsController_create>>>
export type ReturnsControllerCreateQueryError = unknown


/**
 * @summary Create customer return with items
 */

export function useReturnsControllerCreate<TData = Awaited<ReturnType<typeof ReturnsController_create>>, TError = unknown>(
 createReturnDto: CreateReturnDto, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof ReturnsController_create>>, TError, TData>, request?: SecondParameter<typeof customInstance>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getReturnsControllerCreateQueryOptions(createReturnDto,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}






export type ReturnsController_findAllResponse200 = {
  data: ReturnListResponseDto
  status: 200
}

export type ReturnsController_findAllResponseSuccess = (ReturnsController_findAllResponse200) & {
  headers: Headers;
};
;

export type ReturnsController_findAllResponse = (ReturnsController_findAllResponseSuccess)

export const getReturnsControllerFindAllUrl = () => {




  return `/api/v1/wms/web/customer-returns`
}

/**
 * @summary List customer returns
 */
export const ReturnsController_findAll = async ( options?: RequestInit): Promise<ReturnsController_findAllResponse> => {

  return customInstance<ReturnsController_findAllResponse>(getReturnsControllerFindAllUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getReturnsControllerFindAllMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof ReturnsController_findAll>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof ReturnsController_findAll>>, TError,void, TContext> => {

const mutationKey = ['returnsControllerFindAll'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof ReturnsController_findAll>>, void> = () => {


          return  ReturnsController_findAll(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ReturnsControllerFindAllMutationResult = NonNullable<Awaited<ReturnType<typeof ReturnsController_findAll>>>

    export type ReturnsControllerFindAllMutationError = unknown

    /**
 * @summary List customer returns
 */
export const useReturnsControllerFindAll = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof ReturnsController_findAll>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof ReturnsController_findAll>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getReturnsControllerFindAllMutationOptions(options));
    }
    export type ReturnsController_findByIdResponse200 = {
  data: ReturnDto
  status: 200
}

export type ReturnsController_findByIdResponseSuccess = (ReturnsController_findByIdResponse200) & {
  headers: Headers;
};
;

export type ReturnsController_findByIdResponse = (ReturnsController_findByIdResponseSuccess)

export const getReturnsControllerFindByIdUrl = (id: string,) => {




  return `/api/v1/wms/web/customer-returns/${id}`
}

/**
 * @summary Get customer return with items
 */
export const ReturnsController_findById = async (id: string, options?: RequestInit): Promise<ReturnsController_findByIdResponse> => {

  return customInstance<ReturnsController_findByIdResponse>(getReturnsControllerFindByIdUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getReturnsControllerFindByIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof ReturnsController_findById>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof ReturnsController_findById>>, TError,{id: string}, TContext> => {

const mutationKey = ['returnsControllerFindById'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof ReturnsController_findById>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  ReturnsController_findById(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ReturnsControllerFindByIdMutationResult = NonNullable<Awaited<ReturnType<typeof ReturnsController_findById>>>

    export type ReturnsControllerFindByIdMutationError = unknown

    /**
 * @summary Get customer return with items
 */
export const useReturnsControllerFindById = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof ReturnsController_findById>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof ReturnsController_findById>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getReturnsControllerFindByIdMutationOptions(options));
    }
    export type ReturnsController_updateResponse200 = {
  data: ReturnDto
  status: 200
}

export type ReturnsController_updateResponseSuccess = (ReturnsController_updateResponse200) & {
  headers: Headers;
};
;

export type ReturnsController_updateResponse = (ReturnsController_updateResponseSuccess)

export const getReturnsControllerUpdateUrl = (id: string,) => {




  return `/api/v1/wms/web/customer-returns/${id}`
}

/**
 * @summary Update customer return
 */
export const ReturnsController_update = async (id: string,
    updateReturnDto: UpdateReturnDto, options?: RequestInit): Promise<ReturnsController_updateResponse> => {

  return customInstance<ReturnsController_updateResponse>(getReturnsControllerUpdateUrl(id),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateReturnDto)
  }
);}





export const getReturnsControllerUpdateQueryKey = (id: string,
    updateReturnDto?: UpdateReturnDto,) => {
    return [
    'PATCH', `/api/v1/wms/web/customer-returns/${id}`, updateReturnDto
    ] as const;
    }


export const getReturnsControllerUpdateQueryOptions = <TData = Awaited<ReturnType<typeof ReturnsController_update>>, TError = unknown>(id: string,
    updateReturnDto: UpdateReturnDto, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof ReturnsController_update>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getReturnsControllerUpdateQueryKey(id,updateReturnDto);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof ReturnsController_update>>> = ({ signal }) => ReturnsController_update(id,updateReturnDto, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof ReturnsController_update>>, TError, TData> & { queryKey: QueryKey }
}

export type ReturnsControllerUpdateQueryResult = NonNullable<Awaited<ReturnType<typeof ReturnsController_update>>>
export type ReturnsControllerUpdateQueryError = unknown


/**
 * @summary Update customer return
 */

export function useReturnsControllerUpdate<TData = Awaited<ReturnType<typeof ReturnsController_update>>, TError = unknown>(
 id: string,
    updateReturnDto: UpdateReturnDto, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof ReturnsController_update>>, TError, TData>, request?: SecondParameter<typeof customInstance>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getReturnsControllerUpdateQueryOptions(id,updateReturnDto,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}






export type ReturnsController_deleteResponse200 = {
  data: DeleteResultDto
  status: 200
}

export type ReturnsController_deleteResponseSuccess = (ReturnsController_deleteResponse200) & {
  headers: Headers;
};
;

export type ReturnsController_deleteResponse = (ReturnsController_deleteResponseSuccess)

export const getReturnsControllerDeleteUrl = (id: string,) => {




  return `/api/v1/wms/web/customer-returns/${id}`
}

/**
 * @summary Delete customer return
 */
export const ReturnsController_delete = async (id: string, options?: RequestInit): Promise<ReturnsController_deleteResponse> => {

  return customInstance<ReturnsController_deleteResponse>(getReturnsControllerDeleteUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getReturnsControllerDeleteQueryKey = (id: string,) => {
    return [
    'DELETE', `/api/v1/wms/web/customer-returns/${id}`
    ] as const;
    }


export const getReturnsControllerDeleteQueryOptions = <TData = Awaited<ReturnType<typeof ReturnsController_delete>>, TError = unknown>(id: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof ReturnsController_delete>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getReturnsControllerDeleteQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof ReturnsController_delete>>> = ({ signal }) => ReturnsController_delete(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof ReturnsController_delete>>, TError, TData> & { queryKey: QueryKey }
}

export type ReturnsControllerDeleteQueryResult = NonNullable<Awaited<ReturnType<typeof ReturnsController_delete>>>
export type ReturnsControllerDeleteQueryError = unknown


/**
 * @summary Delete customer return
 */

export function useReturnsControllerDelete<TData = Awaited<ReturnType<typeof ReturnsController_delete>>, TError = unknown>(
 id: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof ReturnsController_delete>>, TError, TData>, request?: SecondParameter<typeof customInstance>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getReturnsControllerDeleteQueryOptions(id,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}






export type ReturnsController_receiveReturnResponse201 = {
  data: ReturnDto
  status: 201
}

export type ReturnsController_receiveReturnResponseSuccess = (ReturnsController_receiveReturnResponse201) & {
  headers: Headers;
};
;

export type ReturnsController_receiveReturnResponse = (ReturnsController_receiveReturnResponseSuccess)

export const getReturnsControllerReceiveReturnUrl = (id: string,) => {




  return `/api/v1/wms/web/customer-returns/${id}/receive`
}

/**
 * @summary Receive returned items (creates inventory holds for QC)
 */
export const ReturnsController_receiveReturn = async (id: string,
    receiveReturnDto: ReceiveReturnDto, options?: RequestInit): Promise<ReturnsController_receiveReturnResponse> => {

  return customInstance<ReturnsController_receiveReturnResponse>(getReturnsControllerReceiveReturnUrl(id),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(receiveReturnDto)
  }
);}





export const getReturnsControllerReceiveReturnQueryKey = (id: string,
    receiveReturnDto?: ReceiveReturnDto,) => {
    return [
    'POST', `/api/v1/wms/web/customer-returns/${id}/receive`, receiveReturnDto
    ] as const;
    }


export const getReturnsControllerReceiveReturnQueryOptions = <TData = Awaited<ReturnType<typeof ReturnsController_receiveReturn>>, TError = unknown>(id: string,
    receiveReturnDto: ReceiveReturnDto, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof ReturnsController_receiveReturn>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getReturnsControllerReceiveReturnQueryKey(id,receiveReturnDto);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof ReturnsController_receiveReturn>>> = ({ signal }) => ReturnsController_receiveReturn(id,receiveReturnDto, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof ReturnsController_receiveReturn>>, TError, TData> & { queryKey: QueryKey }
}

export type ReturnsControllerReceiveReturnQueryResult = NonNullable<Awaited<ReturnType<typeof ReturnsController_receiveReturn>>>
export type ReturnsControllerReceiveReturnQueryError = unknown


/**
 * @summary Receive returned items (creates inventory holds for QC)
 */

export function useReturnsControllerReceiveReturn<TData = Awaited<ReturnType<typeof ReturnsController_receiveReturn>>, TError = unknown>(
 id: string,
    receiveReturnDto: ReceiveReturnDto, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof ReturnsController_receiveReturn>>, TError, TData>, request?: SecondParameter<typeof customInstance>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getReturnsControllerReceiveReturnQueryOptions(id,receiveReturnDto,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}






