/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * WMS API
 * Warehouse Management System API
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateFacilityAccessDto,
  FacilityAccessResponseDto,
  PaginatedResponseDto,
  UpdateFacilityAccessDto
} from '../../../types/wms-api';

import { customInstance } from '../../../http/httpClient.js';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type FacilityAccessController_createResponse201 = {
  data: FacilityAccessResponseDto
  status: 201
}

export type FacilityAccessController_createResponseSuccess = (FacilityAccessController_createResponse201) & {
  headers: Headers;
};
;

export type FacilityAccessController_createResponse = (FacilityAccessController_createResponseSuccess)

export const getFacilityAccessControllerCreateUrl = () => {




  return `/api/v1/wms/web/facility-access`
}

/**
 * @summary Create facility access control record
 */
export const FacilityAccessController_create = async (createFacilityAccessDto: CreateFacilityAccessDto, options?: RequestInit): Promise<FacilityAccessController_createResponse> => {

  return customInstance<FacilityAccessController_createResponse>(getFacilityAccessControllerCreateUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createFacilityAccessDto)
  }
);}





export const getFacilityAccessControllerCreateQueryKey = (createFacilityAccessDto?: CreateFacilityAccessDto,) => {
    return [
    'POST', `/api/v1/wms/web/facility-access`, createFacilityAccessDto
    ] as const;
    }


export const getFacilityAccessControllerCreateQueryOptions = <TData = Awaited<ReturnType<typeof FacilityAccessController_create>>, TError = unknown>(createFacilityAccessDto: CreateFacilityAccessDto, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof FacilityAccessController_create>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getFacilityAccessControllerCreateQueryKey(createFacilityAccessDto);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof FacilityAccessController_create>>> = ({ signal }) => FacilityAccessController_create(createFacilityAccessDto, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof FacilityAccessController_create>>, TError, TData> & { queryKey: QueryKey }
}

export type FacilityAccessControllerCreateQueryResult = NonNullable<Awaited<ReturnType<typeof FacilityAccessController_create>>>
export type FacilityAccessControllerCreateQueryError = unknown


/**
 * @summary Create facility access control record
 */

export function useFacilityAccessControllerCreate<TData = Awaited<ReturnType<typeof FacilityAccessController_create>>, TError = unknown>(
 createFacilityAccessDto: CreateFacilityAccessDto, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof FacilityAccessController_create>>, TError, TData>, request?: SecondParameter<typeof customInstance>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getFacilityAccessControllerCreateQueryOptions(createFacilityAccessDto,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}






export type FacilityAccessController_findAllResponse200 = {
  data: PaginatedResponseDto
  status: 200
}

export type FacilityAccessController_findAllResponseSuccess = (FacilityAccessController_findAllResponse200) & {
  headers: Headers;
};
;

export type FacilityAccessController_findAllResponse = (FacilityAccessController_findAllResponseSuccess)

export const getFacilityAccessControllerFindAllUrl = () => {




  return `/api/v1/wms/web/facility-access`
}

/**
 * @summary List facility access control records
 */
export const FacilityAccessController_findAll = async ( options?: RequestInit): Promise<FacilityAccessController_findAllResponse> => {

  return customInstance<FacilityAccessController_findAllResponse>(getFacilityAccessControllerFindAllUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getFacilityAccessControllerFindAllMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof FacilityAccessController_findAll>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof FacilityAccessController_findAll>>, TError,void, TContext> => {

const mutationKey = ['facilityAccessControllerFindAll'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof FacilityAccessController_findAll>>, void> = () => {


          return  FacilityAccessController_findAll(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type FacilityAccessControllerFindAllMutationResult = NonNullable<Awaited<ReturnType<typeof FacilityAccessController_findAll>>>

    export type FacilityAccessControllerFindAllMutationError = unknown

    /**
 * @summary List facility access control records
 */
export const useFacilityAccessControllerFindAll = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof FacilityAccessController_findAll>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof FacilityAccessController_findAll>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getFacilityAccessControllerFindAllMutationOptions(options));
    }
    export type FacilityAccessController_findByIdResponse200 = {
  data: FacilityAccessResponseDto
  status: 200
}

export type FacilityAccessController_findByIdResponseSuccess = (FacilityAccessController_findByIdResponse200) & {
  headers: Headers;
};
;

export type FacilityAccessController_findByIdResponse = (FacilityAccessController_findByIdResponseSuccess)

export const getFacilityAccessControllerFindByIdUrl = (id: string,) => {




  return `/api/v1/wms/web/facility-access/${id}`
}

/**
 * @summary Get facility access control record
 */
export const FacilityAccessController_findById = async (id: string, options?: RequestInit): Promise<FacilityAccessController_findByIdResponse> => {

  return customInstance<FacilityAccessController_findByIdResponse>(getFacilityAccessControllerFindByIdUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getFacilityAccessControllerFindByIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof FacilityAccessController_findById>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof FacilityAccessController_findById>>, TError,{id: string}, TContext> => {

const mutationKey = ['facilityAccessControllerFindById'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof FacilityAccessController_findById>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  FacilityAccessController_findById(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type FacilityAccessControllerFindByIdMutationResult = NonNullable<Awaited<ReturnType<typeof FacilityAccessController_findById>>>

    export type FacilityAccessControllerFindByIdMutationError = unknown

    /**
 * @summary Get facility access control record
 */
export const useFacilityAccessControllerFindById = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof FacilityAccessController_findById>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof FacilityAccessController_findById>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getFacilityAccessControllerFindByIdMutationOptions(options));
    }
    export type FacilityAccessController_updateResponse200 = {
  data: FacilityAccessResponseDto
  status: 200
}

export type FacilityAccessController_updateResponseSuccess = (FacilityAccessController_updateResponse200) & {
  headers: Headers;
};
;

export type FacilityAccessController_updateResponse = (FacilityAccessController_updateResponseSuccess)

export const getFacilityAccessControllerUpdateUrl = (id: string,) => {




  return `/api/v1/wms/web/facility-access/${id}`
}

/**
 * @summary Update facility access control record
 */
export const FacilityAccessController_update = async (id: string,
    updateFacilityAccessDto: UpdateFacilityAccessDto, options?: RequestInit): Promise<FacilityAccessController_updateResponse> => {

  return customInstance<FacilityAccessController_updateResponse>(getFacilityAccessControllerUpdateUrl(id),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateFacilityAccessDto)
  }
);}





export const getFacilityAccessControllerUpdateQueryKey = (id: string,
    updateFacilityAccessDto?: UpdateFacilityAccessDto,) => {
    return [
    'PATCH', `/api/v1/wms/web/facility-access/${id}`, updateFacilityAccessDto
    ] as const;
    }


export const getFacilityAccessControllerUpdateQueryOptions = <TData = Awaited<ReturnType<typeof FacilityAccessController_update>>, TError = unknown>(id: string,
    updateFacilityAccessDto: UpdateFacilityAccessDto, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof FacilityAccessController_update>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getFacilityAccessControllerUpdateQueryKey(id,updateFacilityAccessDto);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof FacilityAccessController_update>>> = ({ signal }) => FacilityAccessController_update(id,updateFacilityAccessDto, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof FacilityAccessController_update>>, TError, TData> & { queryKey: QueryKey }
}

export type FacilityAccessControllerUpdateQueryResult = NonNullable<Awaited<ReturnType<typeof FacilityAccessController_update>>>
export type FacilityAccessControllerUpdateQueryError = unknown


/**
 * @summary Update facility access control record
 */

export function useFacilityAccessControllerUpdate<TData = Awaited<ReturnType<typeof FacilityAccessController_update>>, TError = unknown>(
 id: string,
    updateFacilityAccessDto: UpdateFacilityAccessDto, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof FacilityAccessController_update>>, TError, TData>, request?: SecondParameter<typeof customInstance>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getFacilityAccessControllerUpdateQueryOptions(id,updateFacilityAccessDto,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}






export type FacilityAccessController_deleteResponse200 = {
  data: FacilityAccessResponseDto
  status: 200
}

export type FacilityAccessController_deleteResponseSuccess = (FacilityAccessController_deleteResponse200) & {
  headers: Headers;
};
;

export type FacilityAccessController_deleteResponse = (FacilityAccessController_deleteResponseSuccess)

export const getFacilityAccessControllerDeleteUrl = (id: string,) => {




  return `/api/v1/wms/web/facility-access/${id}`
}

/**
 * @summary Delete facility access control record
 */
export const FacilityAccessController_delete = async (id: string, options?: RequestInit): Promise<FacilityAccessController_deleteResponse> => {

  return customInstance<FacilityAccessController_deleteResponse>(getFacilityAccessControllerDeleteUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getFacilityAccessControllerDeleteQueryKey = (id: string,) => {
    return [
    'DELETE', `/api/v1/wms/web/facility-access/${id}`
    ] as const;
    }


export const getFacilityAccessControllerDeleteQueryOptions = <TData = Awaited<ReturnType<typeof FacilityAccessController_delete>>, TError = unknown>(id: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof FacilityAccessController_delete>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getFacilityAccessControllerDeleteQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof FacilityAccessController_delete>>> = ({ signal }) => FacilityAccessController_delete(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof FacilityAccessController_delete>>, TError, TData> & { queryKey: QueryKey }
}

export type FacilityAccessControllerDeleteQueryResult = NonNullable<Awaited<ReturnType<typeof FacilityAccessController_delete>>>
export type FacilityAccessControllerDeleteQueryError = unknown


/**
 * @summary Delete facility access control record
 */

export function useFacilityAccessControllerDelete<TData = Awaited<ReturnType<typeof FacilityAccessController_delete>>, TError = unknown>(
 id: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof FacilityAccessController_delete>>, TError, TData>, request?: SecondParameter<typeof customInstance>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getFacilityAccessControllerDeleteQueryOptions(id,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}






